Jamus Scheme: java_cup.symbol Class Reference
java_cup.symbol Class Reference
Public Member Functions
symbol (String nm, String tp)
symbol (String nm)
String name ()
String stack_type ()
int use_count ()
void note_use ()
int index ()
abstract boolean is_non_term ()
String toString ()
Protected Attributes
String _name
String _stack_type
int _use_count = 0
int _index
Detailed Description
This abstract class serves as the base class for grammar symbols (i.e., both terminals and non-terminals). Each symbol has a name string, and a string giving the type of object that the symbol will be represented by on the runtime parse stack. In addition, each symbol maintains a use count in order to detect symbols that are declared but never used, and an index number that indicates where it appears in parse tables (index numbers are unique within terminals or non terminals, but not across both).
See also:
java_cup.terminal
java_cup.non_terminal
Version:
last updated: 7/3/96
Author:
Frank Flannery
Definition at line 16 of file symbol.java.
Constructor & Destructor Documentation
java_cup.symbol.symbol (String nm, String tp)
Full constructor.
Parameters:
nm the name of the symbol.
tp a string with the type name.
Definition at line 25 of file symbol.java.
References java_cup.symbol._name, and java_cup.symbol._stack_type.
java_cup.symbol.symbol (String nm)
Constructor with default type.
Parameters:
nm the name of the symbol.
Definition at line 42 of file symbol.java.
Member Function Documentation
int java_cup.symbol.index ()
Index of this symbol (terminal or non terminal) in the parse tables. Note: indexes are unique among terminals and unique among non terminals, however, a terminal may have the same index as a non-terminal, etc.
Definition at line 88 of file symbol.java.
References java_cup.symbol._index.
Referenced by java_cup.lalr_state.build_table_entries(), java_cup.emit.emit_action_code(), java_cup.emit.emit_production_table(), java_cup.emit.parser(), java_cup.lalr_state.report_shift_reduce(), java_cup.emit.symbols(), java_cup.terminal.toString(), and java_cup.non_terminal.toString().
abstract boolean java_cup.symbol.is_non_term () [pure virtual]
Indicate if this is a non-terminal. Here in the base class we don't know, so this is abstract.
Implemented in java_cup.non_terminal, and java_cup.terminal.
Referenced by java_cup.lalr_state.build_table_entries(), java_cup.lalr_item.calc_lookahead(), java_cup.production.check_first_set(), java_cup.production.check_nullable(), java_cup.lr_item_core.dot_before_nt(), java_cup.lalr_item.lookahead_visible(), and java_cup.lalr_state.report_shift_reduce().
String java_cup.symbol.name ()
String for the human readable name of the symbol.
Definition at line 55 of file symbol.java.
References java_cup.symbol._name.
Referenced by java_cup.Main.check_unused(), java_cup.symbol_set.contains(), java_cup.Main.dump_grammar(), java_cup.lalr_state.dump_state(), java_cup.emit.emit_action_code(), java_cup.lalr_state.report_reduce_reduce(), java_cup.lalr_state.report_shift_reduce(), java_cup.emit.symbols(), java_cup.lr_item_core.to_simple_string(), java_cup.production.to_simple_string(), java_cup.lalr_transition.toString(), java_cup.symbol.toString(), java_cup.terminal_set.toString(), and java_cup.lalr_item.toString().
void java_cup.symbol.note_use ()
Increment the use count.
Definition at line 74 of file symbol.java.
References java_cup.symbol._use_count.
String java_cup.symbol.stack_type ()
String for the type of object used for the symbol on the parse stack.
Definition at line 63 of file symbol.java.
References java_cup.symbol._stack_type.
Referenced by java_cup.production.declare_labels(), and java_cup.emit.emit_action_code().
String java_cup.symbol.toString ()
Convert to a string.
Reimplemented in java_cup.non_terminal, and java_cup.terminal.
Definition at line 100 of file symbol.java.
References java_cup.symbol.name().
int java_cup.symbol.use_count ()
Count of how many times the symbol appears in productions.
Definition at line 71 of file symbol.java.
References java_cup.symbol._use_count.
Referenced by java_cup.Main.check_unused().
Member Data Documentation
int java_cup.symbol._index [protected]
Index of this symbol (terminal or non terminal) in the parse tables. Note: indexes are unique among terminals and unique among non terminals, however, a terminal may have the same index as a non-terminal, etc.
Definition at line 82 of file symbol.java.
Referenced by java_cup.symbol.index(), java_cup.non_terminal.non_terminal(), and java_cup.terminal.terminal().
String java_cup.symbol._name [protected]
String for the human readable name of the symbol.
Definition at line 52 of file symbol.java.
Referenced by java_cup.symbol.name(), and java_cup.symbol.symbol().
String java_cup.symbol._stack_type [protected]
String for the type of object used for the symbol on the parse stack.
Definition at line 60 of file symbol.java.
Referenced by java_cup.symbol.stack_type(), and java_cup.symbol.symbol().
int java_cup.symbol._use_count = 0 [protected]
Count of how many times the symbol appears in productions.
Definition at line 68 of file symbol.java.
Referenced by java_cup.symbol.note_use(), and java_cup.symbol.use_count().
The documentation for this class was generated from the following file:
src/java_cup/symbol.java