/**
 * generated by Xtext 2.12.0
 */
package de.htwdd.sf.beleg.customProlog;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Functor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.customProlog.Functor#getFuncName <em>Func Name</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.customProlog.CustomPrologPackage#getFunctor()
 * @model
 * @generated
 */
public interface Functor extends EObject
{
  /**
   * Returns the value of the '<em><b>Func Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Func Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func Name</em>' attribute.
   * @see #setFuncName(String)
   * @see de.htwdd.sf.beleg.customProlog.CustomPrologPackage#getFunctor_FuncName()
   * @model
   * @generated
   */
  String getFuncName();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.customProlog.Functor#getFuncName <em>Func Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func Name</em>' attribute.
   * @see #getFuncName()
   * @generated
   */
  void setFuncName(String value);

} // Functor
