/**
 * generated by Xtext 2.12.0
 */
package de.htwdd.sf.beleg.customProlog;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.customProlog.List#getNonempty <em>Nonempty</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.customProlog.CustomPrologPackage#getList()
 * @model
 * @generated
 */
public interface List extends EObject
{
  /**
   * Returns the value of the '<em><b>Nonempty</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nonempty</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nonempty</em>' containment reference.
   * @see #setNonempty(NonEmptyList)
   * @see de.htwdd.sf.beleg.customProlog.CustomPrologPackage#getList_Nonempty()
   * @model containment="true"
   * @generated
   */
  NonEmptyList getNonempty();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.customProlog.List#getNonempty <em>Nonempty</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nonempty</em>' containment reference.
   * @see #getNonempty()
   * @generated
   */
  void setNonempty(NonEmptyList value);

} // List
