/**
 * generated by Xtext 2.12.0
 */
package de.htwdd.sf.beleg.customProlog;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prologdsl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.customProlog.Prologdsl#getProgram <em>Program</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.customProlog.Prologdsl#getExquery <em>Exquery</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.customProlog.CustomPrologPackage#getPrologdsl()
 * @model
 * @generated
 */
public interface Prologdsl extends EObject
{
  /**
   * Returns the value of the '<em><b>Program</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Program</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Program</em>' containment reference.
   * @see #setProgram(Program)
   * @see de.htwdd.sf.beleg.customProlog.CustomPrologPackage#getPrologdsl_Program()
   * @model containment="true"
   * @generated
   */
  Program getProgram();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.customProlog.Prologdsl#getProgram <em>Program</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Program</em>' containment reference.
   * @see #getProgram()
   * @generated
   */
  void setProgram(Program value);

  /**
   * Returns the value of the '<em><b>Exquery</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exquery</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exquery</em>' containment reference.
   * @see #setExquery(Exquery)
   * @see de.htwdd.sf.beleg.customProlog.CustomPrologPackage#getPrologdsl_Exquery()
   * @model containment="true"
   * @generated
   */
  Exquery getExquery();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.customProlog.Prologdsl#getExquery <em>Exquery</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exquery</em>' containment reference.
   * @see #getExquery()
   * @generated
   */
  void setExquery(Exquery value);

} // Prologdsl
