Jamus Scheme: java_cup.shift_action Class Reference
java_cup.shift_action Class Reference
Public Member Functions
shift_action (lalr_state shft_to) throws internal_error
lalr_state shift_to ()
int kind ()
boolean equals (shift_action other)
boolean equals (Object other)
int hashCode ()
String toString ()
Protected Attributes
lalr_state _shift_to
Detailed Description
This class represents a shift action within the parse table. The action simply stores the state that it shifts to and responds to queries about its type.
Version:
last updated: 11/25/95
Author:
Scott Hudson
Definition at line 11 of file shift_action.java.
Constructor & Destructor Documentation
java_cup.shift_action.shift_action (lalr_state shft_to) throws internal_error
Simple constructor.
Parameters:
shft_to the state that this action shifts to.
Definition at line 20 of file shift_action.java.
References java_cup.shift_action._shift_to.
Member Function Documentation
boolean java_cup.shift_action.equals (shift_action other)
Equality test.
Definition at line 50 of file shift_action.java.
References java_cup.shift_action.shift_to().
Referenced by java_cup.shift_action.equals().
boolean java_cup.shift_action.equals (Object other)
Generic equality test.
Reimplemented from java_cup.parse_action.
Definition at line 58 of file shift_action.java.
References java_cup.shift_action.equals().
int java_cup.shift_action.hashCode ()
Compute a hash code.
Reimplemented from java_cup.parse_action.
Definition at line 69 of file shift_action.java.
References java_cup.lalr_state.hashCode(), and java_cup.shift_action.shift_to().
int java_cup.shift_action.kind ()
Quick access to type of action.
Reimplemented from java_cup.parse_action.
Definition at line 45 of file shift_action.java.
References java_cup.parse_action.SHIFT.
lalr_state java_cup.shift_action.shift_to ()
The state we shift to.
Definition at line 38 of file shift_action.java.
References java_cup.shift_action._shift_to.
Referenced by java_cup.shift_action.equals(), java_cup.shift_action.hashCode(), and java_cup.shift_action.toString().
String java_cup.shift_action.toString ()
Convert to a string.
Reimplemented from java_cup.parse_action.
Definition at line 78 of file shift_action.java.
References java_cup.lalr_state.index(), and java_cup.shift_action.shift_to().
Member Data Documentation
lalr_state java_cup.shift_action._shift_to [protected]
The state we shift to.
Definition at line 35 of file shift_action.java.
Referenced by java_cup.shift_action.shift_action(), and java_cup.shift_action.shift_to().
The documentation for this class was generated from the following file:
src/java_cup/shift_action.java