/**
 * generated by Xtext 2.11.0
 */
package de.htwdd.sf.beleg.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class CustomPrologQuickfixProvider extends DefaultQuickfixProvider {
}
