/**
 * generated by Xtext 2.11.0
 */
package de.htwdd.sf.beleg.ui.labeling;

import com.google.inject.Inject;
import de.htwdd.sf.beleg.customProlog.Atom;
import de.htwdd.sf.beleg.customProlog.Clause;
import de.htwdd.sf.beleg.customProlog.Exquery;
import de.htwdd.sf.beleg.customProlog.Fact;
import de.htwdd.sf.beleg.customProlog.Folge;
import de.htwdd.sf.beleg.customProlog.Functor;
import de.htwdd.sf.beleg.customProlog.List;
import de.htwdd.sf.beleg.customProlog.NonEmptyList;
import de.htwdd.sf.beleg.customProlog.Predicate;
import de.htwdd.sf.beleg.customProlog.Program;
import de.htwdd.sf.beleg.customProlog.Prologdsl;
import de.htwdd.sf.beleg.customProlog.Query;
import de.htwdd.sf.beleg.customProlog.Rule;
import de.htwdd.sf.beleg.customProlog.Term;
import de.htwdd.sf.beleg.services.CustomPrologGrammarAccess;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class CustomPrologLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public CustomPrologLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String text(final Program p) {
    return "Program";
  }
  
  public String text(final Clause c) {
    return "Clause";
  }
  
  public String text(final Prologdsl p) {
    return "Prologdsl";
  }
  
  public String text(final CustomPrologGrammarAccess.PrologdslElements e) {
    return "PrologdslElement";
  }
  
  public String text(final Predicate p) {
    return "Predicate: ";
  }
  
  public String text(final List l) {
    return "List";
  }
  
  public String text(final Folge f) {
    return "Folge";
  }
  
  public String text(final Exquery e) {
    return "?- Exquery";
  }
  
  public String text(final Functor f) {
    String _funcName = f.getFuncName();
    String _plus = ("Functor \"" + _funcName);
    return (_plus + "\"");
  }
  
  public String text(final Fact f) {
    return "Fact";
  }
  
  public String text(final Atom a) {
    return a.getIdent();
  }
  
  public String text(final Term t) {
    return "Term";
  }
  
  public String text(final Query q) {
    return "Query";
  }
  
  public String text(final Rule r) {
    return "Rule";
  }
  
  public String text(final NonEmptyList nel) {
    return "NonEmptyList";
  }
}
