Jamus Scheme: java_cup.internal_error Class Reference
java_cup.internal_error Class Reference
Public Member Functions
internal_error (String msg)
void crash ()
Detailed Description
Exception subclass for reporting internal errors in JavaCup.
Definition at line 5 of file internal_error.java.
Constructor & Destructor Documentation
java_cup.internal_error.internal_error (String msg)
Constructor with a message
Definition at line 8 of file internal_error.java.
Member Function Documentation
void java_cup.internal_error.crash ()
Method called to do a forced error exit on an internal error for cases when we can't actually throw the exception.
Definition at line 15 of file internal_error.java.
Referenced by java_cup.symbol_set.equals(), java_cup.lalr_item_set.equals(), java_cup.lr_item_core.toString(), and java_cup.production.toString().
The documentation for this class was generated from the following file:
src/java_cup/internal_error.java