Jamus Scheme: java_cup.parse_reduce_row Class Reference
java_cup.parse_reduce_row Class Reference
Public Member Functions
parse_reduce_row ()
Static Public Member Functions
static int size ()
Public Attributes
lalr_state under_non_term []
Static Protected Attributes
static int _size = 0
Detailed Description
This class represents one row (corresponding to one machine state) of the reduce-goto parse table.
Definition at line 7 of file parse_reduce_row.java.
Constructor & Destructor Documentation
java_cup.parse_reduce_row.parse_reduce_row ()
Simple constructor. Note: this should not be used until the number of terminals in the grammar has been established.
Definition at line 15 of file parse_reduce_row.java.
References java_cup.parse_reduce_row._size, java_cup.non_terminal.number(), java_cup.parse_reduce_row.size(), and java_cup.parse_reduce_row.under_non_term.
Member Function Documentation
static int java_cup.parse_reduce_row.size () [static]
Number of columns (non terminals) in every row.
Definition at line 32 of file parse_reduce_row.java.
References java_cup.parse_reduce_row._size.
Referenced by java_cup.emit.do_reduce_table(), java_cup.parse_reduce_row.parse_reduce_row(), and java_cup.parse_reduce_table.toString().
Member Data Documentation
int java_cup.parse_reduce_row._size = 0 [static, protected]
Number of columns (non terminals) in every row.
Definition at line 29 of file parse_reduce_row.java.
Referenced by java_cup.parse_reduce_row.parse_reduce_row(), and java_cup.parse_reduce_row.size().
lalr_state java_cup.parse_reduce_row.under_non_term[]
Actual entries for the row.
Definition at line 39 of file parse_reduce_row.java.
Referenced by java_cup.lalr_state.build_table_entries(), java_cup.emit.do_reduce_table(), java_cup.parse_reduce_row.parse_reduce_row(), and java_cup.parse_reduce_table.toString().
The documentation for this class was generated from the following file:
src/java_cup/parse_reduce_row.java