/*
 * generated by Xtext 2.12.0
 */
package de.htwdd.sf.beleg.ui;

import com.google.inject.Injector;

import de.htwdd.sf.beleg.s81170.ui.internal.S81170Activator;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CustomPrologExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return S81170Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return S81170Activator.getInstance().getInjector(S81170Activator.DE_HTWDD_SF_BELEG_CUSTOMPROLOG);
	}
	
}
