/**
 * generated by Xtext 2.11.0
 */
package de.htwdd.sf.beleg;

import de.htwdd.sf.beleg.AbstractCustomPrologRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CustomPrologRuntimeModule extends AbstractCustomPrologRuntimeModule {
}
