/**
 * generated by Xtext 2.11.0
 */
package de.htwdd.sf.beleg;

import de.htwdd.sf.beleg.CustomPrologStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CustomPrologStandaloneSetup extends CustomPrologStandaloneSetupGenerated {
  public static void doSetup() {
    new CustomPrologStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
