Jamus Scheme: java_cup.non_terminal Class Reference
java_cup.non_terminal Class Reference
Public Member Functions
non_terminal (String nm, String tp)
non_terminal (String nm)
Enumeration productions ()
int num_productions ()
void add_production (production prod) throws internal_error
boolean nullable ()
terminal_set first_set ()
boolean is_non_term ()
String toString ()
Static Public Member Functions
static Enumeration all ()
static non_terminal find (String with_name)
static non_terminal find (int indx)
static int number ()
static void compute_nullability () throws internal_error
static void compute_first_sets () throws internal_error
Public Attributes
boolean is_embedded_action = false
Static Public Attributes
static final non_terminal START_nt = new non_terminal("$START")
Protected Member Functions
boolean looks_nullable () throws internal_error
Protected Attributes
Hashtable _productions = new Hashtable(11)
boolean _nullable
terminal_set _first_set = new terminal_set()
Static Protected Attributes
static Hashtable _all = new Hashtable()
static Hashtable _all_by_index = new Hashtable()
static int next_index = 0
static int next_nt = 0
Static Package Functions
static non_terminal create_new (String prefix) throws internal_error
static non_terminal create_new () throws internal_error
Detailed Description
This class represents a non-terminal symbol in the grammar. Each non terminal has a textual name, an index, and a string which indicates the type of object it will be implemented with at runtime (i.e. the class of object that will be pushed on the parse stack to represent it).
Version:
last updated: 11/25/95
Author:
Scott Hudson
Definition at line 15 of file non_terminal.java.
Constructor & Destructor Documentation
java_cup.non_terminal.non_terminal (String nm, String tp)
Full constructor.
Parameters:
nm the name of the non terminal.
tp the type string for the non terminal.
Definition at line 25 of file non_terminal.java.
References java_cup.non_terminal._all, java_cup.non_terminal._all_by_index, java_cup.symbol._index, and java_cup.non_terminal.next_index.
Referenced by java_cup.non_terminal.compute_first_sets(), java_cup.non_terminal.compute_nullability(), and java_cup.non_terminal.create_new().
java_cup.non_terminal.non_terminal (String nm)
Constructor with default type.
Parameters:
nm the name of the non terminal.
Definition at line 51 of file non_terminal.java.
Member Function Documentation
void java_cup.non_terminal.add_production (production prod) throws internal_error
Add a production to our set of productions.
Definition at line 240 of file non_terminal.java.
References java_cup.non_terminal._productions.
static Enumeration java_cup.non_terminal.all () [static]
Access to all non-terminals.
Definition at line 66 of file non_terminal.java.
References java_cup.non_terminal._all.
Referenced by java_cup.Main.check_unused(), java_cup.non_terminal.compute_first_sets(), java_cup.non_terminal.compute_nullability(), and java_cup.emit.symbols().
static void java_cup.non_terminal.compute_first_sets () throws internal_error [static]
Compute first sets for all non-terminals. This assumes nullability has already computed.
Definition at line 183 of file non_terminal.java.
References java_cup.non_terminal._first_set, java_cup.terminal_set.add(), java_cup.non_terminal.all(), java_cup.production.check_first_set(), java_cup.terminal_set.is_subset_of(), java_cup.non_terminal.non_terminal(), and java_cup.non_terminal.productions().
Referenced by java_cup.Main.build_parser().
static void java_cup.non_terminal.compute_nullability () throws internal_error [static]
Compute nullability of all non-terminals.
Definition at line 140 of file non_terminal.java.
References java_cup.non_terminal._nullable, java_cup.non_terminal.all(), java_cup.production.all(), java_cup.production.check_nullable(), java_cup.non_terminal.looks_nullable(), java_cup.non_terminal.non_terminal(), java_cup.non_terminal.nullable(), and java_cup.production.set_nullable().
Referenced by java_cup.Main.build_parser().
static non_terminal java_cup.non_terminal.create_new (String prefix) throws internal_error [static, package]
Method for creating a new uniquely named hidden non-terminal using the given string as a base for the name (or "NT$" if null is passed).
Parameters:
prefix base name to construct unique name from.
Definition at line 123 of file non_terminal.java.
References java_cup.non_terminal.next_nt, and java_cup.non_terminal.non_terminal().
Referenced by java_cup.production.remove_embedded_actions().
static non_terminal java_cup.non_terminal.create_new () throws internal_error [static, package]
static routine for creating a new uniquely named hidden non-terminal
Definition at line 132 of file non_terminal.java.
static non_terminal java_cup.non_terminal.find (String with_name) [static]
lookup a non terminal by name string
Definition at line 69 of file non_terminal.java.
References java_cup.non_terminal._all.
Referenced by java_cup.Main.dump_grammar().
static non_terminal java_cup.non_terminal.find (int indx) [static]
Lookup a non terminal by index.
Definition at line 83 of file non_terminal.java.
References java_cup.non_terminal._all_by_index.
terminal_set java_cup.non_terminal.first_set ()
First set for this non-terminal.
Definition at line 265 of file non_terminal.java.
References java_cup.non_terminal._first_set.
boolean java_cup.non_terminal.is_non_term () [virtual]
Indicate that this symbol is a non-terminal.
Implements java_cup.symbol.
Definition at line 272 of file non_terminal.java.
boolean java_cup.non_terminal.looks_nullable () throws internal_error [protected]
Test to see if this non terminal currently looks nullable.
Definition at line 280 of file non_terminal.java.
References java_cup.non_terminal.productions().
Referenced by java_cup.non_terminal.compute_nullability().
boolean java_cup.non_terminal.nullable ()
Nullability of this non terminal.
Definition at line 257 of file non_terminal.java.
References java_cup.non_terminal._nullable.
Referenced by java_cup.non_terminal.compute_nullability(), and java_cup.non_terminal.toString().
int java_cup.non_terminal.num_productions ()
Total number of productions with this non terminal on the LHS.
Definition at line 235 of file non_terminal.java.
References java_cup.non_terminal._productions.
static int java_cup.non_terminal.number () [static]
Total number of non-terminals.
Definition at line 93 of file non_terminal.java.
References java_cup.non_terminal._all.
Referenced by java_cup.Main.dump_grammar(), java_cup.Main.emit_summary(), and java_cup.parse_reduce_row.parse_reduce_row().
Enumeration java_cup.non_terminal.productions ()
Access to productions with this non terminal on the LHS.
Definition at line 230 of file non_terminal.java.
References java_cup.non_terminal._productions.
Referenced by java_cup.lalr_item_set.compute_closure(), java_cup.non_terminal.compute_first_sets(), and java_cup.non_terminal.looks_nullable().
String java_cup.non_terminal.toString ()
convert to string
Reimplemented from java_cup.symbol.
Definition at line 295 of file non_terminal.java.
References java_cup.symbol.index(), and java_cup.non_terminal.nullable().
Member Data Documentation
Hashtable java_cup.non_terminal._all = new Hashtable() [static, protected]
Table of all non-terminals -- elements are stored using name strings as the key
Definition at line 63 of file non_terminal.java.
Referenced by java_cup.non_terminal.all(), java_cup.non_terminal.find(), java_cup.non_terminal.non_terminal(), and java_cup.non_terminal.number().
Hashtable java_cup.non_terminal._all_by_index = new Hashtable() [static, protected]
Table of all non terminals indexed by their index number.
Definition at line 80 of file non_terminal.java.
Referenced by java_cup.non_terminal.find(), and java_cup.non_terminal.non_terminal().
terminal_set java_cup.non_terminal._first_set = new terminal_set() [protected]
First set for this non-terminal.
Definition at line 262 of file non_terminal.java.
Referenced by java_cup.non_terminal.compute_first_sets(), and java_cup.non_terminal.first_set().
boolean java_cup.non_terminal._nullable [protected]
Nullability of this non terminal.
Definition at line 254 of file non_terminal.java.
Referenced by java_cup.non_terminal.compute_nullability(), and java_cup.non_terminal.nullable().
Hashtable java_cup.non_terminal._productions = new Hashtable(11) [protected]
Table of all productions with this non terminal on the LHS.
Definition at line 227 of file non_terminal.java.
Referenced by java_cup.non_terminal.add_production(), java_cup.non_terminal.num_productions(), and java_cup.non_terminal.productions().
boolean java_cup.non_terminal.is_embedded_action = false
flag non-terminals created to embed action productions
Definition at line 113 of file non_terminal.java.
Referenced by java_cup.production.remove_embedded_actions().
int java_cup.non_terminal.next_index = 0 [static, protected]
Static counter to assign unique indexes.
Definition at line 98 of file non_terminal.java.
Referenced by java_cup.non_terminal.non_terminal().
int java_cup.non_terminal.next_nt = 0 [static, protected]
Static counter for creating unique non-terminal names
Definition at line 103 of file non_terminal.java.
Referenced by java_cup.non_terminal.create_new().
final non_terminal java_cup.non_terminal.START_nt = new non_terminal("$START") [static]
special non-terminal for start symbol
Definition at line 108 of file non_terminal.java.
Referenced by java_cup.$actions.$do_action().
The documentation for this class was generated from the following file:
src/java_cup/non_terminal.java