/**
 * generated by Xtext 2.11.0
 */
package de.htwdd.sf.beleg.ui.contentassist;

import de.htwdd.sf.beleg.ui.contentassist.AbstractCustomPrologProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CustomPrologProposalProvider extends AbstractCustomPrologProposalProvider {
}
