/*
 * generated by Xtext 2.12.0
 */
package de.htwdd.sf.beleg.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCustomPrologScopeProvider extends DelegatingScopeProvider {
}
