Jamus Scheme: Scheme.parser Class Reference
Scheme.parser Class Reference
Public Member Functions
parser ()
parser (java_cup.runtime.Scanner s)
short[][] production_table ()
short[][] action_table ()
short[][] reduce_table ()
java_cup.runtime.Symbol do_action (int act_num, java_cup.runtime.lr_parser parser, java.util.Stack stack, int top) throws java.lang.Exception
int start_state ()
int start_production ()
int EOF_sym ()
int error_sym ()
void syntax_error (java_cup.runtime.Symbol current)
Static Public Member Functions
static void main (String args[]) throws Exception
Protected Member Functions
void init_actions ()
Protected Attributes
CUP $parser $actions action_obj
Static Protected Attributes
static final short _production_table [][]
static final short[][] _action_table
static final short[][] _reduce_table
Detailed Description
CUP v0.10j generated parser.
Version:
Tue Oct 04 16:12:10 CEST 2005
Definition at line 18 of file parser.java.
Constructor & Destructor Documentation
Scheme.parser.parser ()
Default constructor.
Definition at line 21 of file parser.java.
Referenced by Scheme.parser.main().
Scheme.parser.parser (java_cup.runtime.Scanner s)
Constructor which sets the default scanner.
Definition at line 26 of file parser.java.
Member Function Documentation
short [][] Scheme.parser.action_table () [virtual]
Access to parse-action table.
Implements java_cup.runtime.lr_parser.
Definition at line 120 of file parser.java.
References Scheme.parser._action_table.
java_cup.runtime.Symbol Scheme.parser.do_action (int act_num, java_cup.runtime.lr_parser parser, java.util.Stack stack, int top) throws java.lang.Exception
Invoke a user supplied parse action.
Definition at line 162 of file parser.java.
References Scheme.parser.action_obj, and java_cup.runtime.lr_parser.stack.
int Scheme.parser.EOF_sym () [virtual]
EOF Symbol index.
Implements java_cup.runtime.lr_parser.
Definition at line 183 of file parser.java.
int Scheme.parser.error_sym () [virtual]
error Symbol index.
Implements java_cup.runtime.lr_parser.
Definition at line 189 of file parser.java.
void Scheme.parser.init_actions () [protected, virtual]
Action encapsulation object initializer.
Implements java_cup.runtime.lr_parser.
Definition at line 156 of file parser.java.
References Scheme.parser.action_obj.
static void Scheme.parser.main (String args[]) throws Exception [static]
Definition at line 193 of file parser.java.
References Scheme.parser.parser().
short [][] Scheme.parser.production_table () [virtual]
Access to production table.
Implements java_cup.runtime.lr_parser.
Definition at line 43 of file parser.java.
References Scheme.parser._production_table.
short [][] Scheme.parser.reduce_table () [virtual]
Access to reduce_goto table.
Implements java_cup.runtime.lr_parser.
Definition at line 147 of file parser.java.
References Scheme.parser._reduce_table.
int Scheme.parser.start_production () [virtual]
Indicates start production.
Implements java_cup.runtime.lr_parser.
Definition at line 177 of file parser.java.
int Scheme.parser.start_state () [virtual]
Indicates start state.
Implements java_cup.runtime.lr_parser.
Definition at line 171 of file parser.java.
void Scheme.parser.syntax_error (java_cup.runtime.Symbol current)
Definition at line 203 of file parser.java.
References java_cup.runtime.lr_parser.report_error().
Member Data Documentation
final short [][] Scheme.parser._action_table [static, protected]
Parse-action table.
Definition at line 48 of file parser.java.
Referenced by Scheme.parser.action_table().
final short Scheme.parser._production_table[][] [static, protected]
Initial value:
 unpackFromStrings(new String[] { "\000\033\000\002\002\004\000\002\003\004\000\002\004"
                        + "\004\000\002\004\003\000\002\005\004\000\002\005\004"
                        + "\000\002\005\004\000\002\005\003\000\002\006\003\000"
                        + "\002\006\003\000\002\006\003\000\002\006\003\000\002"
                        + "\006\003\000\002\006\003\000\002\006\003\000\002\006"
                        + "\003\000\002\007\004\000\002\010\003\000\002\015\002"
                        + "\000\002\010\005\000\002\011\004\000\002\012\003\000"
                        + "\002\012\004\000\002\012\002\000\002\013\005\000\002"
                        + "\014\004\000\002\014\002" })
Production table.
Definition at line 31 of file parser.java.
Referenced by Scheme.parser.production_table().
final short [][] Scheme.parser._reduce_table [static, protected]
Initial value:
 unpackFromStrings(new String[] { "\000\046\000\016\003\023\004\015\005\021\006\010\007"
                        + "\020\013\005\001\001\000\002\001\001\000\010\006\047"
                        + "\007\020\013\005\001\001\000\002\001\001\000\010\006"
                        + "\046\007\020\013\005\001\001\000\002\001\001\000\002"
                        + "\001\001\000\002\001\001\000\014\005\043\006\010\007"
                        + "\020\013\005\014\042\001\001\000\002\001\001\000\002"
                        + "\001\001\000\012\005\041\006\010\007\020\013\005\001"
                        + "\001\000\010\006\037\007\020\013\005\001\001\000\002"
                        + "\001\001\000\002\001\001\000\002\001\001\000\016\005"
                        + "\030\006\010\007\020\010\027\011\026\013\005\001\001"
                        + "\000\002\001\001\000\002\001\001\000\002\001\001\000"
                        + "\004\015\035\001\001\000\002\001\001\000\016\005\030"
                        + "\006\010\007\020\011\031\012\032\013\005\001\001\000"
                        + "\002\001\001\000\002\001\001\000\012\005\034\006\010"
                        + "\007\020\013\005\001\001\000\002\001\001\000\002\001"
                        + "\001\000\002\001\001\000\002\001\001\000\002\001\001"
                        + "\000\002\001\001\000\002\001\001\000\014\005\043\006"
                        + "\010\007\020\013\005\014\044\001\001\000\002\001\001"
                        + "\000\002\001\001\000\002\001\001\000\002\001\001" })
reduce_goto table.
Definition at line 125 of file parser.java.
Referenced by Scheme.parser.reduce_table().
CUP $parser $actions Scheme.parser.action_obj [protected]
Instance of action encapsulation class.
Definition at line 152 of file parser.java.
Referenced by Scheme.parser.do_action(), and Scheme.parser.init_actions().
The documentation for this class was generated from the following file:
src/Scheme/parser.java