Jamus Scheme: java_cup.production_part Class Reference
java_cup.production_part Class Reference
Public Member Functions
production_part (String lab)
String label ()
abstract boolean is_action ()
boolean equals (production_part other)
boolean equals (Object other)
int hashCode ()
String toString ()
Protected Attributes
String _label
Detailed Description
This class represents one part (either a symbol or an action) of a production. In this base class it contains only an optional label string that the user can use to refer to the part within actions.
This is an abstract class.
See also:
java_cup.production
Version:
last updated: 11/25/95
Author:
Scott Hudson
Definition at line 13 of file production_part.java.
Constructor & Destructor Documentation
java_cup.production_part.production_part (String lab)
Simple constructor.
Definition at line 20 of file production_part.java.
References java_cup.production_part._label.
Member Function Documentation
boolean java_cup.production_part.equals (production_part other)
Equality comparison.
Definition at line 51 of file production_part.java.
References java_cup.production_part.label().
Referenced by java_cup.production_part.equals().
boolean java_cup.production_part.equals (Object other)
Generic equality comparison.
Reimplemented in java_cup.symbol_part, and java_cup.action_part.
Definition at line 65 of file production_part.java.
References java_cup.production_part.equals().
int java_cup.production_part.hashCode ()
Produce a hash code.
Reimplemented in java_cup.symbol_part, and java_cup.action_part.
Definition at line 76 of file production_part.java.
References java_cup.production_part.label().
abstract boolean java_cup.production_part.is_action () [pure virtual]
Indicate if this is an action (rather than a symbol). Here in the base class, we don't this know yet, so its an abstract method.
Implemented in java_cup.symbol_part, and java_cup.action_part.
Referenced by java_cup.lalr_item.calc_lookahead(), java_cup.production.check_first_set(), java_cup.production.check_nullable(), java_cup.Main.dump_grammar(), java_cup.lalr_state.dump_state(), java_cup.lalr_item.lookahead_visible(), java_cup.lr_item_core.lr_item_core(), java_cup.production.remove_embedded_actions(), java_cup.lr_item_core.to_simple_string(), and java_cup.production.to_simple_string().
String java_cup.production_part.label ()
Optional label for referring to the part within an action (null for no label).
Definition at line 37 of file production_part.java.
References java_cup.production_part._label.
Referenced by java_cup.production.declare_labels(), java_cup.production_part.equals(), java_cup.production_part.hashCode(), and java_cup.production_part.toString().
String java_cup.production_part.toString ()
Convert to a string.
Reimplemented in java_cup.symbol_part, and java_cup.action_part.
Definition at line 84 of file production_part.java.
References java_cup.production_part.label().
Member Data Documentation
String java_cup.production_part._label [protected]
Optional label for referring to the part within an action (null for no label).
Definition at line 32 of file production_part.java.
Referenced by java_cup.production_part.label(), and java_cup.production_part.production_part().
The documentation for this class was generated from the following file:
src/java_cup/production_part.java