Jamus Scheme: Scheme.SchemeString Class Reference
Scheme.SchemeString Class Reference
Public Member Functions
SchemeString (String x)
String sprint ()
void print ()
ISchemeObject printp (BufferedWriter open_buffer_writer)
SchemeBoolean eqp (ISchemeObject o)
SchemeBoolean stringle (SchemeString s)
SchemeString stringappend (SchemeString s)
Symbol stringsymbol ()
SchemeBoolean equalp (ISchemeObject o)
ISchemeObject eval ()
Package Attributes
String value
Detailed Description
Definition at line 5 of file SchemeString.java.
Constructor & Destructor Documentation
Scheme.SchemeString.SchemeString (String x)
Definition at line 8 of file SchemeString.java.
References Scheme.SchemeString.value.
Referenced by Scheme.SchemeString.stringappend().
Member Function Documentation
SchemeBoolean Scheme.SchemeString.eqp (ISchemeObject compared_object)
Checks if this scheme object is (structural) equal to the given scheme object #compared_object.
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Returns:
a SchemeBoolean object with value 'true' if they are structural equal, else false.
Implements Scheme.ISchemeObject.
Definition at line 39 of file SchemeString.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, and Scheme.SchemeString.value.
SchemeBoolean Scheme.SchemeString.equalp (ISchemeObject compared_object)
Checks if this scheme object is equal (by value) to the given scheme object #compared_object.
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Returns:
a SchemeBoolean object with value 'true' if they are equal (have the same value), else false.
Implements Scheme.ISchemeObject.
Definition at line 84 of file SchemeString.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, and Scheme.SchemeString.value.
ISchemeObject Scheme.SchemeString.eval ()
Evaluates a scheme expression and returns a new scheme object. Which object is returned, depends on the scheme expression.
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Returns:
a scheme object. Which type of scheme object can be found out with castings.
Reimplemented from Scheme.StElem.
Definition at line 92 of file SchemeString.java.
void Scheme.SchemeString.print ()
Prints the scheme object to 'stdout' (mostly a console).
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Reimplemented from Scheme.StElem.
Definition at line 24 of file SchemeString.java.
References Scheme.SchemeString.sprint().
Referenced by Scheme.RunEnv.display().
ISchemeObject Scheme.SchemeString.printp (BufferedWriter open_buffer_writer)
Prints the scheme object to the BufferedWriter.
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Reimplemented from Scheme.StElem.
Definition at line 29 of file SchemeString.java.
References Scheme.RunEnv.nilval, and Scheme.SchemeString.sprint().
Referenced by Scheme.RunEnv.display().
String Scheme.SchemeString.sprint ()
Returns the scheme object as String.
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Reimplemented from Scheme.StElem.
Definition at line 19 of file SchemeString.java.
References Scheme.SchemeString.value.
Referenced by Scheme.SchemeString.print(), and Scheme.SchemeString.printp().
SchemeString Scheme.SchemeString.stringappend (SchemeString s)
Definition at line 53 of file SchemeString.java.
References Scheme.SchemeString.SchemeString(), and Scheme.SchemeString.value.
SchemeBoolean Scheme.SchemeString.stringle (SchemeString s)
Definition at line 46 of file SchemeString.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, and Scheme.SchemeString.value.
Symbol Scheme.SchemeString.stringsymbol ()
Converts a SchemeString object to a Symbol object. If this object is no SchemeString object, this method should return an empty Symbol object!
Returns:
a Symbol object with the value of this object, if the value is a string.
Implements Scheme.ISchemeString.
Definition at line 58 of file SchemeString.java.
References Scheme.RunEnv.checkbucket(), Scheme.ISchemeObject.cons(), Scheme.RunEnv.hash(), Scheme.RunEnv.hashtab, Scheme.RunEnv.nilval, and Scheme.SchemeString.value.
Member Data Documentation
String Scheme.SchemeString.value [package]
The value of this StElem object.
Reimplemented from Scheme.StElem.
Definition at line 6 of file SchemeString.java.
Referenced by Scheme.RunEnv.display(), Scheme.SchemeString.eqp(), Scheme.SchemeString.equalp(), Scheme.RunEnv.load(), Scheme.RunEnv.open_input_file(), Scheme.RunEnv.open_output_file(), Scheme.SchemeString.SchemeString(), Scheme.SchemeString.sprint(), Scheme.SchemeString.stringappend(), Scheme.SchemeString.stringle(), and Scheme.SchemeString.stringsymbol().
The documentation for this class was generated from the following file:
src/Scheme/SchemeString.java