/**
 * generated by Xtext 2.11.0
 */
package de.htwdd.sf.beleg.ui;

import de.htwdd.sf.beleg.ui.AbstractCustomPrologUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CustomPrologUiModule extends AbstractCustomPrologUiModule {
  public CustomPrologUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
