Jamus Scheme: java_cup.terminal Class Reference
java_cup.terminal Class Reference
Public Member Functions
terminal (String nm, String tp, int precedence_side, int precedence_num)
terminal (String nm, String tp)
terminal (String nm)
boolean is_non_term ()
String toString ()
int precedence_num ()
int precedence_side ()
void set_precedence (int p, int new_prec)
Static Public Member Functions
static Enumeration all ()
static terminal find (String with_name)
static terminal find (int indx)
static int number ()
Static Public Attributes
static final terminal EOF = new terminal("EOF")
static final terminal error = new terminal("error")
Static Protected Attributes
static Hashtable _all = new Hashtable()
static Hashtable _all_by_index = new Hashtable()
static int next_index = 0
Private Attributes
int _precedence_num
int _precedence_side
Detailed Description
This class represents a terminal symbol in the grammar. Each terminal has a textual name, an index, and a string which indicates the type of object it will be implemented with at runtime (i.e. the class of object that will be returned by the scanner and pushed on the parse stack to represent it).
Version:
last updated: 7/3/96
Author:
Frank Flannery
Definition at line 16 of file terminal.java.
Constructor & Destructor Documentation
java_cup.terminal.terminal (String nm, String tp, int precedence_side, int precedence_num)
Full constructor.
Parameters:
nm the name of the terminal.
tp the type of the terminal.
Definition at line 26 of file terminal.java.
References java_cup.terminal._all, java_cup.terminal._all_by_index, java_cup.symbol._index, java_cup.terminal._precedence_num, java_cup.terminal._precedence_side, java_cup.terminal.next_index, java_cup.terminal.precedence_num(), and java_cup.terminal.precedence_side().
java_cup.terminal.terminal (String nm, String tp)
Constructor for non-precedented terminal
Definition at line 56 of file terminal.java.
References java_cup.assoc.no_prec.
java_cup.terminal.terminal (String nm)
Constructor with default type.
Parameters:
nm the name of the terminal.
Definition at line 66 of file terminal.java.
Member Function Documentation
static Enumeration java_cup.terminal.all () [static]
Access to all terminals.
Definition at line 88 of file terminal.java.
References java_cup.terminal._all.
Referenced by java_cup.Main.check_unused(), and java_cup.emit.symbols().
static terminal java_cup.terminal.find (String with_name) [static]
Lookup a terminal by name string.
Definition at line 91 of file terminal.java.
References java_cup.terminal._all.
Referenced by java_cup.lalr_state.build_table_entries(), java_cup.Main.dump_grammar(), java_cup.lalr_state.fix_with_precedence(), java_cup.lalr_state.report_reduce_reduce(), java_cup.lalr_state.report_shift_reduce(), java_cup.terminal_set.toString(), and java_cup.lalr_item.toString().
static terminal java_cup.terminal.find (int indx) [static]
Lookup a terminal by index.
Definition at line 106 of file terminal.java.
References java_cup.terminal._all_by_index.
boolean java_cup.terminal.is_non_term () [virtual]
Report this symbol as not being a non-terminal.
Implements java_cup.symbol.
Definition at line 138 of file terminal.java.
static int java_cup.terminal.number () [static]
Total number of terminals.
Definition at line 116 of file terminal.java.
References java_cup.terminal._all.
Referenced by java_cup.lalr_state.build_table_entries(), java_cup.Main.dump_grammar(), java_cup.Main.emit_summary(), java_cup.parse_action_row.parse_action_row(), java_cup.lalr_state.report_conflicts(), java_cup.lalr_state.report_reduce_reduce(), java_cup.terminal_set.terminal_set(), java_cup.terminal_set.toString(), and java_cup.lalr_item.toString().
int java_cup.terminal.precedence_num ()
get the precedence of a terminal
Definition at line 154 of file terminal.java.
References java_cup.terminal._precedence_num.
Referenced by java_cup.lalr_state.fix_with_precedence(), and java_cup.terminal.terminal().
int java_cup.terminal.precedence_side ()
Definition at line 157 of file terminal.java.
References java_cup.terminal._precedence_side.
Referenced by java_cup.lalr_state.fix_with_precedence(), and java_cup.terminal.terminal().
void java_cup.terminal.set_precedence (int p, int new_prec)
set the precedence of a terminal
Definition at line 162 of file terminal.java.
References java_cup.terminal._precedence_num, and java_cup.terminal._precedence_side.
String java_cup.terminal.toString ()
Convert to a string.
Reimplemented from java_cup.symbol.
Definition at line 146 of file terminal.java.
References java_cup.symbol.index().
Member Data Documentation
Hashtable java_cup.terminal._all = new Hashtable() [static, protected]
Table of all terminals. Elements are stored using name strings as the key
Definition at line 85 of file terminal.java.
Referenced by java_cup.terminal.all(), java_cup.terminal.find(), java_cup.terminal.number(), and java_cup.terminal.terminal().
Hashtable java_cup.terminal._all_by_index = new Hashtable() [static, protected]
Table of all terminals indexed by their index number.
Definition at line 103 of file terminal.java.
Referenced by java_cup.terminal.find(), and java_cup.terminal.terminal().
int java_cup.terminal._precedence_num [private]
Definition at line 75 of file terminal.java.
Referenced by java_cup.terminal.precedence_num(), java_cup.terminal.set_precedence(), and java_cup.terminal.terminal().
int java_cup.terminal._precedence_side [private]
Definition at line 76 of file terminal.java.
Referenced by java_cup.terminal.precedence_side(), java_cup.terminal.set_precedence(), and java_cup.terminal.terminal().
final terminal java_cup.terminal.EOF = new terminal("EOF") [static]
Special terminal for end of input.
Definition at line 126 of file terminal.java.
Referenced by java_cup.$actions.$do_action(), java_cup.lalr_state.build_machine(), java_cup.Main.check_unused(), and java_cup.emit.parser().
final terminal java_cup.terminal.error = new terminal("error") [static]
special terminal used for error recovery
Definition at line 131 of file terminal.java.
Referenced by java_cup.$actions.$do_action(), java_cup.Main.check_unused(), and java_cup.emit.parser().
int java_cup.terminal.next_index = 0 [static, protected]
Static counter to assign unique index.
Definition at line 121 of file terminal.java.
Referenced by java_cup.terminal.terminal().
The documentation for this class was generated from the following file:
src/java_cup/terminal.java