/**
 * generated by Xtext 2.11.0
 */
package de.htwdd.sf.beleg.validation;

import de.htwdd.sf.beleg.validation.AbstractCustomPrologValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CustomPrologValidator extends AbstractCustomPrologValidator {
}
