Jamus Scheme: java_cup.emit Class Reference
java_cup.emit Class Reference
Static Public Member Functions
static boolean lr_values ()
static void symbols (PrintWriter out, boolean emit_non_terms, boolean sym_interface)
static void parser (PrintWriter out, parse_action_table action_table, parse_reduce_table reduce_table, int start_st, production start_prod, boolean compact_reduces, boolean suppress_scanner) throws internal_error
Static Public Attributes
static String prefix = "CUP$"
static String package_name = null
static String symbol_const_class_name = "sym"
static String parser_class_name = "parser"
static String action_code = null
static String parser_code = null
static String init_code = null
static String scan_code = null
static production start_production = null
static Stack import_list = new Stack()
static int num_conflicts = 0
static boolean nowarn = false
static int not_reduced = 0
static int unused_term = 0
static int unused_non_term = 0
static long symbols_time = 0
static long parser_time = 0
static long action_code_time = 0
static long production_table_time = 0
static long action_table_time = 0
static long goto_table_time = 0
Static Protected Member Functions
static void set_lr_values (boolean b)
static String pre (String str)
static void emit_package (PrintWriter out)
static void emit_action_code (PrintWriter out, production start_prod) throws internal_error
static void emit_production_table (PrintWriter out)
static void do_action_table (PrintWriter out, parse_action_table act_tab, boolean compact_reduces) throws internal_error
static void do_reduce_table (PrintWriter out, parse_reduce_table red_tab)
static void do_table_as_string (PrintWriter out, short[][] sa)
static int do_newline (PrintWriter out, int nchar, int nbytes)
static int do_escaped (PrintWriter out, char c)
Static Protected Attributes
static boolean _lr_values
Private Member Functions
emit ()
Detailed Description
This class handles emitting generated code for the resulting parser. The various parse tables must be constructed, etc. before calling any routines in this class.
Three classes are produced by this code:
symbol constant class
this contains constant declarations for each terminal (and optionally each non-terminal).
action class
this non-public class contains code to invoke all the user actions that were embedded in the parser specification.
parser class
the specialized parser class consisting primarily of some user supplied general and initialization code, and the parse tables.
Three parse tables are created as part of the parser class:
production table
lists the LHS non terminal number, and the length of the RHS of each production.
action table
for each state of the parse machine, gives the action to be taken (shift, reduce, or error) under each lookahead symbol.
reduce-goto table
when a reduce on a given production is taken, the parse stack is popped back a number of elements corresponding to the RHS of the production. This reveals a prior state, which we transition out of under the LHS non terminal symbol for the production (as if we had seen the LHS symbol rather than all the symbols matching the RHS). This table is indexed by non terminal numbers and indicates how to make these transitions.
In addition to the method interface, this class maintains a series of public global variables and flags indicating how misc. parts of the code and other output is to be produced, and counting things such as number of conflicts detected (see the source code and public variables below for more details).
This class is "static" (contains only static data and methods).
See also:
java_cup.main
Version:
last update: 11/25/95
Author:
Scott Hudson
Definition at line 98 of file emit.java.
Constructor & Destructor Documentation
java_cup.emit.emit () [private]
Only constructor is private so no instances can be created.
Definition at line 105 of file emit.java.
Member Function Documentation
static void java_cup.emit.do_action_table (PrintWriter out, parse_action_table act_tab, boolean compact_reduces) throws internal_error [static, protected]
Emit the action table.
Parameters:
out stream to produce output on.
act_tab the internal representation of the action table.
compact_reduces do we use the most frequent reduce as default?
Definition at line 534 of file emit.java.
References java_cup.emit.action_table_time, java_cup.parse_action_row.compute_default(), java_cup.parse_action_row.default_reduce, java_cup.emit.do_table_as_string(), java_cup.parse_action.ERROR, java_cup.parse_action.kind(), java_cup.parse_action.NONASSOC, java_cup.parse_action.REDUCE, java_cup.parse_action.SHIFT, java_cup.parse_action_row.size(), and java_cup.parse_action_row.under_term.
Referenced by java_cup.emit.parser().
static int java_cup.emit.do_escaped (PrintWriter out, char c) [static, protected]
Definition at line 727 of file emit.java.
Referenced by java_cup.emit.do_table_as_string().
static int java_cup.emit.do_newline (PrintWriter out, int nchar, int nbytes) [static, protected]
Definition at line 720 of file emit.java.
Referenced by java_cup.emit.do_table_as_string().
static void java_cup.emit.do_reduce_table (PrintWriter out, parse_reduce_table red_tab) [static, protected]
Emit the reduce-goto table.
Parameters:
out stream to produce output on.
red_tab the internal representation of the reduce-goto table.
Definition at line 639 of file emit.java.
References java_cup.emit.do_table_as_string(), java_cup.emit.goto_table_time, java_cup.lalr_state.index(), java_cup.parse_reduce_table.num_states(), java_cup.parse_reduce_row.size(), java_cup.parse_reduce_row.under_non_term, and java_cup.parse_reduce_table.under_state.
Referenced by java_cup.emit.parser().
static void java_cup.emit.do_table_as_string (PrintWriter out, short sa[][]) [static, protected]
Definition at line 697 of file emit.java.
References java_cup.emit.do_escaped(), and java_cup.emit.do_newline().
Referenced by java_cup.emit.do_action_table(), java_cup.emit.do_reduce_table(), and java_cup.emit.emit_production_table().
static void java_cup.emit.emit_action_code (PrintWriter out, production start_prod) throws internal_error [static, protected]
Emit code for the non-public class holding the actual action code.
Parameters:
out stream to produce output on.
start_prod the start production of the grammar.
Definition at line 312 of file emit.java.
References java_cup.production.action(), java_cup.emit.action_code, java_cup.emit.action_code_time, java_cup.production.all(), java_cup.action_part.code_string(), java_cup.action_part.equals(), java_cup.symbol.index(), java_cup.production.index(), java_cup.production.lhs(), java_cup.emit.lr_values(), java_cup.symbol.name(), java_cup.emit.parser_class_name, java_cup.emit.pre(), java_cup.production.rhs(), java_cup.production.rhs_length(), java_cup.symbol.stack_type(), java_cup.symbol_part.the_symbol(), and java_cup.production.to_simple_string().
Referenced by java_cup.emit.parser().
static void java_cup.emit.emit_package (PrintWriter out) [static, protected]
Emit a package spec if the user wants one.
Parameters:
out stream to produce output on.
Definition at line 229 of file emit.java.
References java_cup.emit.package_name.
Referenced by java_cup.emit.parser(), and java_cup.emit.symbols().
static void java_cup.emit.emit_production_table (PrintWriter out) [static, protected]
Emit the production table.
Parameters:
out stream to produce output on.
Definition at line 486 of file emit.java.
References java_cup.production.all(), java_cup.emit.do_table_as_string(), java_cup.symbol.index(), java_cup.production.index(), java_cup.production.lhs(), java_cup.production.number(), java_cup.emit.production_table_time, java_cup.production.rhs_length(), and java_cup.symbol_part.the_symbol().
Referenced by java_cup.emit.parser().
static boolean java_cup.emit.lr_values () [static]
whether or not to emit code for left and right values
Definition at line 210 of file emit.java.
References java_cup.emit._lr_values.
Referenced by java_cup.emit.emit_action_code(), and java_cup.production.make_declaration().
static void java_cup.emit.parser (PrintWriter out, parse_action_table action_table, parse_reduce_table reduce_table, int start_st, production start_prod, boolean compact_reduces, boolean suppress_scanner) throws internal_error [static]
Emit the parser subclass with embedded tables.
Parameters:
out stream to produce output on.
action_table internal representation of the action table.
reduce_table internal representation of the reduce-goto table.
start_st start state of the parse machine.
start_prod start production of the grammar.
compact_reduces do we use most frequent reduce as default?
suppress_scanner should scanner be suppressed for compatibility?
Definition at line 758 of file emit.java.
References java_cup.emit.do_action_table(), java_cup.emit.do_reduce_table(), java_cup.emit.emit_action_code(), java_cup.emit.emit_package(), java_cup.emit.emit_production_table(), java_cup.terminal.EOF, java_cup.terminal.error, java_cup.emit.import_list, java_cup.symbol.index(), java_cup.production.index(), java_cup.emit.init_code, java_cup.emit.parser_class_name, java_cup.emit.parser_code, java_cup.emit.parser_time, java_cup.emit.pre(), java_cup.emit.scan_code, java_cup.emit.start_production, and java_cup.version.title_str.
Referenced by java_cup.Main.emit_parser().
static String java_cup.emit.pre (String str) [static, protected]
Build a string with the standard prefix.
Parameters:
str string to prefix.
Definition at line 220 of file emit.java.
References java_cup.emit.parser_class_name, and java_cup.emit.prefix.
Referenced by java_cup.emit.emit_action_code(), java_cup.production.make_declaration(), and java_cup.emit.parser().
static void java_cup.emit.set_lr_values (boolean b) [static, protected]
Definition at line 211 of file emit.java.
References java_cup.emit._lr_values.
Referenced by java_cup.Main.main().
static void java_cup.emit.symbols (PrintWriter out, boolean emit_non_terms, boolean sym_interface) [static]
Emit code for the symbol constant class, optionally including non terms, if they have been requested.
Parameters:
out stream to produce output on.
emit_non_terms do we emit constants for non terminals?
sym_interface should we emit an interface, rather than a class?
Definition at line 245 of file emit.java.
References java_cup.non_terminal.all(), java_cup.terminal.all(), java_cup.emit.emit_package(), java_cup.symbol.index(), java_cup.symbol.name(), java_cup.emit.symbol_const_class_name, java_cup.emit.symbols_time, and java_cup.version.title_str.
Referenced by java_cup.Main.emit_parser().
Member Data Documentation
boolean java_cup.emit._lr_values [static, protected]
Definition at line 207 of file emit.java.
Referenced by java_cup.emit.lr_values(), and java_cup.emit.set_lr_values().
String java_cup.emit.action_code = null [static]
User declarations for direct inclusion in user action class.
Definition at line 132 of file emit.java.
Referenced by java_cup.$actions.$do_action(), and java_cup.emit.emit_action_code().
long java_cup.emit.action_code_time = 0 [static]
Time to produce action code class.
Definition at line 195 of file emit.java.
Referenced by java_cup.emit.emit_action_code(), and java_cup.Main.show_times().
long java_cup.emit.action_table_time = 0 [static]
Time to produce the action table.
Definition at line 201 of file emit.java.
Referenced by java_cup.emit.do_action_table(), and java_cup.Main.show_times().
long java_cup.emit.goto_table_time = 0 [static]
Time to produce the reduce-goto table.
Definition at line 204 of file emit.java.
Referenced by java_cup.emit.do_reduce_table(), and java_cup.Main.show_times().
Stack java_cup.emit.import_list = new Stack() [static]
List of imports (Strings containing class names) to go with actions.
Definition at line 157 of file emit.java.
Referenced by java_cup.$actions.$do_action(), and java_cup.emit.parser().
String java_cup.emit.init_code = null [static]
User code for user_init() which is called during parser initialization.
Definition at line 142 of file emit.java.
Referenced by java_cup.$actions.$do_action(), and java_cup.emit.parser().
int java_cup.emit.not_reduced = 0 [static]
Count of the number on non-reduced productions found.
Definition at line 172 of file emit.java.
Referenced by java_cup.Main.emit_summary().
boolean java_cup.emit.nowarn = false [static]
Do we skip warnings?
Definition at line 167 of file emit.java.
Referenced by java_cup.parse_action_table.check_reductions(), java_cup.Main.check_unused(), and java_cup.Main.parse_args().
int java_cup.emit.num_conflicts = 0 [static]
Number of conflict found while building tables.
Definition at line 162 of file emit.java.
Referenced by java_cup.Main.build_parser(), java_cup.Main.emit_summary(), java_cup.lalr_state.report_reduce_reduce(), and java_cup.lalr_state.report_shift_reduce().
String java_cup.emit.package_name = null [static]
Package that the resulting code goes into (null is used for unnamed).
Definition at line 117 of file emit.java.
Referenced by java_cup.$actions.$do_action(), java_cup.emit.emit_package(), and java_cup.Main.parse_args().
String java_cup.emit.parser_class_name = "parser" [static]
Name of the generated parser class.
Definition at line 127 of file emit.java.
Referenced by java_cup.emit.emit_action_code(), java_cup.Main.emit_summary(), java_cup.Main.open_files(), java_cup.Main.parse_args(), java_cup.emit.parser(), and java_cup.emit.pre().
String java_cup.emit.parser_code = null [static]
User declarations for direct inclusion in parser class.
Definition at line 137 of file emit.java.
Referenced by java_cup.$actions.$do_action(), and java_cup.emit.parser().
long java_cup.emit.parser_time = 0 [static]
Time to produce parser class.
Definition at line 192 of file emit.java.
Referenced by java_cup.emit.parser(), and java_cup.Main.show_times().
String java_cup.emit.prefix = "CUP$" [static]
The prefix placed on names that pollute someone else's name space.
Definition at line 112 of file emit.java.
Referenced by java_cup.emit.pre().
long java_cup.emit.production_table_time = 0 [static]
Time to produce the production table.
Definition at line 198 of file emit.java.
Referenced by java_cup.emit.emit_production_table(), and java_cup.Main.show_times().
String java_cup.emit.scan_code = null [static]
User code for scan() which is called to get the next Symbol.
Definition at line 147 of file emit.java.
Referenced by java_cup.$actions.$do_action(), and java_cup.emit.parser().
production java_cup.emit.start_production = null [static]
The start production of the grammar.
Definition at line 152 of file emit.java.
Referenced by java_cup.$actions.$do_action(), java_cup.Main.build_parser(), java_cup.Main.emit_parser(), and java_cup.emit.parser().
String java_cup.emit.symbol_const_class_name = "sym" [static]
Name of the generated class for symbol constants.
Definition at line 122 of file emit.java.
Referenced by java_cup.Main.emit_summary(), java_cup.Main.open_files(), java_cup.Main.parse_args(), and java_cup.emit.symbols().
long java_cup.emit.symbols_time = 0 [static]
Time to produce symbol constant class.
Definition at line 189 of file emit.java.
Referenced by java_cup.Main.show_times(), and java_cup.emit.symbols().
int java_cup.emit.unused_non_term = 0 [static]
Count of unused non terminals.
Definition at line 182 of file emit.java.
Referenced by java_cup.Main.emit_summary().
int java_cup.emit.unused_term = 0 [static]
Count of unused terminals.
Definition at line 177 of file emit.java.
Referenced by java_cup.Main.check_unused(), and java_cup.Main.emit_summary().
The documentation for this class was generated from the following file:
src/java_cup/emit.java