Jamus Scheme: java_cup.parse_action_row Class Reference
java_cup.parse_action_row Class Reference
Public Member Functions
parse_action_row ()
void compute_default ()
Static Public Member Functions
static int size ()
Public Attributes
parse_action under_term []
int default_reduce
Static Protected Attributes
static int _size = 0
static int reduction_count [] = null
Detailed Description
This class represents one row (corresponding to one machine state) of the parse action table.
Definition at line 7 of file parse_action_row.java.
Constructor & Destructor Documentation
java_cup.parse_action_row.parse_action_row ()
Simple constructor. Note: this should not be used until the number of terminals in the grammar has been established.
Definition at line 16 of file parse_action_row.java.
References java_cup.parse_action_row._size, java_cup.terminal.number(), java_cup.parse_action_row.size(), and java_cup.parse_action_row.under_term.
Member Function Documentation
void java_cup.parse_action_row.compute_default ()
Compute the default (reduce) action for this row and store it in default_reduce. In the case of non-zero default we will have the effect of replacing all errors by that reduction. This may cause us to do erroneous reduces, but will never cause us to shift past the point of the error and never cause an incorrect parse. -1 will be used to encode the fact that no reduction can be used as a default (in which case error will be used).
Definition at line 70 of file parse_action_row.java.
References java_cup.parse_action_row.default_reduce, java_cup.production.number(), java_cup.parse_action.REDUCE, java_cup.parse_action_row.reduction_count, java_cup.parse_action_row.size(), and java_cup.parse_action_row.under_term.
Referenced by java_cup.emit.do_action_table().
static int java_cup.parse_action_row.size () [static]
Number of columns (terminals) in every row.
Definition at line 37 of file parse_action_row.java.
References java_cup.parse_action_row._size.
Referenced by java_cup.parse_action_table.check_reductions(), java_cup.parse_action_row.compute_default(), java_cup.emit.do_action_table(), and java_cup.parse_action_row.parse_action_row().
Member Data Documentation
int java_cup.parse_action_row._size = 0 [static, protected]
Number of columns (terminals) in every row.
Definition at line 34 of file parse_action_row.java.
Referenced by java_cup.parse_action_row.parse_action_row(), and java_cup.parse_action_row.size().
int java_cup.parse_action_row.default_reduce
Default (reduce) action for this row. -1 will represent default of error.
Definition at line 56 of file parse_action_row.java.
Referenced by java_cup.parse_action_row.compute_default(), and java_cup.emit.do_action_table().
int java_cup.parse_action_row.reduction_count[] = null [static, protected]
Table of reduction counts (reused by compute_default()).
Definition at line 42 of file parse_action_row.java.
Referenced by java_cup.parse_action_row.compute_default().
parse_action java_cup.parse_action_row.under_term[]
Actual action entries for the row.
Definition at line 49 of file parse_action_row.java.
Referenced by java_cup.lalr_state.build_table_entries(), java_cup.parse_action_table.check_reductions(), java_cup.parse_action_row.compute_default(), java_cup.emit.do_action_table(), java_cup.parse_action_row.parse_action_row(), and java_cup.parse_action_table.toString().
The documentation for this class was generated from the following file:
src/java_cup/parse_action_row.java