Jamus Scheme: Scheme.List Class Reference
Scheme.List Class Reference
Public Member Functions
List ()
boolean nullp ()
List cons (Object e)
List reverse ()
List append (List l)
Object car ()
List cdr ()
int length ()
int lengthex ()
List member (Object el)
Object nth (Integer n)
void princ ()
Private Attributes
Object car
List cdr
Detailed Description
Definition at line 5 of file List.java.
Constructor & Destructor Documentation
Scheme.List.List ()
Definition at line 9 of file List.java.
References Scheme.List.car(), and Scheme.List.cdr().
Referenced by Scheme.List.cons(), and Scheme.List.reverse().
Member Function Documentation
List Scheme.List.append (List l)
Definition at line 36 of file List.java.
References Scheme.List.car(), Scheme.List.cdr(), Scheme.List.cons(), and Scheme.List.nullp().
Referenced by Scheme.List.reverse().
Object Scheme.List.car ()
Definition at line 43 of file List.java.
References Scheme.List.cdr().
Referenced by Scheme.List.append(), Scheme.List.List(), Scheme.List.princ(), and Scheme.List.reverse().
List Scheme.List.cdr ()
Definition at line 52 of file List.java.
Referenced by Scheme.List.append(), Scheme.List.car(), Scheme.List.length(), Scheme.List.lengthex(), Scheme.List.List(), Scheme.List.member(), Scheme.List.nullp(), Scheme.List.princ(), and Scheme.List.reverse().
List Scheme.List.cons (Object e)
Definition at line 21 of file List.java.
References Scheme.List.car, Scheme.List.cdr, and Scheme.List.List().
Referenced by Scheme.List.append(), Scheme.Stack.push(), and Scheme.List.reverse().
int Scheme.List.length ()
Definition at line 62 of file List.java.
References Scheme.List.cdr(), and Scheme.List.nullp().
int Scheme.List.lengthex ()
Definition at line 69 of file List.java.
References Scheme.List.cdr().
List Scheme.List.member (Object el)
Definition at line 77 of file List.java.
References Scheme.List.cdr(), and Scheme.List.nullp().
Object Scheme.List.nth (Integer n)
Definition at line 86 of file List.java.
boolean Scheme.List.nullp ()
Definition at line 14 of file List.java.
References Scheme.List.cdr().
Referenced by Scheme.List.append(), Scheme.List.length(), Scheme.List.member(), Scheme.List.princ(), and Scheme.List.reverse().
void Scheme.List.princ ()
Definition at line 90 of file List.java.
References Scheme.List.car(), Scheme.List.cdr(), Scheme.List.nullp(), and Scheme.List.princ().
Referenced by Scheme.List.princ().
List Scheme.List.reverse ()
Definition at line 28 of file List.java.
References Scheme.List.append(), Scheme.List.car(), Scheme.List.cdr(), Scheme.List.cons(), Scheme.List.List(), and Scheme.List.nullp().
Member Data Documentation
Object Scheme.List.car [private]
Definition at line 6 of file List.java.
Referenced by Scheme.List.cons(), and Scheme.Stack.top().
List Scheme.List.cdr [private]
Definition at line 7 of file List.java.
Referenced by Scheme.List.cons(), and Scheme.Stack.pop().
The documentation for this class was generated from the following file:
src/Scheme/List.java