Jamus Scheme: java_cup.lalr_state Class Reference
java_cup.lalr_state Class Reference
Public Member Functions
lalr_state (lalr_item_set itms) throws internal_error
lalr_item_set items ()
lalr_transition transitions ()
int index ()
void add_transition (symbol on_sym, lalr_state to_st) throws internal_error
void build_table_entries (parse_action_table act_table, parse_reduce_table reduce_table) throws internal_error
boolean equals (lalr_state other)
boolean equals (Object other)
int hashCode ()
String toString ()
Static Public Member Functions
static Enumeration all ()
static int number ()
static lalr_state find_state (lalr_item_set itms)
static lalr_state build_machine (production start_prod) throws internal_error
Protected Member Functions
void propagate_lookaheads () throws internal_error
boolean fix_with_precedence (production p, int term_index, parse_action_row table_row, parse_action act) throws internal_error
parse_action insert_action (parse_action a1, parse_action a2, int act_type) throws internal_error
parse_action insert_shift (parse_action a1, parse_action a2) throws internal_error
parse_action insert_reduce (parse_action a1, parse_action a2) throws internal_error
void report_conflicts (terminal_set conflict_set) throws internal_error
void report_reduce_reduce (lalr_item itm1, lalr_item itm2) throws internal_error
void report_shift_reduce (lalr_item red_itm, int conflict_sym) throws internal_error
Static Protected Member Functions
static void dump_state (lalr_state st) throws internal_error
static void propagate_all_lookaheads () throws internal_error
Protected Attributes
lalr_item_set _items
lalr_transition _transitions = null
int _index
Static Protected Attributes
static Hashtable _all = new Hashtable()
static Hashtable _all_kernels = new Hashtable()
static int next_index = 0
Detailed Description
This class represents a state in the LALR viable prefix recognition machine. A state consists of an LALR item set and a set of transitions to other states under terminal and non-terminal symbols. Each state represents a potential configuration of the parser. If the item set of a state includes an item such as:
    [A ::= B * C d E , {a,b,c}]
this indicates that when the parser is in this state it is currently looking for an A of the given form, has already seen the B, and would expect to see an a, b, or c after this sequence is complete. Note that the parser is normally looking for several things at once (represented by several items). In our example above, the state would also include items such as:
    [C ::= * X e Z, {d}]
    [X ::= * f, {e}]
to indicate that it was currently looking for a C followed by a d (which would be reduced into a C, matching the first symbol in our production above), and the terminal f followed by e.
At runtime, the parser uses a viable prefix recognition machine made up of these states to parse. The parser has two operations, shift and reduce. In a shift, it consumes one Symbol and makes a transition to a new state. This corresponds to "moving the dot past" a terminal in one or more items in the state (these new shifted items will then be found in the state at the end of the transition). For a reduce operation, the parser is signifying that it is recognizing the RHS of some production. To do this it first "backs up" by popping a stack of previously saved states. It pops off the same number of states as are found in the RHS of the production. This leaves the machine in the same state is was in when the parser first attempted to find the RHS. From this state it makes a transition based on the non-terminal on the LHS of the production. This corresponds to placing the parse in a configuration equivalent to having replaced all the symbols from the the input corresponding to the RHS with the symbol on the LHS.
See also:
java_cup.lalr_item
java_cup.lalr_item_set
java_cup.lalr_transition
Version:
last updated: 7/3/96
Author:
Frank Flannery
Definition at line 52 of file lalr_state.java.
Constructor & Destructor Documentation
java_cup.lalr_state.lalr_state (lalr_item_set itms) throws internal_error
Constructor for building a state from a set of items.
Parameters:
itms the set of items that makes up this state.
Definition at line 60 of file lalr_state.java.
References java_cup.lalr_state._all, java_cup.lalr_state._index, java_cup.lalr_state._items, java_cup.lalr_state.find_state(), and java_cup.lalr_state.next_index.
Referenced by java_cup.lalr_state.build_machine(), and java_cup.lalr_state.propagate_all_lookaheads().
Member Function Documentation
void java_cup.lalr_state.add_transition (symbol on_sym, lalr_state to_st) throws internal_error
Add a transition out of this state to another.
Parameters:
on_sym the symbol the transition is under.
to_st the state the transition goes to.
Definition at line 221 of file lalr_state.java.
References java_cup.lalr_state._transitions.
Referenced by java_cup.lalr_state.build_machine().
static Enumeration java_cup.lalr_state.all () [static]
Collection of all states.
Definition at line 89 of file lalr_state.java.
References java_cup.lalr_state._all.
Referenced by java_cup.Main.build_parser(), java_cup.lalr_state.build_table_entries(), java_cup.Main.dump_machine(), java_cup.lalr_state.propagate_all_lookaheads(), java_cup.lalr_state.propagate_lookaheads(), and java_cup.lalr_state.report_conflicts().
static lalr_state java_cup.lalr_state.build_machine (production start_prod) throws internal_error [static]
Build an LALR viable prefix recognition machine given a start production. This method operates by first building a start state from the start production (based on a single item with the dot at the beginning and EOF as expected lookahead). Then for each state it attempts to extend the machine by creating transitions out of the state to new or existing states. When considering extension from a state we make a transition on each symbol that appears before the dot in some item. For example, if we have the items:
    [A ::= a b * X c, {d,e}]
    [B ::= a b * X d, {a,b}]
in some state, then we would be making a transition under X to a new state. This new state would be formed by a "kernel" of items corresponding to moving the dot past the X. In this case:
    [A ::= a b X * c, {d,e}]
    [B ::= a b X * Y, {a,b}]
The full state would then be formed by "closing" this kernel set of items so that it included items that represented productions of things the parser was now looking for. In this case we would items corresponding to productions of Y, since various forms of Y are expected next when in this state (see lalr_item_set.compute_closure() for details on closure).
The process of building the viable prefix recognizer terminates when no new states can be added. However, in order to build a smaller number of states (i.e., corresponding to LALR rather than canonical LR) the state building process does not maintain full loookaheads in all items. Consequently, after the machine is built, we go back and propagate lookaheads through the constructed machine using a call to propagate_all_lookaheads(). This makes use of propagation links constructed during the closure and transition process.
Parameters:
start_prod the start production of the grammar
See also:
java_cup.lalr_item_set::compute_closure
java_cup.lalr_state::propagate_all_lookaheads
Definition at line 271 of file lalr_state.java.
References java_cup.lalr_state._all_kernels, java_cup.symbol_set.add(), java_cup.lalr_item_set.add(), java_cup.terminal_set.add(), java_cup.lalr_state.add_transition(), java_cup.symbol_set.all(), java_cup.lalr_item_set.all(), java_cup.lalr_item_set.compute_closure(), java_cup.terminal.EOF, java_cup.lalr_item_set.find(), java_cup.lalr_state.items(), java_cup.lalr_state.lalr_state(), java_cup.lalr_item.lookahead(), java_cup.lalr_state.propagate_all_lookaheads(), java_cup.lalr_item.propagate_items(), java_cup.lalr_item.shift(), and java_cup.lr_item_core.symbol_after_dot().
Referenced by java_cup.Main.build_parser().
void java_cup.lalr_state.build_table_entries (parse_action_table act_table, parse_reduce_table reduce_table) throws internal_error
Fill in the parse table entries for this state. There are two parse tables that encode the viable prefix recognition machine, an action table and a reduce-goto table. The rows in each table correspond to states of the machine. The columns of the action table are indexed by terminal symbols and correspond to either transitions out of the state (shift entries) or reductions from the state to some previous state saved on the stack (reduce entries). All entries in the action table that are not shifts or reduces, represent errors. The reduce-goto table is indexed by non terminals and represents transitions out of a state on that non-terminal.
Conflicts occur if more than one action needs to go in one entry of the action table (this cannot happen with the reduce-goto table). Conflicts are resolved by always shifting for shift/reduce conflicts and choosing the lowest numbered production (hence the one that appeared first in the specification) in reduce/reduce conflicts. All conflicts are reported and if more conflicts are detected than were declared by the user, code generation is aborted.
Parameters:
act_table the action table to put entries in.
reduce_table the reduce-goto table to put entries in.
Definition at line 451 of file lalr_state.java.
References java_cup.terminal_set.add(), java_cup.lalr_state.all(), java_cup.terminal_set.contains(), java_cup.lr_item_core.dot_at_end(), java_cup.terminal_set.empty(), java_cup.parse_action.ERROR, java_cup.terminal.find(), java_cup.lalr_state.fix_with_precedence(), java_cup.symbol.index(), java_cup.lalr_state.index(), java_cup.production.index(), java_cup.symbol.is_non_term(), java_cup.lalr_state.items(), java_cup.parse_action.kind(), java_cup.lalr_item.lookahead(), java_cup.lalr_transition.next(), java_cup.parse_action.NONASSOC, java_cup.terminal.number(), java_cup.lalr_state.report_conflicts(), java_cup.parse_action.SHIFT, java_cup.lr_item_core.the_production(), java_cup.lalr_state.transitions(), java_cup.parse_reduce_row.under_non_term, and java_cup.parse_action_row.under_term.
Referenced by java_cup.Main.build_parser().
static void java_cup.lalr_state.dump_state (lalr_state st) throws internal_error [static, protected]
Helper routine for debugging -- produces a dump of the given state onto System.out.
Definition at line 159 of file lalr_state.java.
References java_cup.lalr_item_set.all(), java_cup.lr_item_core.dot_at_end(), java_cup.lr_item_core.dot_pos(), java_cup.production_part.is_action(), java_cup.production.lhs(), java_cup.symbol.name(), java_cup.production.rhs(), java_cup.production.rhs_length(), java_cup.lr_item_core.the_production(), and java_cup.symbol_part.the_symbol().
boolean java_cup.lalr_state.equals (lalr_state other)
Equality comparison.
Definition at line 836 of file lalr_state.java.
References java_cup.lalr_item_set.equals(), and java_cup.lalr_state.items().
Referenced by java_cup.lalr_state.equals().
boolean java_cup.lalr_state.equals (Object other)
Generic equality comparison.
Definition at line 845 of file lalr_state.java.
References java_cup.lalr_state.equals().
static lalr_state java_cup.lalr_state.find_state (lalr_item_set itms) [static]
Find and return state with a given a kernel item set (or null if not found). The kernel item set is the subset of items that were used to originally create the state. These items are formed by "shifting the dot" within items of other states that have a transition to this one. The remaining elements of this state's item set are added during closure.
Parameters:
itms the kernel set of the state we are looking for.
Definition at line 113 of file lalr_state.java.
References java_cup.lalr_state._all.
Referenced by java_cup.lalr_state.lalr_state().
boolean java_cup.lalr_state.fix_with_precedence (production p, int term_index, parse_action_row table_row, parse_action act) throws internal_error [protected]
Procedure that attempts to fix a shift/reduce error by using precedences. --frankf 6/26/96
if a production (also called rule) or the lookahead terminal has a precedence, then the table can be fixed. if the rule has greater precedence than the terminal, a reduce by that rule in inserted in the table. If the terminal has a higher precedence, it is shifted. if they have equal precedence, then the associativity of the precedence is used to determine what to put in the table: if the precedence is left associative, the action is to reduce. if the precedence is right associative, the action is to shift. if the precedence is non associative, then it is a syntax error.
Parameters:
p the production
term_index the index of the lokahead terminal
parse_action_row a row of the action table
act the rule in conflict with the table entry
Definition at line 584 of file lalr_state.java.
References java_cup.terminal.find(), java_cup.lalr_state.insert_reduce(), java_cup.lalr_state.insert_shift(), java_cup.assoc.left, java_cup.assoc.no_prec, java_cup.assoc.nonassoc, java_cup.terminal.precedence_num(), java_cup.terminal.precedence_side(), and java_cup.assoc.right.
Referenced by java_cup.lalr_state.build_table_entries().
int java_cup.lalr_state.hashCode ()
Produce a hash code.
Definition at line 856 of file lalr_state.java.
References java_cup.lalr_item_set.hashCode(), and java_cup.lalr_state.items().
Referenced by java_cup.shift_action.hashCode().
int java_cup.lalr_state.index ()
Index of this state in the parse tables
Definition at line 150 of file lalr_state.java.
References java_cup.lalr_state._index.
Referenced by java_cup.lalr_state.build_table_entries(), java_cup.emit.do_reduce_table(), java_cup.Main.dump_machine(), java_cup.Main.emit_parser(), java_cup.lalr_state.report_reduce_reduce(), java_cup.lalr_state.report_shift_reduce(), java_cup.parse_reduce_table.toString(), java_cup.shift_action.toString(), java_cup.lalr_transition.toString(), and java_cup.lalr_state.toString().
parse_action java_cup.lalr_state.insert_action (parse_action a1, parse_action a2, int act_type) throws internal_error [protected]
Definition at line 660 of file lalr_state.java.
Referenced by java_cup.lalr_state.insert_reduce(), and java_cup.lalr_state.insert_shift().
parse_action java_cup.lalr_state.insert_reduce (parse_action a1, parse_action a2) throws internal_error [protected]
Definition at line 687 of file lalr_state.java.
References java_cup.lalr_state.insert_action(), and java_cup.parse_action.REDUCE.
Referenced by java_cup.lalr_state.fix_with_precedence().
parse_action java_cup.lalr_state.insert_shift (parse_action a1, parse_action a2) throws internal_error [protected]
Definition at line 678 of file lalr_state.java.
References java_cup.lalr_state.insert_action(), and java_cup.parse_action.SHIFT.
Referenced by java_cup.lalr_state.fix_with_precedence().
lalr_item_set java_cup.lalr_state.items ()
The item set for this state.
Definition at line 134 of file lalr_state.java.
References java_cup.lalr_state._items.
Referenced by java_cup.lalr_state.build_machine(), java_cup.lalr_state.build_table_entries(), java_cup.lalr_state.equals(), java_cup.lalr_state.hashCode(), java_cup.lalr_state.propagate_lookaheads(), java_cup.lalr_state.report_conflicts(), and java_cup.lalr_state.report_shift_reduce().
static int java_cup.lalr_state.number () [static]
Indicate total number of states there are.
Definition at line 94 of file lalr_state.java.
References java_cup.lalr_state._all.
Referenced by java_cup.Main.dump_machine(), java_cup.Main.emit_summary(), java_cup.parse_action_table.parse_action_table(), and java_cup.parse_reduce_table.parse_reduce_table().
static void java_cup.lalr_state.propagate_all_lookaheads () throws internal_error [static, protected]
Propagate lookahead sets through the constructed viable prefix recognizer. When the machine is constructed, each item that results in the creation of another such that its lookahead is included in the other's will have a propagate link set up for it. This allows additions to the lookahead of one item to be included in other items that it was used to directly or indirectly create.
Definition at line 203 of file lalr_state.java.
References java_cup.lalr_state.all(), java_cup.lalr_state.lalr_state(), and java_cup.lalr_state.propagate_lookaheads().
Referenced by java_cup.lalr_state.build_machine().
void java_cup.lalr_state.propagate_lookaheads () throws internal_error [protected]
Propagate lookahead sets out of this state. This recursively propagates to all items that have propagation links from some item in this state.
Definition at line 421 of file lalr_state.java.
References java_cup.lalr_state.all(), and java_cup.lalr_state.items().
Referenced by java_cup.lalr_state.propagate_all_lookaheads().
void java_cup.lalr_state.report_conflicts (terminal_set conflict_set) throws internal_error [protected]
Produce warning messages for all conflicts found in this state.
Definition at line 698 of file lalr_state.java.
References java_cup.lalr_item_set.all(), java_cup.lalr_state.all(), java_cup.lr_item_core.dot_at_end(), java_cup.terminal_set.intersects(), java_cup.lalr_state.items(), java_cup.lalr_item.lookahead(), java_cup.terminal.number(), java_cup.lalr_state.report_reduce_reduce(), and java_cup.lalr_state.report_shift_reduce().
Referenced by java_cup.lalr_state.build_table_entries().
void java_cup.lalr_state.report_reduce_reduce (lalr_item itm1, lalr_item itm2) throws internal_error [protected]
Produce a warning message for one reduce/reduce conflict.
Parameters:
itm1 first item in conflict.
itm2 second item in conflict.
Definition at line 757 of file lalr_state.java.
References java_cup.terminal.find(), java_cup.lalr_state.index(), java_cup.symbol.name(), java_cup.emit.num_conflicts, java_cup.terminal.number(), and java_cup.lexer.warning_count.
Referenced by java_cup.lalr_state.report_conflicts().
void java_cup.lalr_state.report_shift_reduce (lalr_item red_itm, int conflict_sym) throws internal_error [protected]
Produce a warning message for one shift/reduce conflict.
Parameters:
red_itm the item with the reduce.
conflict_sym the index of the symbol conflict occurs under.
Definition at line 795 of file lalr_state.java.
References java_cup.lalr_item_set.all(), java_cup.lr_item_core.dot_at_end(), java_cup.terminal.find(), java_cup.symbol.index(), java_cup.lalr_state.index(), java_cup.symbol.is_non_term(), java_cup.lalr_state.items(), java_cup.symbol.name(), java_cup.emit.num_conflicts, java_cup.lr_item_core.symbol_after_dot(), java_cup.lr_item_core.to_simple_string(), and java_cup.lexer.warning_count.
Referenced by java_cup.lalr_state.report_conflicts().
String java_cup.lalr_state.toString ()
Convert to a string.
Definition at line 865 of file lalr_state.java.
References java_cup.lalr_state._items, java_cup.lalr_state.index(), java_cup.lalr_transition.next(), and java_cup.lalr_state.transitions().
lalr_transition java_cup.lalr_state.transitions ()
List of transitions out of this state.
Definition at line 142 of file lalr_state.java.
References java_cup.lalr_state._transitions.
Referenced by java_cup.lalr_state.build_table_entries(), and java_cup.lalr_state.toString().
Member Data Documentation
Hashtable java_cup.lalr_state._all = new Hashtable() [static, protected]
Collection of all states.
Definition at line 86 of file lalr_state.java.
Referenced by java_cup.lalr_state.all(), java_cup.lalr_state.find_state(), java_cup.lalr_state.lalr_state(), and java_cup.lalr_state.number().
Hashtable java_cup.lalr_state._all_kernels = new Hashtable() [static, protected]
Hash table to find states by their kernels (i.e, the original, unclosed, set of items -- which uniquely define the state). This table stores state objects using (a copy of) their kernel item sets as keys.
Definition at line 102 of file lalr_state.java.
Referenced by java_cup.lalr_state.build_machine().
int java_cup.lalr_state._index [protected]
Index of this state in the parse tables
Definition at line 147 of file lalr_state.java.
Referenced by java_cup.lalr_state.index(), and java_cup.lalr_state.lalr_state().
lalr_item_set java_cup.lalr_state._items [protected]
The item set for this state.
Definition at line 131 of file lalr_state.java.
Referenced by java_cup.lalr_state.items(), java_cup.lalr_state.lalr_state(), and java_cup.lalr_state.toString().
lalr_transition java_cup.lalr_state._transitions = null [protected]
List of transitions out of this state.
Definition at line 139 of file lalr_state.java.
Referenced by java_cup.lalr_state.add_transition(), and java_cup.lalr_state.transitions().
int java_cup.lalr_state.next_index = 0 [static, protected]
Static counter for assigning unique state indexes.
Definition at line 124 of file lalr_state.java.
Referenced by java_cup.lalr_state.lalr_state().
The documentation for this class was generated from the following file:
src/java_cup/lalr_state.java