Jamus Scheme: java_cup.lalr_item Class Reference
java_cup.lalr_item Class Reference
Public Member Functions
lalr_item (production prod, int pos, terminal_set look) throws internal_error
lalr_item (production prod, terminal_set look) throws internal_error
lalr_item (production prod) throws internal_error
terminal_set lookahead ()
Stack propagate_items ()
void add_propagate (lalr_item prop_to)
void propagate_lookaheads (terminal_set incoming) throws internal_error
lalr_item shift () throws internal_error
terminal_set calc_lookahead (terminal_set lookahead_after) throws internal_error
boolean lookahead_visible () throws internal_error
boolean equals (lalr_item other)
boolean equals (Object other)
int hashCode ()
String toString ()
Protected Attributes
terminal_set _lookahead
Stack _propagate_items
boolean needs_propagation
Detailed Description
This class represents an LALR item. Each LALR item consists of a production, a "dot" at a position within that production, and a set of lookahead symbols (terminal). (The first two of these parts are provide by the super class). An item is designed to represent a configuration that the parser may be in. For example, an item of the form:
    [A ::= B * C d E  , {a,b,c}]
indicates that the parser is in the middle of parsing the production
    A ::= B C d E
that B has already been parsed, and that we will expect to see a lookahead of either a, b, or c once the complete RHS of this production has been found.
Items may initially be missing some items from their lookahead sets. Links are maintained from each item to the set of items that would need to be updated if symbols are added to its lookahead set. During "lookahead propagation", we add symbols to various lookahead sets and propagate these changes across these dependency links as needed.
See also:
java_cup.lalr_item_set
java_cup.lalr_state
Version:
last updated: 11/25/95
Author:
Scott Hudson
Definition at line 32 of file lalr_item.java.
Constructor & Destructor Documentation
java_cup.lalr_item.lalr_item (production prod, int pos, terminal_set look) throws internal_error
Full constructor.
Parameters:
prod the production for the item.
pos the position of the "dot" within the production.
look the set of lookahead symbols.
Definition at line 43 of file lalr_item.java.
References java_cup.lalr_item._lookahead, java_cup.lalr_item._propagate_items, and java_cup.lalr_item.needs_propagation.
Referenced by java_cup.lalr_item.shift().
java_cup.lalr_item.lalr_item (production prod, terminal_set look) throws internal_error
Constructor with default position (dot at start).
Parameters:
prod the production for the item.
look the set of lookahead symbols.
Definition at line 58 of file lalr_item.java.
java_cup.lalr_item.lalr_item (production prod) throws internal_error
Constructor with default position and empty lookahead set.
Parameters:
prod the production for the item.
Definition at line 68 of file lalr_item.java.
Member Function Documentation
void java_cup.lalr_item.add_propagate (lalr_item prop_to)
Add a new item to the set of items we propagate to.
Definition at line 101 of file lalr_item.java.
References java_cup.lalr_item._propagate_items, and java_cup.lalr_item.needs_propagation.
Referenced by java_cup.lalr_item_set.compute_closure(), and java_cup.lalr_item.shift().
terminal_set java_cup.lalr_item.calc_lookahead (terminal_set lookahead_after) throws internal_error
Calculate lookahead representing symbols that could appear after the symbol that the dot is currently in front of. Note: this routine must not be invoked before first sets and nullability has been calculated for all non terminals.
Definition at line 173 of file lalr_item.java.
References java_cup.terminal_set.add(), java_cup.lr_item_core.dot_at_end(), java_cup.lr_item_core.dot_pos(), java_cup.production_part.is_action(), java_cup.symbol.is_non_term(), java_cup.production.rhs(), java_cup.production.rhs_length(), and java_cup.lr_item_core.the_production().
Referenced by java_cup.lalr_item_set.compute_closure().
boolean java_cup.lalr_item.equals (lalr_item other)
Equality comparison -- here we only require the cores to be equal since we need to do sets of items based only on core equality (ignoring lookahead sets).
Definition at line 269 of file lalr_item.java.
Referenced by java_cup.lalr_item.equals().
boolean java_cup.lalr_item.equals (Object other)
Generic equality comparison.
Reimplemented from java_cup.lr_item_core.
Definition at line 278 of file lalr_item.java.
References java_cup.lalr_item.equals().
int java_cup.lalr_item.hashCode ()
Return a hash code -- here we only hash the core since we only test core matching in LALR items.
Reimplemented from java_cup.lr_item_core.
Definition at line 291 of file lalr_item.java.
terminal_set java_cup.lalr_item.lookahead ()
The lookahead symbols of the item.
Definition at line 81 of file lalr_item.java.
References java_cup.lalr_item._lookahead.
Referenced by java_cup.lalr_item_set.add(), java_cup.lalr_state.build_machine(), java_cup.lalr_state.build_table_entries(), java_cup.lalr_item_set.compute_closure(), java_cup.lalr_item.propagate_lookaheads(), java_cup.lalr_state.report_conflicts(), java_cup.lalr_item.shift(), and java_cup.lalr_item.toString().
boolean java_cup.lalr_item.lookahead_visible () throws internal_error
Determine if everything from the symbol one beyond the dot all the way to the end of the right hand side is nullable. This would indicate that the lookahead of this item must be included in the lookaheads of all items produced as a closure of this item. Note: this routine should not be invoked until after first sets and nullability have been calculated for all non terminals.
Definition at line 232 of file lalr_item.java.
References java_cup.lr_item_core.dot_at_end(), java_cup.lr_item_core.dot_pos(), java_cup.production_part.is_action(), java_cup.symbol.is_non_term(), java_cup.production.rhs(), java_cup.production.rhs_length(), and java_cup.lr_item_core.the_production().
Referenced by java_cup.lalr_item_set.compute_closure().
Stack java_cup.lalr_item.propagate_items ()
Links to items that the lookahead needs to be propagated to
Definition at line 89 of file lalr_item.java.
References java_cup.lalr_item._propagate_items.
Referenced by java_cup.lalr_state.build_machine(), and java_cup.lalr_item.propagate_lookaheads().
void java_cup.lalr_item.propagate_lookaheads (terminal_set incoming) throws internal_error
Propagate incoming lookaheads through this item to others need to be changed. incoming symbols to potentially be added to lookahead of this item.
Definition at line 115 of file lalr_item.java.
References java_cup.terminal_set.add(), java_cup.lalr_item.lookahead(), java_cup.lalr_item.needs_propagation, and java_cup.lalr_item.propagate_items().
lalr_item java_cup.lalr_item.shift () throws internal_error
Produce the new lalr_item that results from shifting the dot one position to the right.
Definition at line 148 of file lalr_item.java.
References java_cup.lalr_item.add_propagate(), java_cup.lr_item_core.dot_at_end(), java_cup.lr_item_core.dot_pos(), java_cup.lalr_item.lalr_item(), java_cup.lalr_item.lookahead(), and java_cup.lr_item_core.the_production().
Referenced by java_cup.lalr_state.build_machine().
String java_cup.lalr_item.toString ()
Convert to string.
Reimplemented from java_cup.lr_item_core.
Definition at line 299 of file lalr_item.java.
References java_cup.terminal_set.contains(), java_cup.terminal.find(), java_cup.lalr_item.lookahead(), java_cup.symbol.name(), and java_cup.terminal.number().
Member Data Documentation
terminal_set java_cup.lalr_item._lookahead [protected]
The lookahead symbols of the item.
Definition at line 78 of file lalr_item.java.
Referenced by java_cup.lalr_item.lalr_item(), and java_cup.lalr_item.lookahead().
Stack java_cup.lalr_item._propagate_items [protected]
Links to items that the lookahead needs to be propagated to.
Definition at line 86 of file lalr_item.java.
Referenced by java_cup.lalr_item.add_propagate(), java_cup.lalr_item.lalr_item(), and java_cup.lalr_item.propagate_items().
boolean java_cup.lalr_item.needs_propagation [protected]
Flag to indicate that this item needs to propagate its lookahead (whether it has changed or not).
Definition at line 96 of file lalr_item.java.
Referenced by java_cup.lalr_item.add_propagate(), java_cup.lalr_item.lalr_item(), and java_cup.lalr_item.propagate_lookaheads().
The documentation for this class was generated from the following file:
src/java_cup/lalr_item.java