Jamus Scheme: java_cup.nonassoc_action Class Reference
java_cup.nonassoc_action Class Reference
Public Member Functions
nonassoc_action () throws internal_error
int kind ()
boolean equals (parse_action other)
boolean equals (Object other)
int hashCode ()
String toString ()
Detailed Description
This class represents a shift/reduce nonassociative error within the parse table. If action_table element is assign to type nonassoc_action, it cannot be changed, and signifies that there is a conflict between shifting and reducing a production and a terminal that shouldn't be next to each other.
Version:
last updated: 7/2/96
Author:
Frank Flannery
Definition at line 13 of file nonassoc_action.java.
Constructor & Destructor Documentation
java_cup.nonassoc_action.nonassoc_action () throws internal_error
Simple constructor.
Definition at line 21 of file nonassoc_action.java.
Member Function Documentation
boolean java_cup.nonassoc_action.equals (parse_action other)
Equality test.
Reimplemented from java_cup.parse_action.
Definition at line 36 of file nonassoc_action.java.
References java_cup.parse_action.kind(), and java_cup.parse_action.NONASSOC.
Referenced by java_cup.nonassoc_action.equals().
boolean java_cup.nonassoc_action.equals (Object other)
Generic equality test.
Reimplemented from java_cup.parse_action.
Definition at line 44 of file nonassoc_action.java.
References java_cup.nonassoc_action.equals().
int java_cup.nonassoc_action.hashCode ()
Compute a hash code.
Reimplemented from java_cup.parse_action.
Definition at line 55 of file nonassoc_action.java.
int java_cup.nonassoc_action.kind ()
Quick access to type of action.
Reimplemented from java_cup.parse_action.
Definition at line 31 of file nonassoc_action.java.
References java_cup.parse_action.NONASSOC.
String java_cup.nonassoc_action.toString ()
Convert to string.
Reimplemented from java_cup.parse_action.
Definition at line 64 of file nonassoc_action.java.
The documentation for this class was generated from the following file:
src/java_cup/nonassoc_action.java