Jamus Scheme: java_cup.production Class Reference
java_cup.production Class Reference
Public Member Functions
production (non_terminal lhs_sym, production_part rhs_parts[], int rhs_l, String action_str) throws internal_error
production (non_terminal lhs_sym, production_part rhs_parts[], int rhs_l) throws internal_error
production (non_terminal lhs_sym, production_part rhs_parts[], int rhs_l, String action_str, int prec_num, int prec_side) throws internal_error
production (non_terminal lhs_sym, production_part rhs_parts[], int rhs_l, int prec_num, int prec_side) throws internal_error
symbol_part lhs ()
int precedence_num ()
int precedence_side ()
void set_precedence_num (int prec_num)
void set_precedence_side (int prec_side)
production_part rhs (int indx) throws internal_error
int rhs_length ()
action_part action ()
int index ()
int num_reductions ()
void note_reduction_use ()
boolean nullable_known ()
boolean nullable ()
terminal_set first_set ()
boolean check_nullable () throws internal_error
terminal_set check_first_set () throws internal_error
boolean equals (production other)
boolean equals (Object other)
int hashCode ()
String toString ()
String to_simple_string () throws internal_error
Static Public Member Functions
static Enumeration all ()
static production find (int indx)
static int number ()
Protected Member Functions
String make_declaration (String labelname, String stack_type, int offset)
String declare_labels (production_part rhs[], int rhs_len, String final_action)
int merge_adjacent_actions (production_part rhs_parts[], int len)
action_part strip_trailing_action (production_part rhs_parts[], int len)
void remove_embedded_actions () throws internal_error
Static Protected Member Functions
static boolean is_id_start (char c)
static boolean is_id_char (char c)
Protected Attributes
symbol_part _lhs
int _rhs_prec = -1
int _rhs_assoc = -1
production_part _rhs []
int _rhs_length
action_part _action
int _index
int _num_reductions = 0
boolean _nullable_known = false
boolean _nullable = false
terminal_set _first_set = new terminal_set()
Static Protected Attributes
static Hashtable _all = new Hashtable()
static int next_index
Package Functions
boolean set_nullable (boolean v)
Detailed Description
This class represents a production in the grammar. It contains a LHS non terminal, and an array of RHS symbols. As various transformations are done on the RHS of the production, it may shrink. As a result a separate length is always maintained to indicate how much of the RHS array is still valid.
I addition to construction and manipulation operations, productions provide methods for factoring out actions (see remove_embedded_actions()), for computing the nullability of the production (i.e., can it derive the empty string, see check_nullable()), and operations for computing its first set (i.e., the set of terminals that could appear at the beginning of some string derived from the production, see check_first_set()).
See also:
java_cup.production_part
java_cup.symbol_part
java_cup.action_part
Version:
last updated: 7/3/96
Author:
Frank Flannery
Definition at line 27 of file production.java.
Constructor & Destructor Documentation
java_cup.production.production (non_terminal lhs_sym, production_part rhs_parts[], int rhs_l, String action_str) throws internal_error
Full constructor. This constructor accepts a LHS non terminal, an array of RHS parts (including terminals, non terminals, and actions), and a string for a final reduce action. It does several manipulations in the process of creating a production object. After some validity checking it translates labels that appear in actions into code for accessing objects on the runtime parse stack. It them merges adjacent actions if they appear and moves any trailing action into the final reduce actions string. Next it removes any embedded actions by factoring them out with new action productions. Finally it assigns a unique index to the production.
Factoring out of actions is accomplished by creating new "hidden" non terminals. For example if the production was originally:
    A ::= B {action} C D
then it is factored into two productions:
    A ::= B X C D
    X ::= {action}
(where X is a unique new non terminal). This has the effect of placing all actions at the end where they can be handled as part of a reduce by the parser.
Definition at line 56 of file production.java.
References java_cup.production._action, java_cup.production._all, java_cup.production._index, java_cup.production._lhs, java_cup.production._rhs, java_cup.production._rhs_assoc, java_cup.production._rhs_length, java_cup.production._rhs_prec, java_cup.action_part.code_string(), java_cup.production.declare_labels(), java_cup.production.merge_adjacent_actions(), java_cup.production.next_index, java_cup.production.precedence_num(), java_cup.production.precedence_side(), java_cup.production.remove_embedded_actions(), and java_cup.production.strip_trailing_action().
java_cup.production.production (non_terminal lhs_sym, production_part rhs_parts[], int rhs_l) throws internal_error
Constructor with no action string.
Definition at line 166 of file production.java.
java_cup.production.production (non_terminal lhs_sym, production_part rhs_parts[], int rhs_l, String action_str, int prec_num, int prec_side) throws internal_error
Definition at line 179 of file production.java.
References java_cup.production.set_precedence_num(), and java_cup.production.set_precedence_side().
java_cup.production.production (non_terminal lhs_sym, production_part rhs_parts[], int rhs_l, int prec_num, int prec_side) throws internal_error
Definition at line 199 of file production.java.
References java_cup.production.set_precedence_num(), and java_cup.production.set_precedence_side().
Member Function Documentation
action_part java_cup.production.action ()
An action_part containing code for the action to be performed when we reduce with this production.
Definition at line 301 of file production.java.
References java_cup.production._action.
Referenced by java_cup.emit.emit_action_code(), and java_cup.production.toString().
static Enumeration java_cup.production.all () [static]
Access to all productions.
Definition at line 226 of file production.java.
References java_cup.production._all.
Referenced by java_cup.parse_action_table.check_reductions(), java_cup.non_terminal.compute_nullability(), java_cup.emit.emit_action_code(), and java_cup.emit.emit_production_table().
terminal_set java_cup.production.check_first_set () throws internal_error
Update (and return) the first set based on current NT firsts. This assumes that nullability has already been computed for all non terminals and productions.
Definition at line 638 of file production.java.
References java_cup.production._first_set, java_cup.terminal_set.add(), java_cup.production.first_set(), java_cup.production_part.is_action(), java_cup.symbol.is_non_term(), java_cup.production.nullable(), java_cup.production.rhs(), and java_cup.production.rhs_length().
Referenced by java_cup.non_terminal.compute_first_sets().
boolean java_cup.production.check_nullable () throws internal_error
Check to see if the production (now) appears to be nullable. A production is nullable if its RHS could derive the empty string. This results when the RHS is empty or contains only non terminals which themselves are nullable.
Definition at line 584 of file production.java.
References java_cup.production_part.is_action(), java_cup.symbol.is_non_term(), java_cup.production.nullable(), java_cup.production.nullable_known(), java_cup.production.rhs(), java_cup.production.rhs_length(), and java_cup.production.set_nullable().
Referenced by java_cup.non_terminal.compute_nullability().
String java_cup.production.declare_labels (production_part rhs[], int rhs_len, String final_action) [protected]
Declare label names as valid variables within the action string
Parameters:
rhs array of RHS parts.
rhs_len how much of rhs to consider valid.
final_action the final action string of the production.
lhs_type the object type associated with the LHS symbol.
Definition at line 415 of file production.java.
References java_cup.production_part.label(), java_cup.production.make_declaration(), java_cup.symbol.stack_type(), and java_cup.symbol_part.the_symbol().
Referenced by java_cup.production.production(), and java_cup.production.remove_embedded_actions().
boolean java_cup.production.equals (production other)
Equality comparison.
Definition at line 679 of file production.java.
References java_cup.production._index.
Referenced by java_cup.lr_item_core.core_equals(), and java_cup.production.equals().
boolean java_cup.production.equals (Object other)
Generic equality comparison.
Definition at line 688 of file production.java.
References java_cup.production.equals().
static production java_cup.production.find (int indx) [static]
Lookup a production by index.
Definition at line 229 of file production.java.
References java_cup.production._all.
Referenced by java_cup.Main.dump_grammar().
terminal_set java_cup.production.first_set ()
First set of the production. This is the set of terminals that could appear at the front of some string derived from this production.
Definition at line 348 of file production.java.
References java_cup.production._first_set.
Referenced by java_cup.production.check_first_set().
int java_cup.production.hashCode ()
Produce a hash code.
Definition at line 699 of file production.java.
References java_cup.production._index.
Referenced by java_cup.reduce_action.hashCode(), and java_cup.lr_item_core.lr_item_core().
int java_cup.production.index ()
Index number of the production.
Definition at line 309 of file production.java.
References java_cup.production._index.
Referenced by java_cup.lalr_state.build_table_entries(), java_cup.emit.emit_action_code(), java_cup.emit.emit_production_table(), java_cup.emit.parser(), java_cup.reduce_action.toString(), and java_cup.production.toString().
static boolean java_cup.production.is_id_char (char c) [static, protected]
Determine if a character can be in a label id.
Parameters:
c the character in question.
Definition at line 369 of file production.java.
References java_cup.production.is_id_start().
static boolean java_cup.production.is_id_start (char c) [static, protected]
Determine if a given character can be a label id starter.
Parameters:
c the character in question.
Definition at line 357 of file production.java.
Referenced by java_cup.production.is_id_char().
symbol_part java_cup.production.lhs ()
The left hand side non-terminal.
Definition at line 249 of file production.java.
References java_cup.production._lhs.
Referenced by java_cup.Main.dump_grammar(), java_cup.lalr_state.dump_state(), java_cup.emit.emit_action_code(), java_cup.emit.emit_production_table(), java_cup.lr_item_core.to_simple_string(), java_cup.production.to_simple_string(), and java_cup.production.toString().
String java_cup.production.make_declaration (String labelname, String stack_type, int offset) [protected]
Return label declaration code
Parameters:
labelname the label name
stack_type the stack type of label?
Author:
frankf
Definition at line 384 of file production.java.
References java_cup.emit.lr_values(), and java_cup.emit.pre().
Referenced by java_cup.production.declare_labels().
int java_cup.production.merge_adjacent_actions (production_part rhs_parts[], int len) [protected]
Helper routine to merge adjacent actions in a set of RHS parts
Parameters:
rhs_parts array of RHS parts.
len amount of that array that is valid.
Returns:
remaining valid length.
Definition at line 454 of file production.java.
Referenced by java_cup.production.production().
void java_cup.production.note_reduction_use ()
Increment the count of reductions with this non-terminal
Definition at line 320 of file production.java.
References java_cup.production._num_reductions.
boolean java_cup.production.nullable ()
Nullability of the production (can it derive the empty string).
Definition at line 336 of file production.java.
References java_cup.production._nullable.
Referenced by java_cup.production.check_first_set(), java_cup.production.check_nullable(), and java_cup.production.toString().
boolean java_cup.production.nullable_known ()
Is the nullability of the production known or unknown?
Definition at line 328 of file production.java.
References java_cup.production._nullable_known.
Referenced by java_cup.production.check_nullable(), and java_cup.production.toString().
int java_cup.production.num_reductions ()
Count of number of reductions using this production.
Definition at line 317 of file production.java.
References java_cup.production._num_reductions.
Referenced by java_cup.parse_action_table.check_reductions().
static int java_cup.production.number () [static]
Total number of productions.
Definition at line 236 of file production.java.
References java_cup.production._all.
Referenced by java_cup.parse_action_row.compute_default(), java_cup.Main.dump_grammar(), java_cup.emit.emit_production_table(), and java_cup.Main.emit_summary().
int java_cup.production.precedence_num ()
Access to the precedence of the rule
Definition at line 257 of file production.java.
References java_cup.production._rhs_prec.
Referenced by java_cup.production.production().
int java_cup.production.precedence_side ()
Definition at line 258 of file production.java.
References java_cup.production._rhs_assoc.
Referenced by java_cup.production.production().
void java_cup.production.remove_embedded_actions () throws internal_error [protected]
Remove all embedded actions from a production by factoring them out into individual action production using new non terminals. if the original production was:
    A ::= B {action1} C {action2} D
then it will be factored into:
    A ::= B NT$1 C NT$2 D
    NT$1 ::= {action1}
    NT$2 ::= {action2}
where NT$1 and NT$2 are new system created non terminals.
Definition at line 548 of file production.java.
References java_cup.production._rhs, java_cup.non_terminal.create_new(), java_cup.production.declare_labels(), java_cup.production_part.is_action(), java_cup.non_terminal.is_embedded_action, java_cup.production.rhs(), and java_cup.production.rhs_length().
Referenced by java_cup.production.production().
production_part java_cup.production.rhs (int indx) throws internal_error
Access to the collection of parts for the right hand side.
Definition at line 274 of file production.java.
References java_cup.production._rhs, and java_cup.production._rhs_length.
Referenced by java_cup.lalr_item.calc_lookahead(), java_cup.production.check_first_set(), java_cup.production.check_nullable(), java_cup.Main.dump_grammar(), java_cup.lalr_state.dump_state(), java_cup.emit.emit_action_code(), java_cup.lalr_item.lookahead_visible(), java_cup.lr_item_core.lr_item_core(), java_cup.production.remove_embedded_actions(), java_cup.lr_item_core.to_simple_string(), java_cup.production.to_simple_string(), and java_cup.production.toString().
int java_cup.production.rhs_length ()
How much of the right hand side array we are presently using.
Definition at line 289 of file production.java.
References java_cup.production._rhs_length.
Referenced by java_cup.lalr_item.calc_lookahead(), java_cup.production.check_first_set(), java_cup.production.check_nullable(), java_cup.lr_item_core.dot_at_end(), java_cup.Main.dump_grammar(), java_cup.lalr_state.dump_state(), java_cup.emit.emit_action_code(), java_cup.emit.emit_production_table(), java_cup.lalr_item.lookahead_visible(), java_cup.lr_item_core.lr_item_core(), java_cup.production.remove_embedded_actions(), java_cup.lr_item_core.to_simple_string(), java_cup.production.to_simple_string(), and java_cup.production.toString().
boolean java_cup.production.set_nullable (boolean v) [package]
set (and return) nullability
Definition at line 625 of file production.java.
References java_cup.production._nullable, and java_cup.production._nullable_known.
Referenced by java_cup.production.check_nullable(), and java_cup.non_terminal.compute_nullability().
void java_cup.production.set_precedence_num (int prec_num)
Setting the precedence of a rule
Definition at line 261 of file production.java.
References java_cup.production._rhs_prec.
Referenced by java_cup.production.production().
void java_cup.production.set_precedence_side (int prec_side)
Definition at line 264 of file production.java.
References java_cup.production._rhs_assoc.
Referenced by java_cup.production.production().
action_part java_cup.production.strip_trailing_action (production_part rhs_parts[], int len) [protected]
Helper routine to strip a trailing action off rhs and return it
Parameters:
rhs_parts array of RHS parts.
len how many of those are valid.
Returns:
the removed action part.
Definition at line 508 of file production.java.
Referenced by java_cup.production.production().
String java_cup.production.to_simple_string () throws internal_error
Convert to a simpler string.
Definition at line 741 of file production.java.
References java_cup.production_part.is_action(), java_cup.production.lhs(), java_cup.symbol.name(), java_cup.production.rhs(), java_cup.production.rhs_length(), and java_cup.symbol_part.the_symbol().
Referenced by java_cup.parse_action_table.check_reductions(), and java_cup.emit.emit_action_code().
String java_cup.production.toString ()
Convert to a string.
Definition at line 708 of file production.java.
References java_cup.production.action(), java_cup.action_part.code_string(), java_cup.internal_error.crash(), java_cup.production.index(), java_cup.production.lhs(), java_cup.production.nullable(), java_cup.production.nullable_known(), java_cup.production.rhs(), java_cup.production.rhs_length(), and java_cup.symbol_part.toString().
Member Data Documentation
action_part java_cup.production._action [protected]
An action_part containing code for the action to be performed when we reduce with this production.
Definition at line 296 of file production.java.
Referenced by java_cup.production.action(), and java_cup.production.production().
Hashtable java_cup.production._all = new Hashtable() [static, protected]
Table of all productions. Elements are stored using their index as the key.
Definition at line 223 of file production.java.
Referenced by java_cup.production.all(), java_cup.production.find(), java_cup.production.number(), and java_cup.production.production().
terminal_set java_cup.production._first_set = new terminal_set() [protected]
First set of the production. This is the set of terminals that could appear at the front of some string derived from this production.
Definition at line 343 of file production.java.
Referenced by java_cup.production.check_first_set(), and java_cup.production.first_set().
int java_cup.production._index [protected]
Index number of the production.
Definition at line 306 of file production.java.
Referenced by java_cup.production.equals(), java_cup.production.hashCode(), java_cup.production.index(), and java_cup.production.production().
symbol_part java_cup.production._lhs [protected]
The left hand side non-terminal.
Definition at line 246 of file production.java.
Referenced by java_cup.production.lhs(), and java_cup.production.production().
boolean java_cup.production._nullable = false [protected]
Nullability of the production (can it derive the empty string).
Definition at line 333 of file production.java.
Referenced by java_cup.production.nullable(), and java_cup.production.set_nullable().
boolean java_cup.production._nullable_known = false [protected]
Is the nullability of the production known or unknown?
Definition at line 325 of file production.java.
Referenced by java_cup.production.nullable_known(), and java_cup.production.set_nullable().
int java_cup.production._num_reductions = 0 [protected]
Count of number of reductions using this production.
Definition at line 314 of file production.java.
Referenced by java_cup.production.note_reduction_use(), and java_cup.production.num_reductions().
production_part java_cup.production._rhs[] [protected]
A collection of parts for the right hand side.
Definition at line 271 of file production.java.
Referenced by java_cup.production.production(), java_cup.production.remove_embedded_actions(), and java_cup.production.rhs().
int java_cup.production._rhs_assoc = -1 [protected]
Definition at line 254 of file production.java.
Referenced by java_cup.production.precedence_side(), java_cup.production.production(), and java_cup.production.set_precedence_side().
int java_cup.production._rhs_length [protected]
How much of the right hand side array we are presently using.
Definition at line 286 of file production.java.
Referenced by java_cup.production.production(), java_cup.production.rhs(), and java_cup.production.rhs_length().
int java_cup.production._rhs_prec = -1 [protected]
The precedence of the rule
Definition at line 253 of file production.java.
Referenced by java_cup.production.precedence_num(), java_cup.production.production(), and java_cup.production.set_precedence_num().
int java_cup.production.next_index [static, protected]
Static counter for assigning unique index numbers.
Definition at line 239 of file production.java.
Referenced by java_cup.production.production().
The documentation for this class was generated from the following file:
src/java_cup/production.java