Jamus Scheme: java_cup.action_part Class Reference
java_cup.action_part Class Reference
Public Member Functions
action_part (String code_str)
String code_string ()
void set_code_string (String new_str)
boolean is_action ()
boolean equals (action_part other)
boolean equals (Object other)
int hashCode ()
String toString ()
Protected Attributes
String _code_string
Detailed Description
This class represents a part of a production which contains an action. These are eventually eliminated from productions and converted to trailing actions by factoring out with a production that derives the empty string (and ends with this action).
See also:
java_cup.production
Version:
last update: 11/25/95
Author:
Scott Hudson
Definition at line 15 of file action_part.java.
Constructor & Destructor Documentation
java_cup.action_part.action_part (String code_str)
Simple constructor.
Parameters:
code_str string containing the actual user code.
Definition at line 24 of file action_part.java.
References java_cup.action_part._code_string.
Member Function Documentation
String java_cup.action_part.code_string ()
String containing code for the action in question.
Definition at line 40 of file action_part.java.
References java_cup.action_part._code_string.
Referenced by java_cup.emit.emit_action_code(), java_cup.action_part.equals(), java_cup.action_part.hashCode(), java_cup.production.production(), java_cup.action_part.toString(), and java_cup.production.toString().
boolean java_cup.action_part.equals (action_part other)
Equality comparison for properly typed object.
Definition at line 57 of file action_part.java.
References java_cup.action_part.code_string(), and java_cup.action_part.equals().
Referenced by java_cup.emit.emit_action_code(), and java_cup.action_part.equals().
boolean java_cup.action_part.equals (Object other)
Generic equality comparison.
Reimplemented from java_cup.production_part.
Definition at line 67 of file action_part.java.
References java_cup.action_part.equals().
int java_cup.action_part.hashCode ()
Produce a hash code.
Reimplemented from java_cup.production_part.
Definition at line 78 of file action_part.java.
References java_cup.action_part.code_string().
boolean java_cup.action_part.is_action () [virtual]
Override to report this object as an action.
Implements java_cup.production_part.
Definition at line 52 of file action_part.java.
void java_cup.action_part.set_code_string (String new_str)
Set the code string.
Definition at line 45 of file action_part.java.
References java_cup.action_part._code_string.
String java_cup.action_part.toString ()
Convert to a string.
Reimplemented from java_cup.production_part.
Definition at line 87 of file action_part.java.
References java_cup.action_part.code_string().
Member Data Documentation
String java_cup.action_part._code_string [protected]
String containing code for the action in question.
Definition at line 35 of file action_part.java.
Referenced by java_cup.action_part.action_part(), java_cup.action_part.code_string(), and java_cup.action_part.set_code_string().
The documentation for this class was generated from the following file:
src/java_cup/action_part.java