Jamus Scheme: java_cup.runtime.lr_parser Class Reference
java_cup.runtime.lr_parser Class Reference
Public Member Functions
lr_parser ()
lr_parser (Scanner s)
abstract short[][] production_table ()
abstract short[][] action_table ()
abstract short[][] reduce_table ()
abstract int start_state ()
abstract int start_production ()
abstract int EOF_sym ()
abstract int error_sym ()
void done_parsing ()
void setScanner (Scanner s)
Scanner getScanner ()
abstract Symbol do_action (int act_num, lr_parser parser, Stack stack, int top) throws java.lang.Exception
void user_init () throws java.lang.Exception
Symbol scan () throws java.lang.Exception
void report_fatal_error (String message, Object info) throws java.lang.Exception
void report_error (String message, Object info)
void syntax_error (Symbol cur_token)
void unrecovered_syntax_error (Symbol cur_token) throws java.lang.Exception
Symbol parse () throws java.lang.Exception
void debug_message (String mess)
void dump_stack ()
void debug_reduce (int prod_num, int nt_num, int rhs_size)
void debug_shift (Symbol shift_tkn)
void debug_stack ()
Symbol debug_parse () throws java.lang.Exception
Protected Member Functions
int error_sync_size ()
abstract void init_actions () throws java.lang.Exception
final short get_action (int state, int sym)
final short get_reduce (int state, int sym)
boolean error_recovery (boolean debug) throws java.lang.Exception
boolean shift_under_error ()
boolean find_recovery_config (boolean debug)
void read_lookahead () throws java.lang.Exception
Symbol cur_err_token ()
boolean advance_lookahead ()
void restart_lookahead () throws java.lang.Exception
boolean try_parse_ahead (boolean debug) throws java.lang.Exception
void parse_lookahead (boolean debug) throws java.lang.Exception
Static Protected Member Functions
static short[][] unpackFromStrings (String[] sa)
Protected Attributes
boolean _done_parsing = false
int tos
Symbol cur_token
Stack stack = new Stack()
short[][] production_tab
short[][] action_tab
short[][] reduce_tab
Symbol lookahead []
int lookahead_pos
Static Protected Attributes
static final int _error_sync_size = 3
Private Attributes
Scanner _scanner
Detailed Description
This class implements a skeleton table driven LR parser. In general, LR parsers are a form of bottom up shift-reduce parsers. Shift-reduce parsers act by shifting input onto a parse stack until the Symbols matching the right hand side of a production appear on the top of the stack. Once this occurs, a reduce is performed. This involves removing the Symbols corresponding to the right hand side of the production (the so called "handle") and replacing them with the non-terminal from the left hand side of the production.
To control the decision of whether to shift or reduce at any given point, the parser uses a state machine (the "viable prefix recognition machine" built by the parser generator). The current state of the machine is placed on top of the parse stack (stored as part of a Symbol object representing a terminal or non terminal). The parse action table is consulted (using the current state and the current lookahead Symbol as indexes) to determine whether to shift or to reduce. When the parser shifts, it changes to a new state by pushing a new Symbol (containing a new state) onto the stack. When the parser reduces, it pops the handle (right hand side of a production) off the stack. This leaves the parser in the state it was in before any of those Symbols were matched. Next the reduce-goto table is consulted (using the new state and current lookahead Symbol as indexes) to determine a new state to go to. The parser then shifts to this goto state by pushing the left hand side Symbol of the production (also containing the new state) onto the stack.
This class actually provides four LR parsers. The methods parse() and debug_parse() provide two versions of the main parser (the only difference being that debug_parse() emits debugging trace messages as it parses). In addition to these main parsers, the error recovery mechanism uses two more. One of these is used to simulate "parsing ahead" in the input without carrying out actions (to verify that a potential error recovery has worked), and the other is used to parse through buffered "parse ahead" input in order to execute all actions and re-synchronize the actual parser configuration.
This is an abstract class which is normally filled out by a subclass generated by the JavaCup parser generator. In addition to supplying the actual parse tables, generated code also supplies methods which invoke various pieces of user supplied code, provide access to certain special Symbols (e.g., EOF and error), etc. Specifically, the following abstract methods are normally supplied by generated code:
short[][] production_table()
Provides a reference to the production table (indicating the index of the left hand side non terminal and the length of the right hand side for each production in the grammar).
short[][] action_table()
Provides a reference to the parse action table.
short[][] reduce_table()
Provides a reference to the reduce-goto table.
int start_state()
Indicates the index of the start state.
int start_production()
Indicates the index of the starting production.
int EOF_sym()
Indicates the index of the EOF Symbol.
int error_sym()
Indicates the index of the error Symbol.
Symbol do_action()
Executes a piece of user supplied action code. This always comes at the point of a reduce in the parse, so this code also allocates and fills in the left hand side non terminal Symbol object that is to be pushed onto the stack for the reduce.
void init_actions()
Code to initialize a special object that encapsulates user supplied actions (this object is used by do_action() to actually carry out the actions).
In addition to these routines that must be supplied by the generated subclass there are also a series of routines that may be supplied. These include:
Symbol scan()
Used to get the next input Symbol from the scanner.
Scanner getScanner()
Used to provide a scanner for the default implementation of scan().
int error_sync_size()
This determines how many Symbols past the point of an error must be parsed without error in order to consider a recovery to be valid. This defaults to 3. Values less than 2 are not recommended.
void report_error(String message, Object info)
This method is called to report an error. The default implementation simply prints a message to System.err and where the error occurred. This method is often replaced in order to provide a more sophisticated error reporting mechanism.
void report_fatal_error(String message, Object info)
This method is called when a fatal error that cannot be recovered from is encountered. In the default implementation, it calls report_error() to emit a message, then throws an exception.
void syntax_error(Symbol cur_token)
This method is called as soon as syntax error is detected (but before recovery is attempted). In the default implementation it invokes: report_error("Syntax error", null);
void unrecovered_syntax_error(Symbol cur_token)
This method is called if syntax error recovery fails. In the default implementation it invokes:
report_fatal_error("Couldn't repair and continue parse", null);
See also:
java_cup.runtime.Symbol
java_cup.runtime.Symbol
java_cup.runtime.virtual_parse_stack
Version:
last updated: 7/3/96
Author:
Frank Flannery
Definition at line 115 of file lr_parser.java.
Constructor & Destructor Documentation
java_cup.runtime.lr_parser.lr_parser ()
Simple constructor.
Definition at line 122 of file lr_parser.java.
java_cup.runtime.lr_parser.lr_parser (Scanner s)
Constructor that sets the default scanner. [CSA/davidm]
Definition at line 128 of file lr_parser.java.
References java_cup.runtime.lr_parser.setScanner().
Member Function Documentation
abstract short [][] java_cup.runtime.lr_parser.action_table () [pure virtual]
The action table (supplied by generated subclass). This table is indexed by state and terminal number indicating what action is to be taken when the parser is in the given state (i.e., the given state is on top of the stack) and the given terminal is next on the input. States are indexed using the first dimension, however, the entries for a given state are compacted and stored in adjacent index, value pairs which are searched for rather than accessed directly (see get_action()). The actions stored in the table will be either shifts, reduces, or errors. Shifts are encoded as positive values (one greater than the state shifted to). Reduces are encoded as negative values (one less than the production reduced by). Error entries are denoted by zero.
See also:
java_cup.runtime.lr_parser::get_action
Implemented in java_cup.parser, Scheme.parser, and java_cup.simple_calc.parser.
Referenced by java_cup.runtime.lr_parser.debug_parse(), and java_cup.runtime.lr_parser.parse().
boolean java_cup.runtime.lr_parser.advance_lookahead () [protected]
Advance to next "parse ahead" input Symbol. Return true if we have input to advance to, false otherwise.
Definition at line 1004 of file lr_parser.java.
References java_cup.runtime.lr_parser.error_sync_size(), and java_cup.runtime.lr_parser.lookahead_pos.
Referenced by java_cup.runtime.lr_parser.parse_lookahead(), and java_cup.runtime.lr_parser.try_parse_ahead().
Symbol java_cup.runtime.lr_parser.cur_err_token () [protected]
Return the current lookahead in our error "parse ahead" buffer.
Definition at line 997 of file lr_parser.java.
References java_cup.runtime.lr_parser.lookahead, and java_cup.runtime.lr_parser.lookahead_pos.
Referenced by java_cup.runtime.lr_parser.error_recovery(), java_cup.runtime.lr_parser.parse_lookahead(), and java_cup.runtime.lr_parser.try_parse_ahead().
void java_cup.runtime.lr_parser.debug_message (String mess)
Write a debugging message to System.err for the debugging version of the parser.
Parameters:
mess the text of the debugging message.
Definition at line 629 of file lr_parser.java.
Referenced by java_cup.runtime.lr_parser.debug_parse(), java_cup.runtime.lr_parser.debug_reduce(), java_cup.runtime.lr_parser.debug_shift(), java_cup.runtime.lr_parser.debug_stack(), java_cup.runtime.lr_parser.dump_stack(), java_cup.runtime.lr_parser.error_recovery(), java_cup.runtime.lr_parser.find_recovery_config(), java_cup.runtime.lr_parser.parse_lookahead(), and java_cup.runtime.lr_parser.try_parse_ahead().
Symbol java_cup.runtime.lr_parser.debug_parse () throws java.lang.Exception
Perform a parse with debugging output. This does exactly the same things as parse(), except that it calls debug_shift() and debug_reduce() when shift and reduce moves are taken by the parser and produces various other debugging messages.
Definition at line 705 of file lr_parser.java.
References java_cup.runtime.lr_parser._done_parsing, java_cup.runtime.lr_parser.action_tab, java_cup.runtime.lr_parser.action_table(), java_cup.runtime.lr_parser.cur_token, java_cup.runtime.lr_parser.debug_message(), java_cup.runtime.lr_parser.debug_reduce(), java_cup.runtime.lr_parser.debug_shift(), java_cup.runtime.lr_parser.do_action(), java_cup.runtime.lr_parser.done_parsing(), java_cup.runtime.lr_parser.error_recovery(), java_cup.runtime.lr_parser.get_action(), java_cup.runtime.lr_parser.get_reduce(), java_cup.runtime.lr_parser.init_actions(), java_cup.runtime.Symbol.parse_state, java_cup.runtime.lr_parser.production_tab, java_cup.runtime.lr_parser.production_table(), java_cup.runtime.lr_parser.reduce_tab, java_cup.runtime.lr_parser.reduce_table(), java_cup.runtime.lr_parser.scan(), java_cup.runtime.lr_parser.stack, java_cup.runtime.lr_parser.start_state(), java_cup.runtime.Symbol.sym, java_cup.runtime.lr_parser.syntax_error(), java_cup.runtime.lr_parser.tos, java_cup.runtime.lr_parser.unrecovered_syntax_error(), java_cup.runtime.Symbol.used_by_parser, and java_cup.runtime.lr_parser.user_init().
Referenced by java_cup.simple_calc.Main.main(), and java_cup.Main.parse_grammar_spec().
void java_cup.runtime.lr_parser.debug_reduce (int prod_num, int nt_num, int rhs_size)
Do debug output for a reduce.
Parameters:
prod_num the production we are reducing with.
nt_num the index of the LHS non terminal.
rhs_size the size of the RHS.
Definition at line 664 of file lr_parser.java.
References java_cup.runtime.lr_parser.debug_message().
Referenced by java_cup.runtime.lr_parser.debug_parse(), and java_cup.runtime.lr_parser.parse_lookahead().
void java_cup.runtime.lr_parser.debug_shift (Symbol shift_tkn)
Do debug output for shift.
Parameters:
shift_tkn the Symbol being shifted onto the stack.
Definition at line 676 of file lr_parser.java.
References java_cup.runtime.lr_parser.debug_message(), java_cup.runtime.Symbol.parse_state, and java_cup.runtime.Symbol.sym.
Referenced by java_cup.runtime.lr_parser.debug_parse(), and java_cup.runtime.lr_parser.parse_lookahead().
void java_cup.runtime.lr_parser.debug_stack ()
Do debug output for stack state. [CSA]
Definition at line 686 of file lr_parser.java.
References java_cup.runtime.lr_parser.debug_message(), java_cup.runtime.Symbol.parse_state, java_cup.runtime.lr_parser.stack, and java_cup.runtime.Symbol.sym.
abstract Symbol java_cup.runtime.lr_parser.do_action (int act_num, lr_parser parser, Stack stack, int top) throws java.lang.Exception [pure virtual]
Perform a bit of user supplied action code (supplied by generated subclass). Actions are indexed by an internal action number assigned at parser generation time.
Parameters:
act_num the internal index of the action to be performed.
parser the parser object we are acting for.
stack the parse stack of that object.
top the index of the top element of the parse stack.
Referenced by java_cup.runtime.lr_parser.debug_parse(), java_cup.runtime.lr_parser.parse(), and java_cup.runtime.lr_parser.parse_lookahead().
void java_cup.runtime.lr_parser.done_parsing ()
This method is called to indicate that the parser should quit. This is normally called by an accept action, but can be used to cancel parsing early in other circumstances if desired.
Definition at line 230 of file lr_parser.java.
References java_cup.runtime.lr_parser._done_parsing.
Referenced by java_cup.simple_calc.$actions.$do_action(), java_cup.runtime.lr_parser.debug_parse(), java_cup.runtime.lr_parser.parse(), java_cup.runtime.lr_parser.report_fatal_error(), and java_cup.parser.report_fatal_error().
void java_cup.runtime.lr_parser.dump_stack ()
Dump the parse stack for debugging purposes.
Definition at line 637 of file lr_parser.java.
References java_cup.runtime.lr_parser.debug_message(), and java_cup.runtime.lr_parser.stack.
abstract int java_cup.runtime.lr_parser.EOF_sym () [pure virtual]
The index of the end of file terminal Symbol (supplied by generated subclass).
Implemented in java_cup.parser, Scheme.parser, and java_cup.simple_calc.parser.
Referenced by java_cup.runtime.lr_parser.error_recovery().
boolean java_cup.runtime.lr_parser.error_recovery (boolean debug) throws java.lang.Exception [protected]
Attempt to recover from a syntax error. This returns false if recovery fails, true if it succeeds. Recovery happens in 4 steps. First we pop the parse stack down to a point at which we have a shift out of the top-most state on the error Symbol. This represents the initial error recovery configuration. If no such configuration is found, then we fail. Next a small number of "lookahead" or "parse ahead" Symbols are read into a buffer. The size of this buffer is determined by error_sync_size() and determines how many Symbols beyond the error must be matched to consider the recovery a success. Next, we begin to discard Symbols in attempt to get past the point of error to a point where we can continue parsing. After each Symbol, we attempt to "parse ahead" though the buffered lookahead Symbols. The "parse ahead" process simulates that actual parse, but does not modify the real parser's configuration, nor execute any actions. If we can parse all the stored Symbols without error, then the recovery is considered a success. Once a successful recovery point is determined, we do an actual parse over the stored input -- modifying the real parse configuration and executing all actions. Finally, we return the the normal parser to continue with the overall parse.
Parameters:
debug should we produce debugging messages as we parse.
Definition at line 848 of file lr_parser.java.
References java_cup.runtime.lr_parser.cur_err_token(), java_cup.runtime.lr_parser.debug_message(), java_cup.runtime.lr_parser.EOF_sym(), java_cup.runtime.lr_parser.find_recovery_config(), java_cup.runtime.lr_parser.lookahead, java_cup.runtime.lr_parser.parse_lookahead(), java_cup.runtime.lr_parser.read_lookahead(), java_cup.runtime.lr_parser.restart_lookahead(), and java_cup.runtime.lr_parser.try_parse_ahead().
Referenced by java_cup.runtime.lr_parser.debug_parse(), and java_cup.runtime.lr_parser.parse().
abstract int java_cup.runtime.lr_parser.error_sym () [pure virtual]
The index of the special error Symbol (supplied by generated subclass).
Implemented in java_cup.parser, Scheme.parser, and java_cup.simple_calc.parser.
Referenced by java_cup.runtime.lr_parser.find_recovery_config(), and java_cup.runtime.lr_parser.shift_under_error().
int java_cup.runtime.lr_parser.error_sync_size () [protected]
The number of Symbols after an error we much match to consider it recovered from.
Definition at line 147 of file lr_parser.java.
References java_cup.runtime.lr_parser._error_sync_size.
Referenced by java_cup.runtime.lr_parser.advance_lookahead(), java_cup.runtime.lr_parser.read_lookahead(), and java_cup.runtime.lr_parser.restart_lookahead().
boolean java_cup.runtime.lr_parser.find_recovery_config (boolean debug) [protected]
Put the (real) parse stack into error recovery configuration by popping the stack down to a state that can shift on the special error Symbol, then doing the shift. If no suitable state exists on the stack we return false
Parameters:
debug should we produce debugging messages as we parse.
Definition at line 917 of file lr_parser.java.
References java_cup.runtime.lr_parser.debug_message(), java_cup.runtime.lr_parser.error_sym(), java_cup.runtime.lr_parser.get_action(), java_cup.runtime.Symbol.parse_state, java_cup.runtime.lr_parser.shift_under_error(), java_cup.runtime.lr_parser.stack, java_cup.runtime.lr_parser.tos, and java_cup.runtime.Symbol.used_by_parser.
Referenced by java_cup.runtime.lr_parser.error_recovery().
final short java_cup.runtime.lr_parser.get_action (int state, int sym) [protected]
Fetch an action from the action table. The table is broken up into rows, one per state (rows are indexed directly by state number). Within each row, a list of index, value pairs are given (as sequential entries in the table), and the list is terminated by a default entry (denoted with a Symbol index of -1). To find the proper entry in a row we do a linear or binary search (depending on the size of the row).
Parameters:
state the state index of the action being accessed.
sym the Symbol index of the action being accessed.
Definition at line 424 of file lr_parser.java.
References java_cup.runtime.lr_parser.action_tab.
Referenced by java_cup.runtime.lr_parser.debug_parse(), java_cup.runtime.lr_parser.find_recovery_config(), java_cup.runtime.lr_parser.parse(), java_cup.runtime.lr_parser.parse_lookahead(), java_cup.runtime.lr_parser.shift_under_error(), and java_cup.runtime.lr_parser.try_parse_ahead().
final short java_cup.runtime.lr_parser.get_reduce (int state, int sym) [protected]
Fetch a state from the reduce-goto table. The table is broken up into rows, one per state (rows are indexed directly by state number). Within each row, a list of index, value pairs are given (as sequential entries in the table), and the list is terminated by a default entry (denoted with a Symbol index of -1). To find the proper entry in a row we do a linear search.
Parameters:
state the state index of the entry being accessed.
sym the Symbol index of the entry being accessed.
Definition at line 479 of file lr_parser.java.
References java_cup.runtime.lr_parser.reduce_tab.
Referenced by java_cup.runtime.lr_parser.debug_parse(), java_cup.runtime.lr_parser.parse(), java_cup.runtime.lr_parser.parse_lookahead(), and java_cup.runtime.lr_parser.try_parse_ahead().
Scanner java_cup.runtime.lr_parser.getScanner ()
Simple accessor method to get the default scanner.
Definition at line 283 of file lr_parser.java.
References java_cup.runtime.lr_parser._scanner.
Referenced by java_cup.runtime.lr_parser.scan().
abstract void java_cup.runtime.lr_parser.init_actions () throws java.lang.Exception [protected, pure virtual]
Initialize the action object. This is called before the parser does any parse actions. This is filled in by generated code to create an object that encapsulates all action code.
Implemented in java_cup.parser, Scheme.parser, and java_cup.simple_calc.parser.
Referenced by java_cup.runtime.lr_parser.debug_parse(), and java_cup.runtime.lr_parser.parse().
Symbol java_cup.runtime.lr_parser.parse () throws java.lang.Exception
This method provides the main parsing routine. It returns only when done_parsing() has been called (typically because the parser has accepted, or a fatal error has been reported). See the header documentation for the class regarding how shift/reduce parsers operate and how the various tables are used.
Definition at line 510 of file lr_parser.java.
References java_cup.runtime.lr_parser._done_parsing, java_cup.runtime.lr_parser.action_tab, java_cup.runtime.lr_parser.action_table(), java_cup.runtime.lr_parser.cur_token, java_cup.runtime.lr_parser.do_action(), java_cup.runtime.lr_parser.done_parsing(), java_cup.runtime.lr_parser.error_recovery(), java_cup.runtime.lr_parser.get_action(), java_cup.runtime.lr_parser.get_reduce(), java_cup.runtime.lr_parser.init_actions(), java_cup.runtime.Symbol.parse_state, java_cup.runtime.lr_parser.production_tab, java_cup.runtime.lr_parser.production_table(), java_cup.runtime.lr_parser.reduce_tab, java_cup.runtime.lr_parser.reduce_table(), java_cup.runtime.lr_parser.scan(), java_cup.runtime.lr_parser.stack, java_cup.runtime.lr_parser.start_state(), java_cup.runtime.Symbol.sym, java_cup.runtime.lr_parser.syntax_error(), java_cup.runtime.lr_parser.tos, java_cup.runtime.lr_parser.unrecovered_syntax_error(), java_cup.runtime.Symbol.used_by_parser, and java_cup.runtime.lr_parser.user_init().
Referenced by Scheme.RunEnv.interpreter_file(), Scheme.RunEnv.load(), java_cup.simple_calc.Main.main(), java_cup.Main.parse_grammar_spec(), Scheme.RunEnv.read(), and Scheme.RunEnv.InterpreterThread.run().
void java_cup.runtime.lr_parser.parse_lookahead (boolean debug) throws java.lang.Exception [protected]
Parse forward using stored lookahead Symbols. In this case we have already verified that parsing will make it through the stored lookahead Symbols and we are now getting back to the point at which we can hand control back to the normal parser. Consequently, this version of the parser performs all actions and modifies the real parse configuration. This returns once we have consumed all the stored input or we accept.
Parameters:
debug should we produce debugging messages as we parse.
Definition at line 1114 of file lr_parser.java.
References java_cup.runtime.lr_parser._done_parsing, java_cup.runtime.lr_parser.advance_lookahead(), java_cup.runtime.lr_parser.cur_err_token(), java_cup.runtime.lr_parser.debug_message(), java_cup.runtime.lr_parser.debug_reduce(), java_cup.runtime.lr_parser.debug_shift(), java_cup.runtime.lr_parser.do_action(), java_cup.runtime.lr_parser.get_action(), java_cup.runtime.lr_parser.get_reduce(), java_cup.runtime.lr_parser.lookahead_pos, java_cup.runtime.Symbol.parse_state, java_cup.runtime.lr_parser.production_tab, java_cup.runtime.lr_parser.report_fatal_error(), java_cup.runtime.lr_parser.stack, java_cup.runtime.Symbol.sym, java_cup.runtime.lr_parser.tos, and java_cup.runtime.Symbol.used_by_parser.
Referenced by java_cup.runtime.lr_parser.error_recovery().
abstract short [][] java_cup.runtime.lr_parser.production_table () [pure virtual]
Table of production information (supplied by generated subclass). This table contains one entry per production and is indexed by the negative-encoded values (reduce actions) in the action_table. Each entry has two parts, the index of the non-terminal on the left hand side of the production, and the number of Symbols on the right hand side.
Implemented in java_cup.parser, Scheme.parser, and java_cup.simple_calc.parser.
Referenced by java_cup.runtime.lr_parser.debug_parse(), and java_cup.runtime.lr_parser.parse().
void java_cup.runtime.lr_parser.read_lookahead () throws java.lang.Exception [protected]
Read from input to establish our buffer of "parse ahead" lookahead Symbols.
Definition at line 978 of file lr_parser.java.
References java_cup.runtime.lr_parser.cur_token, java_cup.runtime.lr_parser.error_sync_size(), java_cup.runtime.lr_parser.lookahead, java_cup.runtime.lr_parser.lookahead_pos, and java_cup.runtime.lr_parser.scan().
Referenced by java_cup.runtime.lr_parser.error_recovery().
abstract short [][] java_cup.runtime.lr_parser.reduce_table () [pure virtual]
The reduce-goto table (supplied by generated subclass). This table is indexed by state and non-terminal number and contains state numbers. States are indexed using the first dimension, however, the entries for a given state are compacted and stored in adjacent index, value pairs which are searched for rather than accessed directly (see get_reduce()). When a reduce occurs, the handle (corresponding to the RHS of the matched production) is popped off the stack. The new top of stack indicates a state. This table is then indexed by that state and the LHS of the reducing production to indicate where to "shift" to.
See also:
java_cup.runtime.lr_parser::get_reduce
Implemented in java_cup.parser, Scheme.parser, and java_cup.simple_calc.parser.
Referenced by java_cup.runtime.lr_parser.debug_parse(), and java_cup.runtime.lr_parser.parse().
void java_cup.runtime.lr_parser.report_error (String message, Object info)
Report a non fatal error (or warning). This method takes a message string and an additional object (to be used by specializations implemented in subclasses). Here in the base class a very simple implementation is provided which simply prints the message to System.err.
Parameters:
message an error message.
info an extra object reserved for use by specialized subclasses.
Reimplemented in java_cup.parser.
Definition at line 375 of file lr_parser.java.
Referenced by java_cup.runtime.lr_parser.report_fatal_error(), Scheme.parser.syntax_error(), and java_cup.runtime.lr_parser.syntax_error().
void java_cup.runtime.lr_parser.report_fatal_error (String message, Object info) throws java.lang.Exception
Report a fatal error. This method takes a message string and an additional object (to be used by specializations implemented in subclasses). Here in the base class a very simple implementation is provided which reports the error then throws an exception.
Parameters:
message an error message.
info an extra object reserved for use by specialized subclasses.
Reimplemented in java_cup.parser.
Definition at line 349 of file lr_parser.java.
References java_cup.runtime.lr_parser.done_parsing(), and java_cup.runtime.lr_parser.report_error().
Referenced by java_cup.runtime.lr_parser.parse_lookahead(), and java_cup.runtime.lr_parser.unrecovered_syntax_error().
void java_cup.runtime.lr_parser.restart_lookahead () throws java.lang.Exception [protected]
Reset the parse ahead input to one Symbol past where we started error recovery (this consumes one new Symbol from the real input).
Definition at line 1018 of file lr_parser.java.
References java_cup.runtime.lr_parser.cur_token, java_cup.runtime.lr_parser.error_sync_size(), java_cup.runtime.lr_parser.lookahead, java_cup.runtime.lr_parser.lookahead_pos, and java_cup.runtime.lr_parser.scan().
Referenced by java_cup.runtime.lr_parser.error_recovery().
Symbol java_cup.runtime.lr_parser.scan () throws java.lang.Exception
Get the next Symbol from the input (supplied by generated subclass). Once end of file has been reached, all subsequent calls to scan should return an EOF Symbol (which is Symbol number 0). By default this method returns getScanner().next_token(); this implementation can be overriden by the generated parser using the code declared in the "scan with" clause. Do not recycle objects; every call to scan() should return a fresh object.
Reimplemented in java_cup.parser.
Definition at line 334 of file lr_parser.java.
References java_cup.runtime.lr_parser.getScanner(), and java_cup.runtime.Scanner.next_token().
Referenced by java_cup.runtime.lr_parser.debug_parse(), java_cup.runtime.lr_parser.parse(), java_cup.runtime.lr_parser.read_lookahead(), and java_cup.runtime.lr_parser.restart_lookahead().
void java_cup.runtime.lr_parser.setScanner (Scanner s)
Simple accessor method to set the default scanner.
Definition at line 278 of file lr_parser.java.
References java_cup.runtime.lr_parser._scanner.
Referenced by java_cup.runtime.lr_parser.lr_parser().
boolean java_cup.runtime.lr_parser.shift_under_error () [protected]
Determine if we can shift under the special error Symbol out of the state currently on the top of the (real) parse stack.
Definition at line 902 of file lr_parser.java.
References java_cup.runtime.lr_parser.error_sym(), java_cup.runtime.lr_parser.get_action(), and java_cup.runtime.lr_parser.stack.
Referenced by java_cup.runtime.lr_parser.find_recovery_config().
abstract int java_cup.runtime.lr_parser.start_production () [pure virtual]
The index of the start production (supplied by generated subclass).
Implemented in java_cup.parser, Scheme.parser, and java_cup.simple_calc.parser.
Referenced by java_cup.runtime.lr_parser.try_parse_ahead().
abstract int java_cup.runtime.lr_parser.start_state () [pure virtual]
The index of the start state (supplied by generated subclass).
Implemented in java_cup.parser, Scheme.parser, and java_cup.simple_calc.parser.
Referenced by java_cup.runtime.lr_parser.debug_parse(), and java_cup.runtime.lr_parser.parse().
void java_cup.runtime.lr_parser.syntax_error (Symbol cur_token)
This method is called when a syntax error has been detected and recovery is about to be invoked. Here in the base class we just emit a "Syntax error" error message.
Parameters:
cur_token the current lookahead Symbol.
Definition at line 394 of file lr_parser.java.
References java_cup.runtime.lr_parser.report_error().
Referenced by java_cup.runtime.lr_parser.debug_parse(), and java_cup.runtime.lr_parser.parse().
boolean java_cup.runtime.lr_parser.try_parse_ahead (boolean debug) throws java.lang.Exception [protected]
Do a simulated parse forward (a "parse ahead") from the current stack configuration using stored lookahead input and a virtual parse stack. Return true if we make it all the way through the stored lookahead input without error. This basically simulates the action of parse() using only our saved "parse ahead" input, and not executing any actions.
Parameters:
debug should we produce debugging messages as we parse.
Definition at line 1043 of file lr_parser.java.
References java_cup.runtime.lr_parser.advance_lookahead(), java_cup.runtime.lr_parser.cur_err_token(), java_cup.runtime.lr_parser.debug_message(), java_cup.runtime.lr_parser.get_action(), java_cup.runtime.lr_parser.get_reduce(), java_cup.runtime.virtual_parse_stack.pop(), java_cup.runtime.lr_parser.production_tab, java_cup.runtime.virtual_parse_stack.push(), java_cup.runtime.lr_parser.stack, java_cup.runtime.lr_parser.start_production(), java_cup.runtime.Symbol.sym, and java_cup.runtime.virtual_parse_stack.top().
Referenced by java_cup.runtime.lr_parser.error_recovery().
static short [][] java_cup.runtime.lr_parser.unpackFromStrings (String[] sa) [static, protected]
Utility function: unpacks parse tables from strings
Definition at line 1220 of file lr_parser.java.
void java_cup.runtime.lr_parser.unrecovered_syntax_error (Symbol cur_token) throws java.lang.Exception
This method is called if it is determined that syntax error recovery has been unsuccessful. Here in the base class we report a fatal error.
Parameters:
cur_token the current lookahead Symbol.
Definition at line 406 of file lr_parser.java.
References java_cup.runtime.lr_parser.cur_token, and java_cup.runtime.lr_parser.report_fatal_error().
Referenced by java_cup.runtime.lr_parser.debug_parse(), and java_cup.runtime.lr_parser.parse().
void java_cup.runtime.lr_parser.user_init () throws java.lang.Exception
User code for initialization inside the parser. Typically this initializes the scanner. This is called before the parser requests the first Symbol. Here this is just a placeholder for subclasses that might need this and we perform no action. This method is normally overridden by the generated code using this contents of the "init with" clause as its body.
Reimplemented in java_cup.parser.
Definition at line 314 of file lr_parser.java.
Referenced by java_cup.runtime.lr_parser.debug_parse(), and java_cup.runtime.lr_parser.parse().
Member Data Documentation
boolean java_cup.runtime.lr_parser._done_parsing = false [protected]
Internal flag to indicate when parser should quit.
Definition at line 222 of file lr_parser.java.
Referenced by java_cup.runtime.lr_parser.debug_parse(), java_cup.runtime.lr_parser.done_parsing(), java_cup.runtime.lr_parser.parse(), and java_cup.runtime.lr_parser.parse_lookahead().
final int java_cup.runtime.lr_parser._error_sync_size = 3 [static, protected]
The default number of Symbols after an error we much match to consider it recovered from.
Definition at line 140 of file lr_parser.java.
Referenced by java_cup.runtime.lr_parser.error_sync_size().
Scanner java_cup.runtime.lr_parser._scanner [private]
This is the scanner object used by the default implementation of scan() to get Symbols. To avoid name conflicts with existing code, this field is private. [CSA/davidm]
Definition at line 273 of file lr_parser.java.
Referenced by java_cup.runtime.lr_parser.getScanner(), and java_cup.runtime.lr_parser.setScanner().
short [][] java_cup.runtime.lr_parser.action_tab [protected]
Direct reference to the action table.
Definition at line 261 of file lr_parser.java.
Referenced by java_cup.runtime.lr_parser.debug_parse(), java_cup.runtime.lr_parser.get_action(), and java_cup.runtime.lr_parser.parse().
Symbol java_cup.runtime.lr_parser.cur_token [protected]
The current lookahead Symbol.
Definition at line 246 of file lr_parser.java.
Referenced by java_cup.runtime.lr_parser.debug_parse(), java_cup.runtime.lr_parser.parse(), java_cup.runtime.lr_parser.read_lookahead(), java_cup.runtime.lr_parser.restart_lookahead(), and java_cup.runtime.lr_parser.unrecovered_syntax_error().
Symbol java_cup.runtime.lr_parser.lookahead[] [protected]
Lookahead Symbols used for attempting error recovery "parse aheads".
Definition at line 968 of file lr_parser.java.
Referenced by java_cup.runtime.lr_parser.cur_err_token(), java_cup.runtime.lr_parser.error_recovery(), java_cup.runtime.lr_parser.read_lookahead(), and java_cup.runtime.lr_parser.restart_lookahead().
int java_cup.runtime.lr_parser.lookahead_pos [protected]
Position in lookahead input buffer used for "parse ahead".
Definition at line 971 of file lr_parser.java.
Referenced by java_cup.runtime.lr_parser.advance_lookahead(), java_cup.runtime.lr_parser.cur_err_token(), java_cup.runtime.lr_parser.parse_lookahead(), java_cup.runtime.lr_parser.read_lookahead(), and java_cup.runtime.lr_parser.restart_lookahead().
short [][] java_cup.runtime.lr_parser.production_tab [protected]
Direct reference to the production table.
Definition at line 256 of file lr_parser.java.
Referenced by java_cup.runtime.lr_parser.debug_parse(), java_cup.runtime.lr_parser.parse(), java_cup.runtime.lr_parser.parse_lookahead(), and java_cup.runtime.lr_parser.try_parse_ahead().
short [][] java_cup.runtime.lr_parser.reduce_tab [protected]
Direct reference to the reduce-goto table.
Definition at line 266 of file lr_parser.java.
Referenced by java_cup.runtime.lr_parser.debug_parse(), java_cup.runtime.lr_parser.get_reduce(), and java_cup.runtime.lr_parser.parse().
Stack java_cup.runtime.lr_parser.stack = new Stack() [protected]
The parse stack itself.
Definition at line 251 of file lr_parser.java.
Referenced by java_cup.runtime.lr_parser.debug_parse(), java_cup.runtime.lr_parser.debug_stack(), java_cup.simple_calc.parser.do_action(), Scheme.parser.do_action(), java_cup.parser.do_action(), java_cup.runtime.lr_parser.dump_stack(), java_cup.runtime.lr_parser.find_recovery_config(), java_cup.runtime.lr_parser.parse(), java_cup.runtime.lr_parser.parse_lookahead(), java_cup.runtime.lr_parser.shift_under_error(), and java_cup.runtime.lr_parser.try_parse_ahead().
int java_cup.runtime.lr_parser.tos [protected]
Indication of the index for top of stack (for use by actions).
Definition at line 241 of file lr_parser.java.
Referenced by java_cup.runtime.lr_parser.debug_parse(), java_cup.runtime.lr_parser.find_recovery_config(), java_cup.runtime.lr_parser.parse(), and java_cup.runtime.lr_parser.parse_lookahead().
The documentation for this class was generated from the following file:
src/java_cup/runtime/lr_parser.java