Jamus Scheme: java_cup.symbol_part Class Reference
java_cup.symbol_part Class Reference
Public Member Functions
symbol_part (symbol sym, String lab) throws internal_error
symbol_part (symbol sym) throws internal_error
symbol the_symbol ()
boolean is_action ()
boolean equals (symbol_part other)
boolean equals (Object other)
int hashCode ()
String toString ()
Protected Attributes
symbol _the_symbol
Detailed Description
This class represents a part of a production which is a symbol (terminal or non terminal). This simply maintains a reference to the symbol in question.
See also:
java_cup.production
Version:
last updated: 11/25/95
Author:
Scott Hudson
Definition at line 11 of file symbol_part.java.
Constructor & Destructor Documentation
java_cup.symbol_part.symbol_part (symbol sym, String lab) throws internal_error
Full constructor.
Parameters:
sym the symbol that this part is made up of.
lab an optional label string for the part.
Definition at line 21 of file symbol_part.java.
References java_cup.symbol_part._the_symbol.
java_cup.symbol_part.symbol_part (symbol sym) throws internal_error
Constructor with no label.
Parameters:
sym the symbol that this part is made up of.
Definition at line 36 of file symbol_part.java.
Member Function Documentation
boolean java_cup.symbol_part.equals (symbol_part other)
Equality comparison.
Definition at line 61 of file symbol_part.java.
References java_cup.symbol_part.equals(), and java_cup.symbol_part.the_symbol().
Referenced by java_cup.symbol_part.equals().
boolean java_cup.symbol_part.equals (Object other)
Generic equality comparison.
Reimplemented from java_cup.production_part.
Definition at line 70 of file symbol_part.java.
References java_cup.symbol_part.equals().
int java_cup.symbol_part.hashCode ()
Produce a hash code.
Reimplemented from java_cup.production_part.
Definition at line 81 of file symbol_part.java.
References java_cup.symbol_part.the_symbol().
boolean java_cup.symbol_part.is_action () [virtual]
Respond that we are not an action part.
Implements java_cup.production_part.
Definition at line 56 of file symbol_part.java.
symbol java_cup.symbol_part.the_symbol ()
The symbol that this part is made up of.
Definition at line 49 of file symbol_part.java.
References java_cup.symbol_part._the_symbol.
Referenced by java_cup.$actions.add_precedence(), java_cup.production.declare_labels(), java_cup.Main.dump_grammar(), java_cup.lalr_state.dump_state(), java_cup.emit.emit_action_code(), java_cup.emit.emit_production_table(), java_cup.symbol_part.equals(), java_cup.symbol_part.hashCode(), java_cup.lr_item_core.to_simple_string(), java_cup.production.to_simple_string(), and java_cup.symbol_part.toString().
String java_cup.symbol_part.toString ()
Convert to a string.
Reimplemented from java_cup.production_part.
Definition at line 90 of file symbol_part.java.
References java_cup.symbol_part.the_symbol().
Referenced by java_cup.production.toString().
Member Data Documentation
symbol java_cup.symbol_part._the_symbol [protected]
The symbol that this part is made up of.
Definition at line 46 of file symbol_part.java.
Referenced by java_cup.symbol_part.symbol_part(), and java_cup.symbol_part.the_symbol().
The documentation for this class was generated from the following file:
src/java_cup/symbol_part.java