Jamus Scheme: Scheme.UseScheme Class Reference
Scheme.UseScheme Class Reference
Static Public Member Functions
static void main (String[] args) throws Exception
Detailed Description
Definition at line 5 of file UseScheme.java.
Member Function Documentation
static void Scheme.UseScheme.main (String[] args) throws Exception [static]
Definition at line 19 of file UseScheme.java.
References Scheme.RunEnv.init(), Scheme.RunEnv.interpreter_dialog(), and Scheme.RunEnv.interpreter_file().
The documentation for this class was generated from the following file:
src/Scheme/UseScheme.java