Jamus Scheme: Scheme.StElem Class Reference
Scheme.StElem Class Reference
Public Member Functions
StElem (String pname)
StElem ()
String getPname ()
void setPname (String p)
Object getValue ()
void setValue (Object e)
Object getToplevelValue ()
void setToplevelValue (Object e)
String getMode ()
void setMode (String m)
ISchemeObject expand ()
ISchemeObject expandall ()
ISchemeObject eval ()
SchemeString symbolstring ()
void print ()
ISchemeObject printp (BufferedWriter open_buffer_writer)
Package Attributes
String pname
String mode
Object value
Object toplevelvalue
Symbol next
Detailed Description
Definition at line 5 of file StElem.java.
Constructor & Destructor Documentation
Scheme.StElem.StElem (String pname)
Definition at line 12 of file StElem.java.
References Scheme.StElem.mode, and Scheme.StElem.pname.
Scheme.StElem.StElem ()
Definition at line 21 of file StElem.java.
References Scheme.StElem.mode.
Member Function Documentation
ISchemeObject Scheme.StElem.eval ()
Evaluates a scheme expression and returns a new scheme object. Which object is returned, depends on the scheme expression.
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Returns:
a scheme object. Which type of scheme object can be found out with castings.
Reimplemented from Scheme.SchemeObject.
Definition at line 71 of file StElem.java.
References Scheme.StElem.getMode(), Scheme.StElem.getToplevelValue(), Scheme.StElem.getValue(), Scheme.RunEnv.nilval, Scheme.StElem.print(), Scheme.StElem.toplevelvalue, and Scheme.RunEnv.unbound.
ISchemeObject Scheme.StElem.expand ()
Expands a scheme expression once. Which object is returned, depends on the scheme expression.
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Returns:
a scheme object. Which type of scheme object can be found out with castings.
See also:
e.g. symbolp(), numberp(), integerp(), realp(), pairp(), listp(), nullp()
Reimplemented from Scheme.SchemeObject.
Definition at line 61 of file StElem.java.
ISchemeObject Scheme.StElem.expandall ()
Expands a scheme expression until it cannot be expanded anymore. Which object is returned, depends on the scheme expression.
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Returns:
a scheme object. Which type of scheme object can be found out with castings.
See also:
e.g. symbolp(), numberp(), integerp(), realp(), pairp(), listp(), nullp()
Reimplemented from Scheme.SchemeObject.
Definition at line 66 of file StElem.java.
String Scheme.StElem.getMode ()
Reimplemented in Scheme.Symbol.
Definition at line 52 of file StElem.java.
References Scheme.StElem.mode.
Referenced by Scheme.StElem.eval().
String Scheme.StElem.getPname ()
Definition at line 25 of file StElem.java.
References Scheme.StElem.pname.
Referenced by Scheme.RunEnv.intern(), Scheme.RunEnv.newSymEntry(), and Scheme.StElem.symbolstring().
Object Scheme.StElem.getToplevelValue ()
Definition at line 42 of file StElem.java.
References Scheme.StElem.toplevelvalue.
Referenced by Scheme.StElem.eval().
Object Scheme.StElem.getValue ()
Definition at line 33 of file StElem.java.
References Scheme.StElem.value.
Referenced by Scheme.StElem.eval().
void Scheme.StElem.print ()
Prints the scheme object to 'stdout' (mostly a console).
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Reimplemented from Scheme.SchemeObject.
Reimplemented in Scheme.SchemePort, Scheme.SchemeFunction, Scheme.Symbol, Scheme.SchemeBoolean, Scheme.SchemeString, and Scheme.Function.
Definition at line 116 of file StElem.java.
References Scheme.StElem.pname.
Referenced by Scheme.StElem.eval().
ISchemeObject Scheme.StElem.printp (BufferedWriter open_buffer_writer)
Prints the scheme object to the BufferedWriter.
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Implements Scheme.ISchemeObject.
Reimplemented in Scheme.SchemePort, Scheme.SchemeFunction, Scheme.SchemeString, and Scheme.Symbol.
Definition at line 121 of file StElem.java.
References Scheme.RunEnv.nilval, and Scheme.StElem.pname.
void Scheme.StElem.setMode (String m)
Definition at line 56 of file StElem.java.
References Scheme.StElem.mode.
Referenced by Scheme.RunEnv.newSymEntry().
void Scheme.StElem.setPname (String p)
Definition at line 29 of file StElem.java.
References Scheme.StElem.pname.
void Scheme.StElem.setToplevelValue (Object e)
Definition at line 46 of file StElem.java.
References Scheme.StElem.toplevelvalue.
void Scheme.StElem.setValue (Object e)
Definition at line 38 of file StElem.java.
References Scheme.StElem.value.
Referenced by Scheme.RunEnv.newSymEntry().
SchemeString Scheme.StElem.symbolstring ()
Definition at line 106 of file StElem.java.
References Scheme.StElem.getPname().
Member Data Documentation
String Scheme.StElem.mode [package]
Definition at line 7 of file StElem.java.
Referenced by Scheme.Symbol.getMode(), Scheme.StElem.getMode(), Scheme.SchemeFunction.SchemeFunction(), Scheme.StElem.setMode(), and Scheme.StElem.StElem().
Symbol Scheme.StElem.next [package]
Definition at line 10 of file StElem.java.
String Scheme.StElem.pname [package]
Definition at line 6 of file StElem.java.
Referenced by Scheme.StElem.getPname(), Scheme.SchemeBoolean.print(), Scheme.Symbol.print(), Scheme.StElem.print(), Scheme.Symbol.printp(), Scheme.StElem.printp(), Scheme.StElem.setPname(), and Scheme.StElem.StElem().
Object Scheme.StElem.toplevelvalue [package]
Definition at line 9 of file StElem.java.
Referenced by Scheme.StElem.eval(), Scheme.StElem.getToplevelValue(), and Scheme.StElem.setToplevelValue().
Object Scheme.StElem.value [package]
Reimplemented from Scheme.SchemeObject.
Reimplemented in Scheme.SchemeString.
Definition at line 8 of file StElem.java.
Referenced by Scheme.StElem.getValue(), Scheme.SchemeBoolean.not(), and Scheme.StElem.setValue().
The documentation for this class was generated from the following file:
src/Scheme/StElem.java