Jamus Scheme: java_cup.reduce_action Class Reference
java_cup.reduce_action Class Reference
Public Member Functions
reduce_action (production prod) throws internal_error
production reduce_with ()
int kind ()
boolean equals (reduce_action other)
boolean equals (Object other)
int hashCode ()
String toString ()
Protected Attributes
production _reduce_with
Detailed Description
This class represents a reduce action within the parse table. The action simply stores the production that it reduces with and responds to queries about its type.
Version:
last updated: 11/25/95
Author:
Scott Hudson
Definition at line 11 of file reduce_action.java.
Constructor & Destructor Documentation
java_cup.reduce_action.reduce_action (production prod) throws internal_error
Simple constructor.
Parameters:
prod the production this action reduces with.
Definition at line 20 of file reduce_action.java.
References java_cup.reduce_action._reduce_with.
Member Function Documentation
boolean java_cup.reduce_action.equals (reduce_action other)
Equality test.
Definition at line 50 of file reduce_action.java.
References java_cup.reduce_action.reduce_with().
Referenced by java_cup.reduce_action.equals().
boolean java_cup.reduce_action.equals (Object other)
Generic equality test.
Reimplemented from java_cup.parse_action.
Definition at line 58 of file reduce_action.java.
References java_cup.reduce_action.equals().
int java_cup.reduce_action.hashCode ()
Compute a hash code.
Reimplemented from java_cup.parse_action.
Definition at line 69 of file reduce_action.java.
References java_cup.production.hashCode(), and java_cup.reduce_action.reduce_with().
int java_cup.reduce_action.kind ()
Quick access to type of action.
Reimplemented from java_cup.parse_action.
Definition at line 45 of file reduce_action.java.
References java_cup.parse_action.REDUCE.
production java_cup.reduce_action.reduce_with ()
The production we reduce with.
Definition at line 38 of file reduce_action.java.
References java_cup.reduce_action._reduce_with.
Referenced by java_cup.reduce_action.equals(), java_cup.reduce_action.hashCode(), and java_cup.reduce_action.toString().
String java_cup.reduce_action.toString ()
Convert to string.
Reimplemented from java_cup.parse_action.
Definition at line 77 of file reduce_action.java.
References java_cup.production.index(), and java_cup.reduce_action.reduce_with().
Member Data Documentation
production java_cup.reduce_action._reduce_with [protected]
The production we reduce with.
Definition at line 35 of file reduce_action.java.
Referenced by java_cup.reduce_action.reduce_action(), and java_cup.reduce_action.reduce_with().
The documentation for this class was generated from the following file:
src/java_cup/reduce_action.java