Jamus Scheme: java_cup.parser Class Reference
java_cup.parser Class Reference
Public Member Functions
parser (BufferedInputStream buf)
parser (java_cup.runtime.Scanner s)
short[][] production_table ()
short[][] action_table ()
short[][] reduce_table ()
java_cup.runtime.Symbol do_action (int act_num, java_cup.runtime.lr_parser parser, java.util.Stack stack, int top) throws java.lang.Exception
int start_state ()
int start_production ()
int EOF_sym ()
int error_sym ()
void user_init () throws java.lang.Exception
java_cup.runtime.Symbol scan () throws java.lang.Exception
void report_fatal_error (String message, Object info)
void report_error (String message, Object info)
Protected Member Functions
void init_actions ()
Protected Attributes
CUP $parser $actions action_obj
Static Protected Attributes
static final short _production_table [][]
static final short[][] _action_table
static final short[][] _reduce_table
Package Attributes
BufferedInputStream b
Detailed Description
CUP v0.10j generated parser.
Version:
Sat Jul 24 08:05:57 EDT 1999
Definition at line 16 of file parser.java.
Constructor & Destructor Documentation
java_cup.parser.parser (BufferedInputStream buf)
Default constructor.
Definition at line 22 of file parser.java.
References java_cup.parser.b.
java_cup.parser.parser (java_cup.runtime.Scanner s)
Constructor which sets the default scanner.
Definition at line 28 of file parser.java.
Member Function Documentation
short [][] java_cup.parser.action_table () [virtual]
Access to parse-action table.
Implements java_cup.runtime.lr_parser.
Definition at line 255 of file parser.java.
References java_cup.parser._action_table.
java_cup.runtime.Symbol java_cup.parser.do_action (int act_num, java_cup.runtime.lr_parser parser, java.util.Stack stack, int top) throws java.lang.Exception
Invoke a user supplied parse action.
Definition at line 345 of file parser.java.
References java_cup.parser.action_obj, and java_cup.runtime.lr_parser.stack.
int java_cup.parser.EOF_sym () [virtual]
EOF Symbol index.
Implements java_cup.runtime.lr_parser.
Definition at line 362 of file parser.java.
int java_cup.parser.error_sym () [virtual]
error Symbol index.
Implements java_cup.runtime.lr_parser.
Definition at line 365 of file parser.java.
void java_cup.parser.init_actions () [protected, virtual]
Action encapsulation object initializer.
Implements java_cup.runtime.lr_parser.
Definition at line 339 of file parser.java.
References java_cup.parser.action_obj.
short [][] java_cup.parser.production_table () [virtual]
Access to production table.
Implements java_cup.runtime.lr_parser.
Definition at line 69 of file parser.java.
References java_cup.parser._production_table.
short [][] java_cup.parser.reduce_table () [virtual]
Access to reduce_goto table.
Implements java_cup.runtime.lr_parser.
Definition at line 333 of file parser.java.
References java_cup.parser._reduce_table.
void java_cup.parser.report_error (String message, Object info)
Report a non fatal error (or warning). This method takes a message string and an additional object (to be used by specializations implemented in subclasses). Here in the base class a very simple implementation is provided which simply prints the message to System.err.
Parameters:
message an error message.
info an extra object reserved for use by specialized subclasses.
Reimplemented from java_cup.runtime.lr_parser.
Definition at line 399 of file parser.java.
References java_cup.lexer.emit_error().
void java_cup.parser.report_fatal_error (String message, Object info)
Report a fatal error. This method takes a message string and an additional object (to be used by specializations implemented in subclasses). Here in the base class a very simple implementation is provided which reports the error then throws an exception.
Parameters:
message an error message.
info an extra object reserved for use by specialized subclasses.
Reimplemented from java_cup.runtime.lr_parser.
Definition at line 389 of file parser.java.
References java_cup.runtime.lr_parser.done_parsing(), and java_cup.lexer.emit_error().
java_cup.runtime.Symbol java_cup.parser.scan () throws java.lang.Exception
Scan to get the next Symbol.
Reimplemented from java_cup.runtime.lr_parser.
Definition at line 379 of file parser.java.
References java_cup.lexer.next_token().
int java_cup.parser.start_production () [virtual]
Indicates start production.
Implements java_cup.runtime.lr_parser.
Definition at line 359 of file parser.java.
int java_cup.parser.start_state () [virtual]
Indicates start state.
Implements java_cup.runtime.lr_parser.
Definition at line 357 of file parser.java.
void java_cup.parser.user_init () throws java.lang.Exception
User initialization code.
Reimplemented from java_cup.runtime.lr_parser.
Definition at line 369 of file parser.java.
References java_cup.parser.b, and java_cup.lexer.init().
Member Data Documentation
final short [][] java_cup.parser._action_table [static, protected]
Parse-action table.
Definition at line 72 of file parser.java.
Referenced by java_cup.parser.action_table().
final short java_cup.parser._production_table[][] [static, protected]
Production table.
Definition at line 31 of file parser.java.
Referenced by java_cup.parser.production_table().
final short [][] java_cup.parser._reduce_table [static, protected]
reduce_goto table.
Definition at line 258 of file parser.java.
Referenced by java_cup.parser.reduce_table().
CUP $parser $actions java_cup.parser.action_obj [protected]
Instance of action encapsulation class.
Definition at line 336 of file parser.java.
Referenced by java_cup.parser.do_action(), and java_cup.parser.init_actions().
BufferedInputStream java_cup.parser.b [package]
Definition at line 18 of file parser.java.
Referenced by java_cup.parser.parser(), and java_cup.parser.user_init().
The documentation for this class was generated from the following file:
src/java_cup/parser.java