Jamus Scheme: java_cup.simple_calc.scanner Class Reference
java_cup.simple_calc.scanner Class Reference
Public Member Functions
scanner (java.io.InputStream is) throws java.io.IOException
scanner () throws java.io.IOException
Symbol next_token () throws java.io.IOException
Protected Member Functions
void advance () throws java.io.IOException
Protected Attributes
int next_char
Package Attributes
final java.io.InputStream instream
Private Member Functions
void init () throws java.io.IOException
Detailed Description
Definition at line 7 of file scanner.java.
Constructor & Destructor Documentation
java_cup.simple_calc.scanner.scanner (java.io.InputStream is) throws java.io.IOException
Definition at line 10 of file scanner.java.
References java_cup.simple_calc.scanner.init(), and java_cup.simple_calc.scanner.instream.
java_cup.simple_calc.scanner.scanner () throws java.io.IOException
Definition at line 14 of file scanner.java.
Member Function Documentation
void java_cup.simple_calc.scanner.advance () throws java.io.IOException [protected]
Definition at line 20 of file scanner.java.
References java_cup.simple_calc.scanner.instream, and java_cup.simple_calc.scanner.next_char.
Referenced by java_cup.simple_calc.scanner.init(), and java_cup.simple_calc.scanner.next_token().
void java_cup.simple_calc.scanner.init () throws java.io.IOException [private]
Definition at line 25 of file scanner.java.
References java_cup.simple_calc.scanner.advance().
Referenced by java_cup.simple_calc.scanner.scanner().
Symbol java_cup.simple_calc.scanner.next_token () throws java.io.IOException
Implements java_cup.runtime.Scanner.
Definition at line 30 of file scanner.java.
References java_cup.simple_calc.scanner.advance(), java_cup.simple_calc.sym.DIVIDE, java_cup.simple_calc.sym.EOF, java_cup.simple_calc.sym.LPAREN, java_cup.simple_calc.sym.MINUS, java_cup.simple_calc.sym.MOD, java_cup.simple_calc.scanner.next_char, java_cup.simple_calc.sym.NUMBER, java_cup.simple_calc.sym.PLUS, java_cup.simple_calc.sym.RPAREN, java_cup.simple_calc.sym.SEMI, and java_cup.simple_calc.sym.TIMES.
Member Data Documentation
final java.io.InputStream java_cup.simple_calc.scanner.instream [package]
Definition at line 8 of file scanner.java.
Referenced by java_cup.simple_calc.scanner.advance(), and java_cup.simple_calc.scanner.scanner().
int java_cup.simple_calc.scanner.next_char [protected]
Definition at line 17 of file scanner.java.
Referenced by java_cup.simple_calc.scanner.advance(), and java_cup.simple_calc.scanner.next_token().
The documentation for this class was generated from the following file:
src/java_cup/simple_calc/scanner.java