Jamus Scheme: java_cup.parse_reduce_table Class Reference
java_cup.parse_reduce_table Class Reference
Public Member Functions
parse_reduce_table ()
int num_states ()
String toString ()
Public Attributes
parse_reduce_row[] under_state
Protected Attributes
int _num_states
Detailed Description
This class represents the complete "reduce-goto" table of the parser. It has one row for each state in the parse machines, and a column for each terminal symbol. Each entry contains a state number to shift to as the last step of a reduce.
See also:
java_cup.parse_reduce_row
Version:
last updated: 11/25/95
Author:
Scott Hudson
Definition at line 15 of file parse_reduce_table.java.
Constructor & Destructor Documentation
java_cup.parse_reduce_table.parse_reduce_table ()
Simple constructor. Note: all terminals, non-terminals, and productions must already have been entered, and the viable prefix recognizer should have been constructed before this is called.
Definition at line 25 of file parse_reduce_table.java.
References java_cup.parse_reduce_table._num_states, java_cup.lalr_state.number(), and java_cup.parse_reduce_table.under_state.
Member Function Documentation
int java_cup.parse_reduce_table.num_states ()
How many rows/states in the machine/table.
Definition at line 45 of file parse_reduce_table.java.
References java_cup.parse_reduce_table._num_states.
Referenced by java_cup.emit.do_reduce_table(), and java_cup.parse_reduce_table.toString().
String java_cup.parse_reduce_table.toString ()
Convert to a string.
Definition at line 57 of file parse_reduce_table.java.
References java_cup.lalr_state.index(), java_cup.parse_reduce_table.num_states(), java_cup.parse_reduce_row.size(), java_cup.parse_reduce_row.under_non_term, and java_cup.parse_reduce_table.under_state.
Member Data Documentation
int java_cup.parse_reduce_table._num_states [protected]
How many rows/states in the machine/table.
Definition at line 42 of file parse_reduce_table.java.
Referenced by java_cup.parse_reduce_table.num_states(), and java_cup.parse_reduce_table.parse_reduce_table().
parse_reduce_row [] java_cup.parse_reduce_table.under_state
Actual array of rows, one per state
Definition at line 50 of file parse_reduce_table.java.
Referenced by java_cup.emit.do_reduce_table(), java_cup.parse_reduce_table.parse_reduce_table(), and java_cup.parse_reduce_table.toString().
The documentation for this class was generated from the following file:
src/java_cup/parse_reduce_table.java