Jamus Scheme: Scheme.RunEnv.InterpreterThread Class Reference
Scheme.RunEnv.InterpreterThread Class Reference
Public Member Functions
void run ()
Package Functions
InterpreterThread ()
Private Attributes
PipedReader in
boolean run_interpreter = true
Detailed Description
Definition at line 867 of file RunEnv.java.
Constructor & Destructor Documentation
Scheme.RunEnv.InterpreterThread.InterpreterThread () [package]
Definition at line 871 of file RunEnv.java.
Member Function Documentation
void Scheme.RunEnv.InterpreterThread.run ()
Definition at line 875 of file RunEnv.java.
References Scheme.RunEnv.et, Scheme.RunEnv.EingabeThread.getEingabeThread(), Scheme.RunEnv.EingabeThread.getRunValue(), Scheme.RunEnv.InterpreterThread.in, java_cup.runtime.lr_parser.parse(), and Scheme.RunEnv.InterpreterThread.run_interpreter.
Member Data Documentation
PipedReader Scheme.RunEnv.InterpreterThread.in [private]
Definition at line 868 of file RunEnv.java.
Referenced by Scheme.RunEnv.InterpreterThread.run().
boolean Scheme.RunEnv.InterpreterThread.run_interpreter = true [private]
Definition at line 869 of file RunEnv.java.
Referenced by Scheme.RunEnv.InterpreterThread.run().
The documentation for this class was generated from the following file:
src/Scheme/RunEnv.java