Jamus Scheme: java_cup.lr_item_core Class Reference
java_cup.lr_item_core Class Reference
Public Member Functions
lr_item_core (production prod, int pos) throws internal_error
lr_item_core (production prod) throws internal_error
production the_production ()
int dot_pos ()
boolean dot_at_end ()
symbol symbol_after_dot ()
non_terminal dot_before_nt ()
lr_item_core shift_core () throws internal_error
boolean core_equals (lr_item_core other)
boolean equals (lr_item_core other)
boolean equals (Object other)
int core_hashCode ()
int hashCode ()
String to_simple_string () throws internal_error
String toString ()
Protected Member Functions
int obj_hash ()
Protected Attributes
production _the_production
int _dot_pos
int _core_hash_cache
symbol _symbol_after_dot = null
Detailed Description
The "core" of an LR item. This includes a production and the position of a marker (the "dot") within the production. Typically item cores are written using a production with an embedded "dot" to indicate their position. For example:
     A ::= B * C d E
This represents a point in a parse where the parser is trying to match the given production, and has succeeded in matching everything before the "dot" (and hence is expecting to see the symbols after the dot next). See lalr_item, lalr_item_set, and lalr_start for full details on the meaning and use of items.
See also:
java_cup.lalr_item
java_cup.lalr_item_set
java_cup.lalr_state
Version:
last updated: 11/25/95
Author:
Scott Hudson
Definition at line 23 of file lr_item_core.java.
Constructor & Destructor Documentation
java_cup.lr_item_core.lr_item_core (production prod, int pos) throws internal_error
Full constructor.
Parameters:
prod production this item uses.
pos position of the "dot" within the item.
Definition at line 33 of file lr_item_core.java.
References java_cup.lr_item_core._core_hash_cache, java_cup.lr_item_core._dot_pos, java_cup.lr_item_core._symbol_after_dot, java_cup.lr_item_core._the_production, java_cup.production.hashCode(), java_cup.production_part.is_action(), java_cup.production.rhs(), and java_cup.production.rhs_length().
Referenced by java_cup.lr_item_core.shift_core().
java_cup.lr_item_core.lr_item_core (production prod) throws internal_error
Constructor for dot at start of right hand side.
Parameters:
prod production this item uses.
Definition at line 67 of file lr_item_core.java.
Member Function Documentation
boolean java_cup.lr_item_core.core_equals (lr_item_core other)
Equality comparison for the core only. This is separate out because we need separate access in a super class.
Definition at line 162 of file lr_item_core.java.
References java_cup.lr_item_core._dot_pos, java_cup.lr_item_core._the_production, and java_cup.production.equals().
Referenced by java_cup.lr_item_core.equals().
int java_cup.lr_item_core.core_hashCode ()
Hash code for the core (separated so we keep non overridden version).
Definition at line 188 of file lr_item_core.java.
References java_cup.lr_item_core._core_hash_cache.
boolean java_cup.lr_item_core.dot_at_end ()
Is the dot at the end of the production?
Definition at line 109 of file lr_item_core.java.
References java_cup.lr_item_core._dot_pos, java_cup.lr_item_core._the_production, and java_cup.production.rhs_length().
Referenced by java_cup.lalr_state.build_table_entries(), java_cup.lalr_item.calc_lookahead(), java_cup.lalr_state.dump_state(), java_cup.lalr_item.lookahead_visible(), java_cup.lalr_state.report_conflicts(), java_cup.lalr_state.report_shift_reduce(), java_cup.lalr_item.shift(), and java_cup.lr_item_core.shift_core().
non_terminal java_cup.lr_item_core.dot_before_nt ()
Determine if we have a dot before a non terminal, and if so which one (return null or the non terminal).
Definition at line 129 of file lr_item_core.java.
References java_cup.symbol.is_non_term(), and java_cup.lr_item_core.symbol_after_dot().
Referenced by java_cup.lalr_item_set.compute_closure().
int java_cup.lr_item_core.dot_pos ()
The position of the "dot" -- this indicates the part of the production that the marker is before, so 0 indicates a dot at the beginning of the RHS.
Definition at line 94 of file lr_item_core.java.
References java_cup.lr_item_core._dot_pos.
Referenced by java_cup.lalr_item.calc_lookahead(), java_cup.lalr_state.dump_state(), java_cup.lalr_item.lookahead_visible(), and java_cup.lalr_item.shift().
boolean java_cup.lr_item_core.equals (lr_item_core other)
Equality comparison.
Definition at line 172 of file lr_item_core.java.
References java_cup.lr_item_core.core_equals().
Referenced by java_cup.lr_item_core.equals().
boolean java_cup.lr_item_core.equals (Object other)
Generic equality comparison.
Reimplemented in java_cup.lalr_item.
Definition at line 177 of file lr_item_core.java.
References java_cup.lr_item_core.equals().
int java_cup.lr_item_core.hashCode ()
Hash code for the item.
Reimplemented in java_cup.lalr_item.
Definition at line 196 of file lr_item_core.java.
References java_cup.lr_item_core._core_hash_cache.
int java_cup.lr_item_core.obj_hash () [protected]
Return the hash code that object would have provided for us so we have a (nearly) unique id for debugging.
Definition at line 206 of file lr_item_core.java.
lr_item_core java_cup.lr_item_core.shift_core () throws internal_error
Produce a new lr_item_core that results from shifting the dot one position to the right.
Definition at line 148 of file lr_item_core.java.
References java_cup.lr_item_core._dot_pos, java_cup.lr_item_core._the_production, java_cup.lr_item_core.dot_at_end(), and java_cup.lr_item_core.lr_item_core().
symbol java_cup.lr_item_core.symbol_after_dot ()
Return the symbol after the dot. If there is no symbol after the dot we return null.
Definition at line 118 of file lr_item_core.java.
References java_cup.lr_item_core._symbol_after_dot.
Referenced by java_cup.lalr_state.build_machine(), java_cup.lr_item_core.dot_before_nt(), and java_cup.lalr_state.report_shift_reduce().
production java_cup.lr_item_core.the_production ()
The production for the item.
Definition at line 80 of file lr_item_core.java.
References java_cup.lr_item_core._the_production.
Referenced by java_cup.lalr_state.build_table_entries(), java_cup.lalr_item.calc_lookahead(), java_cup.lalr_state.dump_state(), java_cup.lalr_item.lookahead_visible(), and java_cup.lalr_item.shift().
String java_cup.lr_item_core.to_simple_string () throws internal_error
Convert to a string (separated out from toString() so we can call it from subclass that overrides toString()).
Definition at line 216 of file lr_item_core.java.
References java_cup.lr_item_core._dot_pos, java_cup.lr_item_core._the_production, java_cup.production_part.is_action(), java_cup.production.lhs(), java_cup.symbol.name(), java_cup.production.rhs(), java_cup.production.rhs_length(), and java_cup.symbol_part.the_symbol().
Referenced by java_cup.lalr_state.report_shift_reduce(), and java_cup.lr_item_core.toString().
String java_cup.lr_item_core.toString ()
Convert to a string
Reimplemented in java_cup.lalr_item.
Definition at line 266 of file lr_item_core.java.
References java_cup.internal_error.crash(), and java_cup.lr_item_core.to_simple_string().
Member Data Documentation
int java_cup.lr_item_core._core_hash_cache [protected]
Cache of the hash code.
Definition at line 99 of file lr_item_core.java.
Referenced by java_cup.lr_item_core.core_hashCode(), java_cup.lr_item_core.hashCode(), and java_cup.lr_item_core.lr_item_core().
int java_cup.lr_item_core._dot_pos [protected]
The position of the "dot" -- this indicates the part of the production that the marker is before, so 0 indicates a dot at the beginning of the RHS.
Definition at line 88 of file lr_item_core.java.
Referenced by java_cup.lr_item_core.core_equals(), java_cup.lr_item_core.dot_at_end(), java_cup.lr_item_core.dot_pos(), java_cup.lr_item_core.lr_item_core(), java_cup.lr_item_core.shift_core(), and java_cup.lr_item_core.to_simple_string().
symbol java_cup.lr_item_core._symbol_after_dot = null [protected]
Cache of symbol after the dot.
Definition at line 104 of file lr_item_core.java.
Referenced by java_cup.lr_item_core.lr_item_core(), and java_cup.lr_item_core.symbol_after_dot().
production java_cup.lr_item_core._the_production [protected]
The production for the item.
Definition at line 77 of file lr_item_core.java.
Referenced by java_cup.lr_item_core.core_equals(), java_cup.lr_item_core.dot_at_end(), java_cup.lr_item_core.lr_item_core(), java_cup.lr_item_core.shift_core(), java_cup.lr_item_core.the_production(), and java_cup.lr_item_core.to_simple_string().
The documentation for this class was generated from the following file:
src/java_cup/lr_item_core.java