Jamus Scheme: java_cup.Main Class Reference
java_cup.Main Class Reference
Static Public Member Functions
static void main (String argv[]) throws internal_error, java.io.IOException, java.lang.Exception
static void dump_grammar () throws internal_error
static void dump_machine ()
static void dump_tables ()
Static Protected Member Functions
static void usage (String message)
static void parse_args (String argv[])
static void open_files ()
static void close_files () throws java.io.IOException
static void parse_grammar_spec () throws java.lang.Exception
static void check_unused ()
static void build_parser () throws internal_error
static void emit_parser () throws internal_error
static String plural (int val)
static void emit_summary (boolean output_produced)
static void show_times ()
static String timestr (long time_val, long total_time)
Static Protected Attributes
static boolean print_progress = true
static boolean opt_dump_states = false
static boolean opt_dump_tables = false
static boolean opt_dump_grammar = false
static boolean opt_show_timing = false
static boolean opt_do_debug = false
static boolean opt_compact_red = false
static boolean include_non_terms = false
static boolean no_summary = false
static int expect_conflicts = 0
static boolean lr_values = true
static boolean sym_interface = false
static boolean suppress_scanner = false
static long start_time = 0
static long prelim_end = 0
static long parse_end = 0
static long check_end = 0
static long dump_end = 0
static long build_end = 0
static long nullability_end = 0
static long first_end = 0
static long machine_end = 0
static long table_end = 0
static long reduce_check_end = 0
static long emit_end = 0
static long final_time = 0
static String arg_text = ""
static BufferedInputStream input_file
static PrintWriter parser_class_file
static PrintWriter symbol_class_file
static lalr_state start_state
static parse_action_table action_table
static parse_reduce_table reduce_table
Private Member Functions
Main ()
Detailed Description
This class serves as the main driver for the JavaCup system. It accepts user options and coordinates overall control flow. The main flow of control includes the following activities:
Parse user supplied arguments and options.
Open output files.
Parse the specification from standard input.
Check for unused terminals, non-terminals, and productions.
Build the state machine, tables, etc.
Output the generated code.
Close output files.
Print a summary if requested.
Options to the main program include:
-package name
specify package generated classes go in [default none]
-parser name
specify parser class name [default "parser"]
-symbols name
specify name for symbol constant class [default "sym"]
-interface
emit symbol constant interface, rather than class
-nonterms
put non terminals in symbol constant class
-expect #
number of conflicts expected/allowed [default 0]
-compact_red
compact tables by defaulting to most frequent reduce
-nowarn
don't warn about useless productions, etc.
-nosummary
don't print the usual summary of parse states, etc.
-progress
print messages to indicate progress of the system
-time
print time usage summary
-dump_grammar
produce a dump of the symbols and grammar
-dump_states
produce a dump of parse state machine
-dump_tables
produce a dump of the parse tables
-dump
produce a dump of all of the above
-debug
turn on debugging messages within JavaCup
-nopositions
don't generate the positions code
-noscanner
don't refer to java_cup.runtime.Scanner in the parser (for compatibility with old runtimes)
-version
print version information for JavaCUP and halt.
Version:
last updated: 7/3/96
Author:
Frank Flannery
Definition at line 67 of file Main.java.
Constructor & Destructor Documentation
java_cup.Main.Main () [private]
Only constructor is private, so we do not allocate any instances of this class.
Definition at line 74 of file Main.java.
Member Function Documentation
static void java_cup.Main.build_parser () throws internal_error [static, protected]
Build the (internal) parser from the previously parsed specification. This includes:
Computing nullability of non-terminals.
Computing first sets of non-terminals and productions.
Building the viable prefix recognizer machine.
Filling in the (internal) parse tables.
Checking for unreduced productions.
Definition at line 539 of file Main.java.
References java_cup.Main.action_table, java_cup.lalr_state.all(), java_cup.lalr_state.build_machine(), java_cup.lalr_state.build_table_entries(), java_cup.parse_action_table.check_reductions(), java_cup.non_terminal.compute_first_sets(), java_cup.non_terminal.compute_nullability(), java_cup.lexer.error_count, java_cup.Main.expect_conflicts, java_cup.Main.first_end, java_cup.Main.machine_end, java_cup.Main.nullability_end, java_cup.emit.num_conflicts, java_cup.Main.opt_do_debug, java_cup.Main.print_progress, java_cup.Main.reduce_check_end, java_cup.Main.reduce_table, java_cup.emit.start_production, java_cup.Main.start_state, and java_cup.Main.table_end.
Referenced by java_cup.Main.main().
static void java_cup.Main.check_unused () [static, protected]
Check for unused symbols. Unreduced productions get checked when tables are created.
Definition at line 464 of file Main.java.
References java_cup.non_terminal.all(), java_cup.terminal.all(), java_cup.terminal.EOF, java_cup.terminal.error, java_cup.symbol.name(), java_cup.emit.nowarn, java_cup.emit.unused_term, java_cup.symbol.use_count(), and java_cup.lexer.warning_count.
Referenced by java_cup.Main.main().
static void java_cup.Main.close_files () throws java.io.IOException [static, protected]
Close various files used by the system.
Definition at line 420 of file Main.java.
References java_cup.Main.input_file, java_cup.Main.parser_class_file, and java_cup.Main.symbol_class_file.
Referenced by java_cup.Main.main().
static void java_cup.Main.dump_grammar () throws internal_error [static]
Produce a human readable dump of the grammar.
Definition at line 787 of file Main.java.
References java_cup.non_terminal.find(), java_cup.terminal.find(), java_cup.production.find(), java_cup.production_part.is_action(), java_cup.production.lhs(), java_cup.symbol.name(), java_cup.non_terminal.number(), java_cup.terminal.number(), java_cup.production.number(), java_cup.production.rhs(), java_cup.production.rhs_length(), and java_cup.symbol_part.the_symbol().
Referenced by java_cup.Main.main().
static void java_cup.Main.dump_machine () [static]
Produce a (semi-) human readable dump of the complete viable prefix recognition state machine.
Definition at line 829 of file Main.java.
References java_cup.lalr_state.all(), java_cup.lalr_state.index(), java_cup.lalr_state.number(), and java_cup.Main.start_state.
Referenced by java_cup.Main.main().
static void java_cup.Main.dump_tables () [static]
Produce a (semi-) human readable dumps of the parse tables
Definition at line 852 of file Main.java.
References java_cup.Main.action_table, and java_cup.Main.reduce_table.
Referenced by java_cup.Main.main().
static void java_cup.Main.emit_parser () throws internal_error [static, protected]
Call the emit routines necessary to write out the generated parser.
Definition at line 596 of file Main.java.
References java_cup.Main.action_table, java_cup.Main.include_non_terms, java_cup.lalr_state.index(), java_cup.Main.opt_compact_red, java_cup.emit.parser(), java_cup.Main.parser_class_file, java_cup.Main.reduce_table, java_cup.emit.start_production, java_cup.Main.start_state, java_cup.Main.suppress_scanner, java_cup.Main.sym_interface, java_cup.Main.symbol_class_file, and java_cup.emit.symbols().
Referenced by java_cup.Main.main().
static void java_cup.Main.emit_summary (boolean output_produced) [static, protected]
Emit a long summary message to standard error (System.err) which summarizes what was found in the specification, how many states were produced, how many conflicts were found, etc. A detailed timing summary is also produced if it was requested by the user.
Parameters:
output_produced did the system get far enough to generate code.
Definition at line 625 of file Main.java.
References java_cup.lexer.error_count, java_cup.Main.expect_conflicts, java_cup.Main.final_time, java_cup.Main.no_summary, java_cup.emit.not_reduced, java_cup.emit.num_conflicts, java_cup.non_terminal.number(), java_cup.lalr_state.number(), java_cup.terminal.number(), java_cup.production.number(), java_cup.Main.opt_show_timing, java_cup.emit.parser_class_name, java_cup.Main.plural(), java_cup.Main.show_times(), java_cup.emit.symbol_const_class_name, java_cup.version.title_str, java_cup.emit.unused_non_term, java_cup.emit.unused_term, java_cup.version.version_str, and java_cup.lexer.warning_count.
Referenced by java_cup.Main.main().
static void java_cup.Main.main (String argv[]) throws internal_error, java.io.IOException, java.lang.Exception [static]
The main driver for the system.
Parameters:
argv an array of strings containing command line arguments.
Definition at line 154 of file Main.java.
References java_cup.Main.arg_text, java_cup.Main.build_end, java_cup.Main.build_parser(), java_cup.Main.check_end, java_cup.Main.check_unused(), java_cup.Main.close_files(), java_cup.Main.dump_end, java_cup.Main.dump_grammar(), java_cup.Main.dump_machine(), java_cup.Main.dump_tables(), java_cup.Main.emit_end, java_cup.Main.emit_parser(), java_cup.Main.emit_summary(), java_cup.lexer.error_count, java_cup.Main.input_file, java_cup.Main.lr_values, java_cup.Main.no_summary, java_cup.Main.open_files(), java_cup.Main.opt_dump_grammar, java_cup.Main.opt_dump_states, java_cup.Main.opt_dump_tables, java_cup.Main.parse_args(), java_cup.Main.parse_end, java_cup.Main.parse_grammar_spec(), java_cup.Main.prelim_end, java_cup.Main.print_progress, java_cup.emit.set_lr_values(), and java_cup.Main.start_time.
static void java_cup.Main.open_files () [static, protected]
Open various files used by the system.
Definition at line 387 of file Main.java.
References java_cup.Main.parser_class_file, java_cup.emit.parser_class_name, java_cup.Main.symbol_class_file, and java_cup.emit.symbol_const_class_name.
Referenced by java_cup.Main.main().
static void java_cup.Main.parse_args (String argv[]) [static, protected]
Parse command line options and arguments to set various user-option flags and variables.
Parameters:
argv the command line arguments to be parsed.
Definition at line 278 of file Main.java.
References java_cup.Main.arg_text, java_cup.Main.expect_conflicts, java_cup.Main.include_non_terms, java_cup.Main.lr_values, java_cup.Main.no_summary, java_cup.emit.nowarn, java_cup.Main.opt_compact_red, java_cup.Main.opt_do_debug, java_cup.Main.opt_dump_grammar, java_cup.Main.opt_dump_states, java_cup.Main.opt_dump_tables, java_cup.Main.opt_show_timing, java_cup.emit.package_name, java_cup.emit.parser_class_name, java_cup.Main.print_progress, java_cup.Main.suppress_scanner, java_cup.Main.sym_interface, java_cup.emit.symbol_const_class_name, java_cup.version.title_str, and java_cup.Main.usage().
Referenced by java_cup.Main.main().
static void java_cup.Main.parse_grammar_spec () throws java.lang.Exception [static, protected]
Parse the grammar specification from standard input. This produces sets of terminal, non-terminals, and productions which can be accessed via static variables of the respective classes, as well as the setting of various variables (mostly in the emit class) for small user supplied items such as the code to scan with.
Definition at line 435 of file Main.java.
References java_cup.runtime.lr_parser.debug_parse(), java_cup.lexer.emit_error(), java_cup.Main.input_file, java_cup.Main.opt_do_debug, and java_cup.runtime.lr_parser.parse().
Referenced by java_cup.Main.main().
static String java_cup.Main.plural (int val) [static, protected]
Helper routine to optionally return a plural or non-plural ending.
Parameters:
val the numerical value determining plurality.
Definition at line 609 of file Main.java.
Referenced by java_cup.Main.emit_summary().
static void java_cup.Main.show_times () [static, protected]
Produce the optional timing summary as part of an overall summary.
Definition at line 681 of file Main.java.
References java_cup.emit.action_code_time, java_cup.emit.action_table_time, java_cup.Main.build_end, java_cup.Main.check_end, java_cup.Main.dump_end, java_cup.Main.emit_end, java_cup.Main.final_time, java_cup.Main.first_end, java_cup.emit.goto_table_time, java_cup.Main.machine_end, java_cup.Main.nullability_end, java_cup.Main.parse_end, java_cup.emit.parser_time, java_cup.Main.prelim_end, java_cup.emit.production_table_time, java_cup.Main.reduce_check_end, java_cup.Main.start_time, java_cup.emit.symbols_time, java_cup.Main.table_end, and java_cup.Main.timestr().
Referenced by java_cup.Main.emit_summary().
static String java_cup.Main.timestr (long time_val, long total_time) [static, protected]
Helper routine to format a decimal based display of seconds and percentage of total time given counts of milliseconds. Note: this is broken for use with some instances of negative time (since we don't use any negative time here, we let if be for now).
Parameters:
time_val the value being formatted (in ms).
total_time total time percentages are calculated against (in ms).
Definition at line 749 of file Main.java.
Referenced by java_cup.Main.show_times().
static void java_cup.Main.usage (String message) [static, protected]
Print a "usage message" that described possible command line options, then exit.
Parameters:
message a specific error message to preface the usage message by.
Definition at line 241 of file Main.java.
References java_cup.version.program_name.
Referenced by java_cup.Main.parse_args().
Member Data Documentation
parse_action_table java_cup.Main.action_table [static, protected]
Resulting parse action table.
Definition at line 523 of file Main.java.
Referenced by java_cup.Main.build_parser(), java_cup.Main.dump_tables(), and java_cup.Main.emit_parser().
String java_cup.Main.arg_text = "" [static, protected]
Definition at line 143 of file Main.java.
Referenced by java_cup.Main.main(), and java_cup.Main.parse_args().
long java_cup.Main.build_end = 0 [static, protected]
Timing data -- when did we end state and table building
Definition at line 127 of file Main.java.
Referenced by java_cup.Main.main(), and java_cup.Main.show_times().
long java_cup.Main.check_end = 0 [static, protected]
Timing data -- when did we end checking
Definition at line 123 of file Main.java.
Referenced by java_cup.Main.main(), and java_cup.Main.show_times().
long java_cup.Main.dump_end = 0 [static, protected]
Timing data -- when did we end dumping
Definition at line 125 of file Main.java.
Referenced by java_cup.Main.main(), and java_cup.Main.show_times().
long java_cup.Main.emit_end = 0 [static, protected]
Timing data -- when did we finish emitting code
Definition at line 139 of file Main.java.
Referenced by java_cup.Main.main(), and java_cup.Main.show_times().
int java_cup.Main.expect_conflicts = 0 [static, protected]
User option -- number of conflicts to expect
Definition at line 100 of file Main.java.
Referenced by java_cup.Main.build_parser(), java_cup.Main.emit_summary(), and java_cup.Main.parse_args().
long java_cup.Main.final_time = 0 [static, protected]
Timing data -- when were we completely done
Definition at line 141 of file Main.java.
Referenced by java_cup.Main.emit_summary(), and java_cup.Main.show_times().
long java_cup.Main.first_end = 0 [static, protected]
Timing data -- when did we end first set calculation
Definition at line 131 of file Main.java.
Referenced by java_cup.Main.build_parser(), and java_cup.Main.show_times().
boolean java_cup.Main.include_non_terms = false [static, protected]
User option -- should we include non terminal symbol numbers in the symbol constant class.
Definition at line 96 of file Main.java.
Referenced by java_cup.Main.emit_parser(), and java_cup.Main.parse_args().
BufferedInputStream java_cup.Main.input_file [static, protected]
Input file. This is a buffered version of System.in.
Definition at line 376 of file Main.java.
Referenced by java_cup.Main.close_files(), java_cup.Main.main(), and java_cup.Main.parse_grammar_spec().
boolean java_cup.Main.lr_values = true [static, protected]
User option -- should generator generate code for left/right values?
Definition at line 104 of file Main.java.
Referenced by java_cup.Main.main(), and java_cup.Main.parse_args().
long java_cup.Main.machine_end = 0 [static, protected]
Timing data -- when did we end state machine construction
Definition at line 133 of file Main.java.
Referenced by java_cup.Main.build_parser(), and java_cup.Main.show_times().
boolean java_cup.Main.no_summary = false [static, protected]
User option -- do not print a summary.
Definition at line 98 of file Main.java.
Referenced by java_cup.Main.emit_summary(), java_cup.Main.main(), and java_cup.Main.parse_args().
long java_cup.Main.nullability_end = 0 [static, protected]
Timing data -- when did we end nullability calculation
Definition at line 129 of file Main.java.
Referenced by java_cup.Main.build_parser(), and java_cup.Main.show_times().
boolean java_cup.Main.opt_compact_red = false [static, protected]
User option -- do we compact tables by making most common reduce the default action
Definition at line 93 of file Main.java.
Referenced by java_cup.Main.emit_parser(), and java_cup.Main.parse_args().
boolean java_cup.Main.opt_do_debug = false [static, protected]
User option -- do we run produce extra debugging messages
Definition at line 90 of file Main.java.
Referenced by java_cup.Main.build_parser(), java_cup.Main.parse_args(), and java_cup.Main.parse_grammar_spec().
boolean java_cup.Main.opt_dump_grammar = false [static, protected]
User option -- do we produce a dump of the grammar
Definition at line 86 of file Main.java.
Referenced by java_cup.Main.main(), and java_cup.Main.parse_args().
boolean java_cup.Main.opt_dump_states = false [static, protected]
User option -- do we produce a dump of the state machine
Definition at line 82 of file Main.java.
Referenced by java_cup.Main.main(), and java_cup.Main.parse_args().
boolean java_cup.Main.opt_dump_tables = false [static, protected]
User option -- do we produce a dump of the parse tables
Definition at line 84 of file Main.java.
Referenced by java_cup.Main.main(), and java_cup.Main.parse_args().
boolean java_cup.Main.opt_show_timing = false [static, protected]
User option -- do we show timing information as a part of the summary
Definition at line 88 of file Main.java.
Referenced by java_cup.Main.emit_summary(), and java_cup.Main.parse_args().
long java_cup.Main.parse_end = 0 [static, protected]
Timing data -- when did we end parsing
Definition at line 121 of file Main.java.
Referenced by java_cup.Main.main(), and java_cup.Main.show_times().
PrintWriter java_cup.Main.parser_class_file [static, protected]
Output file for the parser class.
Definition at line 379 of file Main.java.
Referenced by java_cup.Main.close_files(), java_cup.Main.emit_parser(), and java_cup.Main.open_files().
long java_cup.Main.prelim_end = 0 [static, protected]
Timing data -- when did we end preliminaries
Definition at line 119 of file Main.java.
Referenced by java_cup.Main.main(), and java_cup.Main.show_times().
boolean java_cup.Main.print_progress = true [static, protected]
User option -- do we print progress messages.
Definition at line 80 of file Main.java.
Referenced by java_cup.Main.build_parser(), java_cup.Main.main(), and java_cup.Main.parse_args().
long java_cup.Main.reduce_check_end = 0 [static, protected]
Timing data -- when did we end checking for non-reduced productions
Definition at line 137 of file Main.java.
Referenced by java_cup.Main.build_parser(), and java_cup.Main.show_times().
parse_reduce_table java_cup.Main.reduce_table [static, protected]
Resulting reduce-goto table.
Definition at line 526 of file Main.java.
Referenced by java_cup.Main.build_parser(), java_cup.Main.dump_tables(), and java_cup.Main.emit_parser().
lalr_state java_cup.Main.start_state [static, protected]
Start state in the overall state machine.
Definition at line 520 of file Main.java.
Referenced by java_cup.Main.build_parser(), java_cup.Main.dump_machine(), and java_cup.Main.emit_parser().
long java_cup.Main.start_time = 0 [static, protected]
Timing data -- when did we start
Definition at line 117 of file Main.java.
Referenced by java_cup.Main.main(), and java_cup.Main.show_times().
boolean java_cup.Main.suppress_scanner = false [static, protected]
User option -- should generator suppress references to java_cup.runtime.Scanner for compatibility with old runtimes?
Definition at line 111 of file Main.java.
Referenced by java_cup.Main.emit_parser(), and java_cup.Main.parse_args().
boolean java_cup.Main.sym_interface = false [static, protected]
User option -- should symbols be put in a class or an interface? [CSA]
Definition at line 107 of file Main.java.
Referenced by java_cup.Main.emit_parser(), and java_cup.Main.parse_args().
PrintWriter java_cup.Main.symbol_class_file [static, protected]
Output file for the symbol constant class.
Definition at line 382 of file Main.java.
Referenced by java_cup.Main.close_files(), java_cup.Main.emit_parser(), and java_cup.Main.open_files().
long java_cup.Main.table_end = 0 [static, protected]
Timing data -- when did we end table construction
Definition at line 135 of file Main.java.
Referenced by java_cup.Main.build_parser(), and java_cup.Main.show_times().
The documentation for this class was generated from the following file:
src/java_cup/Main.java