Jamus Scheme: Scheme.RunEnv Class Reference
Scheme.RunEnv Class Reference
Classes
class EingabeThread
class InterpreterThread
Static Public Member Functions
static void init ()
static StElem interns (String sy)
static void newSymEntry (StElem x)
static ISchemeObject load (ISchemeObject param)
static ISchemeObject open_input_file (ISchemeObject param)
static ISchemeObject open_output_file (ISchemeObject param)
static ISchemeObject close_input_port (ISchemeObject in)
static ISchemeObject close_output_port (ISchemeObject out)
static ISchemeObject read (ISchemeObject in)
static ISchemeObject write (ISchemeObject param)
static ISchemeObject display (ISchemeObject param)
static ISchemeObject newline ()
static ISchemeObject current_input_port ()
static ISchemeObject current_output_port ()
static ISchemeObject set_current_input_port (ISchemeObject new_current_input_port)
static ISchemeObject set_current_output_port (ISchemeObject new_current_output_port)
static void exit ()
static void interpreter_dialog () throws Exception
static void interpreter_file (File textFile) throws Exception
Static Public Attributes
static Stack stack = new Stack(10000)
static ISchemeObject root
Static Package Functions
static int hash (String s, int tableng)
static StElem intern (StElem s)
static ISchemeObject checkbucket (String s, ISchemeObject x)
static void bind (Pair vars, Pair args)
static void bind1 (Symbol var, Pair args)
static void unbind (Pair vars)
static void unbind1 (Symbol var)
Static Package Attributes
static Pair nilval = new Pair()
static ISchemeObject unbound = new Symbol("unbound")
static SchemePort current_input_port = new SchemePort("stdin")
static SchemePort current_output_port = new SchemePort("stdout")
static EingabeThread et = new EingabeThread()
static InterpreterThread it = new InterpreterThread()
static int interpreter_modus
static boolean read_status = false
static int number_read_call_temp
static int number_read_data_temp
static ISchemeObject read_object
static SchemeBoolean bTrue
static SchemeBoolean bFalse
static final int tableng = 31
static ISchemeObject[] hashtab = new ISchemeObject[tableng]
Detailed Description
Definition at line 19 of file RunEnv.java.
Member Function Documentation
static void Scheme.RunEnv.bind (Pair vars, Pair args) [static, package]
Definition at line 458 of file RunEnv.java.
References Scheme.Pair.car, Scheme.Pair.cdr, Scheme.ISchemeObject.cons(), Scheme.Pair.nullp(), Scheme.Stack.push(), Scheme.RunEnv.stack, and Scheme.RunEnv.unbound.
Referenced by Scheme.Pair.apply().
static void Scheme.RunEnv.bind1 (Symbol var, Pair args) [static, package]
Definition at line 477 of file RunEnv.java.
References Scheme.ISchemeObject.cons(), Scheme.Stack.push(), Scheme.RunEnv.stack, and Scheme.RunEnv.unbound.
Referenced by Scheme.Pair.apply().
static ISchemeObject Scheme.RunEnv.checkbucket (String s, ISchemeObject x) [static, package]
Definition at line 176 of file RunEnv.java.
References Scheme.ISchemeObject.nullp().
Referenced by Scheme.$actions.$do_action(), Scheme.RunEnv.intern(), Scheme.RunEnv.interns(), and Scheme.SchemeString.stringsymbol().
static ISchemeObject Scheme.RunEnv.close_input_port (ISchemeObject in) [static]
Definition at line 601 of file RunEnv.java.
References Scheme.RunEnv.nilval, Scheme.SchemePort.open_buffer_reader, Scheme.SchemePort.open_file_reader, and Scheme.SchemePort.port_description.
static ISchemeObject Scheme.RunEnv.close_output_port (ISchemeObject out) [static]
Definition at line 624 of file RunEnv.java.
References Scheme.RunEnv.nilval, Scheme.SchemePort.open_buffer_writer, Scheme.SchemePort.open_file_writer, and Scheme.SchemePort.port_description.
static ISchemeObject Scheme.RunEnv.current_input_port () [static]
Definition at line 776 of file RunEnv.java.
Referenced by Scheme.RunEnv.set_current_input_port().
static ISchemeObject Scheme.RunEnv.current_output_port () [static]
Definition at line 781 of file RunEnv.java.
Referenced by Scheme.RunEnv.display(), Scheme.RunEnv.newline(), Scheme.RunEnv.set_current_output_port(), and Scheme.RunEnv.write().
static ISchemeObject Scheme.RunEnv.display (ISchemeObject param) [static]
Definition at line 725 of file RunEnv.java.
References Scheme.RunEnv.current_output_port(), Scheme.RunEnv.nilval, Scheme.SchemeString.print(), Scheme.ISchemeObject.print(), Scheme.SchemeString.printp(), Scheme.ISchemeObject.printp(), and Scheme.SchemeString.value.
static void Scheme.RunEnv.exit () [static]
Definition at line 810 of file RunEnv.java.
References Scheme.RunEnv.et, Scheme.RunEnv.interpreter_modus, and Scheme.RunEnv.EingabeThread.run_interpreter.
static int Scheme.RunEnv.hash (String s, int tableng) [static, package]
Definition at line 48 of file RunEnv.java.
Referenced by Scheme.$actions.$do_action(), Scheme.RunEnv.intern(), Scheme.RunEnv.interns(), and Scheme.SchemeString.stringsymbol().
static void Scheme.RunEnv.init () [static]
Definition at line 60 of file RunEnv.java.
References Scheme.RunEnv.newSymEntry().
Referenced by Scheme.TestTdgs.main(), Scheme.UseTdgs.main(), and Scheme.UseScheme.main().
static StElem Scheme.RunEnv.intern (StElem s) [static, package]
Definition at line 134 of file RunEnv.java.
References Scheme.RunEnv.checkbucket(), Scheme.Pair.cons(), Scheme.ISchemeObject.cons(), Scheme.StElem.getPname(), Scheme.RunEnv.hash(), Scheme.RunEnv.hashtab, Scheme.RunEnv.nilval, Scheme.ISchemeObject.nullp(), and Scheme.RunEnv.tableng.
Referenced by Scheme.RunEnv.newSymEntry().
static StElem Scheme.RunEnv.interns (String sy) [static]
Definition at line 153 of file RunEnv.java.
References Scheme.RunEnv.checkbucket(), Scheme.RunEnv.hash(), Scheme.RunEnv.hashtab, and Scheme.RunEnv.nilval.
Referenced by Scheme.$actions.$do_action(), Scheme.Pair.closure(), Scheme.Pair.condexp(), Scheme.Pair.eval(), Scheme.Pair.expand(), Scheme.Pair.expand2(), Scheme.Pair.fc2(), Scheme.Pair.lettwo(), Scheme.Pair.searchgb(), and Scheme.Pair.settwo().
static void Scheme.RunEnv.interpreter_dialog () throws Exception [static]
Definition at line 905 of file RunEnv.java.
References Scheme.RunEnv.et, Scheme.RunEnv.interpreter_modus, and Scheme.RunEnv.it.
Referenced by Scheme.UseScheme.main().
static void Scheme.RunEnv.interpreter_file (File textFile) throws Exception [static]
Definition at line 913 of file RunEnv.java.
References Scheme.RunEnv.interpreter_modus, and java_cup.runtime.lr_parser.parse().
Referenced by Scheme.TestTdgs.main(), Scheme.UseTdgs.main(), and Scheme.UseScheme.main().
static ISchemeObject Scheme.RunEnv.load (ISchemeObject param) [static]
Definition at line 531 of file RunEnv.java.
References Scheme.RunEnv.nilval, java_cup.runtime.lr_parser.parse(), and Scheme.SchemeString.value.
static ISchemeObject Scheme.RunEnv.newline () [static]
Definition at line 760 of file RunEnv.java.
References Scheme.RunEnv.current_output_port(), Scheme.Pair.newline(), and Scheme.RunEnv.nilval.
static void Scheme.RunEnv.newSymEntry (StElem x) [static]
Definition at line 187 of file RunEnv.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, Scheme.StElem.getPname(), Scheme.RunEnv.intern(), Scheme.StElem.setMode(), and Scheme.StElem.setValue().
Referenced by Scheme.RunEnv.init().
static ISchemeObject Scheme.RunEnv.open_input_file (ISchemeObject param) [static]
Definition at line 551 of file RunEnv.java.
References Scheme.RunEnv.nilval, and Scheme.SchemeString.value.
static ISchemeObject Scheme.RunEnv.open_output_file (ISchemeObject param) [static]
Definition at line 576 of file RunEnv.java.
References Scheme.RunEnv.nilval, and Scheme.SchemeString.value.
static ISchemeObject Scheme.RunEnv.read (ISchemeObject in) [static]
Definition at line 648 of file RunEnv.java.
References Scheme.SchemePort.number_read_call, Scheme.RunEnv.number_read_call_temp, Scheme.SchemePort.number_read_data, Scheme.RunEnv.number_read_data_temp, Scheme.SchemePort.open_buffer_reader, Scheme.SchemePort.open_file_reader, java_cup.runtime.lr_parser.parse(), Scheme.SchemePort.port_description, Scheme.RunEnv.read_object, Scheme.RunEnv.read_status, and Scheme.SchemePort.resetBufferedReader().
static ISchemeObject Scheme.RunEnv.set_current_input_port (ISchemeObject new_current_input_port) [static]
Definition at line 785 of file RunEnv.java.
References Scheme.RunEnv.current_input_port(), and Scheme.RunEnv.nilval.
static ISchemeObject Scheme.RunEnv.set_current_output_port (ISchemeObject new_current_output_port) [static]
Definition at line 792 of file RunEnv.java.
References Scheme.RunEnv.current_output_port(), and Scheme.RunEnv.nilval.
static void Scheme.RunEnv.unbind (Pair vars) [static, package]
Definition at line 489 of file RunEnv.java.
References Scheme.Pair.cdr, Scheme.Pair.nullp(), Scheme.Stack.pop(), Scheme.RunEnv.stack, Scheme.Stack.top(), and Scheme.RunEnv.unbound.
Referenced by Scheme.Pair.apply().
static void Scheme.RunEnv.unbind1 (Symbol var) [static, package]
Definition at line 512 of file RunEnv.java.
References Scheme.Stack.pop(), Scheme.RunEnv.stack, Scheme.Stack.top(), and Scheme.RunEnv.unbound.
Referenced by Scheme.Pair.apply().
static ISchemeObject Scheme.RunEnv.write (ISchemeObject param) [static]
Definition at line 711 of file RunEnv.java.
References Scheme.RunEnv.current_output_port(), Scheme.RunEnv.nilval, Scheme.ISchemeObject.print(), and Scheme.ISchemeObject.printp().
Referenced by Scheme.Pair.write().
Member Data Documentation
SchemeBoolean Scheme.RunEnv.bFalse [static, package]
Definition at line 43 of file RunEnv.java.
Referenced by Scheme.$actions.$do_action(), Scheme.Pair.andexp(), Scheme.Pair.apply(), Scheme.Pair.assoc(), Scheme.Pair.eq(), Scheme.SchemeNumber.eqp(), Scheme.SchemeDouble.eqp(), Scheme.Pair.eqp(), Scheme.SchemeString.eqp(), Scheme.SchemeInteger.eqp(), Scheme.SchemeObject.eqp(), Scheme.SchemeNumber.equalp(), Scheme.Pair.equalp(), Scheme.SchemeDouble.equalp(), Scheme.SchemeInteger.equalp(), Scheme.SchemeObject.equalp(), Scheme.SchemeString.equalp(), Scheme.Pair.eval(), Scheme.Pair.expand(), Scheme.Pair.gt(), Scheme.SchemeDouble.integerp(), Scheme.Pair.listp(), Scheme.Pair.lt(), Scheme.SchemeNumber.negativep(), Scheme.SchemeDouble.negativep(), Scheme.SchemeInteger.negativep(), Scheme.RunEnv.newSymEntry(), Scheme.SchemeBoolean.not(), Scheme.Pair.not(), Scheme.Pair.nullpp(), Scheme.Pair.orexp(), Scheme.Pair.pairp(), Scheme.SchemeNumber.positivep(), Scheme.SchemeDouble.positivep(), Scheme.SchemeInteger.positivep(), Scheme.SchemeString.stringle(), Scheme.Symbol.stringle(), Scheme.Pair.stringle(), Scheme.Pair.symbolp(), Scheme.SchemeNumber.zerop(), Scheme.SchemeDouble.zerop(), Scheme.SchemeInteger.zerop(), and Scheme.Pair.zerop().
SchemeBoolean Scheme.RunEnv.bTrue [static, package]
Definition at line 42 of file RunEnv.java.
Referenced by Scheme.$actions.$do_action(), Scheme.Pair.andexp(), Scheme.Pair.apply(), Scheme.Pair.assoc(), Scheme.Pair.condexp(), Scheme.Pair.eq(), Scheme.SchemeNumber.eqp(), Scheme.Pair.eqp(), Scheme.SchemeDouble.eqp(), Scheme.SchemeString.eqp(), Scheme.SchemeInteger.eqp(), Scheme.SchemeObject.eqp(), Scheme.SchemeNumber.equalp(), Scheme.Pair.equalp(), Scheme.SchemeDouble.equalp(), Scheme.SchemeInteger.equalp(), Scheme.SchemeObject.equalp(), Scheme.SchemeString.equalp(), Scheme.Pair.eval(), Scheme.Pair.expand(), Scheme.Pair.gt(), Scheme.SchemeDouble.integerp(), Scheme.SchemeInteger.integerp(), Scheme.Pair.listp(), Scheme.Pair.lt(), Scheme.Pair.member(), Scheme.SchemeNumber.negativep(), Scheme.SchemeDouble.negativep(), Scheme.SchemeInteger.negativep(), Scheme.RunEnv.newSymEntry(), Scheme.SchemeBoolean.not(), Scheme.Pair.not(), Scheme.Pair.nullpp(), Scheme.SchemeNumber.numberp(), Scheme.SchemeDouble.numberp(), Scheme.SchemeInteger.numberp(), Scheme.Pair.orexp(), Scheme.Pair.pairp(), Scheme.SchemeNumber.positivep(), Scheme.SchemeDouble.positivep(), Scheme.SchemeInteger.positivep(), Scheme.SchemeDouble.realp(), Scheme.SchemeString.stringle(), Scheme.Symbol.stringle(), Scheme.Pair.stringle(), Scheme.Symbol.symbolp(), Scheme.Pair.vundef(), Scheme.SchemeNumber.zerop(), Scheme.SchemeDouble.zerop(), and Scheme.SchemeInteger.zerop().
SchemePort Scheme.RunEnv.current_input_port = new SchemePort("stdin") [static, package]
Definition at line 26 of file RunEnv.java.
SchemePort Scheme.RunEnv.current_output_port = new SchemePort("stdout") [static, package]
Definition at line 27 of file RunEnv.java.
EingabeThread Scheme.RunEnv.et = new EingabeThread() [static, package]
Definition at line 29 of file RunEnv.java.
Referenced by Scheme.RunEnv.exit(), Scheme.RunEnv.interpreter_dialog(), and Scheme.RunEnv.InterpreterThread.run().
ISchemeObject [] Scheme.RunEnv.hashtab = new ISchemeObject[tableng] [static, package]
Definition at line 46 of file RunEnv.java.
Referenced by Scheme.$actions.$do_action(), Scheme.RunEnv.intern(), Scheme.RunEnv.interns(), and Scheme.SchemeString.stringsymbol().
int Scheme.RunEnv.interpreter_modus [static, package]
Definition at line 32 of file RunEnv.java.
Referenced by Scheme.RunEnv.exit(), Scheme.RunEnv.interpreter_dialog(), and Scheme.RunEnv.interpreter_file().
InterpreterThread Scheme.RunEnv.it = new InterpreterThread() [static, package]
Definition at line 30 of file RunEnv.java.
Referenced by Scheme.RunEnv.interpreter_dialog().
Pair Scheme.RunEnv.nilval = new Pair() [static, package]
Definition at line 23 of file RunEnv.java.
Referenced by Scheme.$actions.$do_action(), Scheme.Pair.apply(), Scheme.Pair.assoc(), Scheme.RunEnv.close_input_port(), Scheme.RunEnv.close_output_port(), Scheme.Pair.closure(), Scheme.Pair.condexp(), Scheme.RunEnv.display(), Scheme.StElem.eval(), Scheme.Pair.eval(), Scheme.Pair.expand(), Scheme.Pair.expand2(), Scheme.Pair.expandall(), Scheme.Pair.expandlist(), Scheme.Pair.fc2(), Scheme.Pair.initlist(), Scheme.RunEnv.intern(), Scheme.RunEnv.interns(), Scheme.Pair.lettwo(), Scheme.RunEnv.load(), Scheme.Pair.member(), Scheme.RunEnv.newline(), Scheme.Pair.newline(), Scheme.RunEnv.open_input_file(), Scheme.RunEnv.open_output_file(), Scheme.Symbol.printp(), Scheme.SchemeNumber.printp(), Scheme.SchemeInteger.printp(), Scheme.SchemeDouble.printp(), Scheme.SchemeFunction.printp(), Scheme.SchemeString.printp(), Scheme.SchemePort.printp(), Scheme.StElem.printp(), Scheme.Pair.printp(), Scheme.Pair.remdup(), Scheme.Pair.remdup2(), Scheme.Pair.remove(), Scheme.Pair.reverse(), Scheme.Pair.searchb(), Scheme.Pair.searchgb(), Scheme.Pair.searchv(), Scheme.RunEnv.set_current_input_port(), Scheme.RunEnv.set_current_output_port(), Scheme.Pair.settwo(), Scheme.Pair.steplist(), Scheme.SchemeString.stringsymbol(), Scheme.Pair.ubvcdr(), Scheme.Pair.varlist(), Scheme.Pair.vl(), Scheme.Pair.vn(), Scheme.Pair.vundef(), Scheme.RunEnv.write(), and Scheme.Pair.write().
int Scheme.RunEnv.number_read_call_temp [static, package]
Definition at line 35 of file RunEnv.java.
Referenced by Scheme.Pair.eval(), and Scheme.RunEnv.read().
int Scheme.RunEnv.number_read_data_temp [static, package]
Definition at line 36 of file RunEnv.java.
Referenced by Scheme.Pair.eval(), and Scheme.RunEnv.read().
ISchemeObject Scheme.RunEnv.read_object [static, package]
Definition at line 38 of file RunEnv.java.
Referenced by Scheme.Pair.eval(), and Scheme.RunEnv.read().
boolean Scheme.RunEnv.read_status = false [static, package]
Definition at line 34 of file RunEnv.java.
Referenced by Scheme.Pair.eval(), and Scheme.RunEnv.read().
ISchemeObject Scheme.RunEnv.root [static]
Definition at line 40 of file RunEnv.java.
Referenced by Scheme.$actions.$do_action(), Scheme.Pair.eval(), Scheme.TestTdgs.main(), and Scheme.UseTdgs.main().
Stack Scheme.RunEnv.stack = new Stack(10000) [static]
Definition at line 21 of file RunEnv.java.
Referenced by Scheme.RunEnv.bind(), Scheme.RunEnv.bind1(), Scheme.Pair.eval(), Scheme.RunEnv.unbind(), and Scheme.RunEnv.unbind1().
final int Scheme.RunEnv.tableng = 31 [static, package]
Definition at line 45 of file RunEnv.java.
Referenced by Scheme.RunEnv.intern().
ISchemeObject Scheme.RunEnv.unbound = new Symbol("unbound") [static, package]
Definition at line 24 of file RunEnv.java.
Referenced by Scheme.RunEnv.bind(), Scheme.RunEnv.bind1(), Scheme.StElem.eval(), Scheme.Pair.eval(), Scheme.Pair.searchgb(), Scheme.RunEnv.unbind(), and Scheme.RunEnv.unbind1().
The documentation for this class was generated from the following file:
src/Scheme/RunEnv.java