Jamus Scheme: Scheme.$actions Class Reference
Scheme.$actions Class Reference
Public Member Functions
final java_cup.runtime.Symbol
CUP $parser $do_action (int CUP $parser $act_num, java_cup.runtime.lr_parser CUP $parser $parser, java.util.Stack CUP $parser $stack, int CUP $parser $top) throws java.lang.Exception
Package Functions
CUP $parser $actions (parser parser)
Private Attributes
final parser parser
Detailed Description
Cup generated class to encapsulate user supplied action code.
Definition at line 210 of file parser.java.
Constructor & Destructor Documentation
CUP $parser Scheme.$actions.$actions (parser parser) [package]
Constructor
Definition at line 214 of file parser.java.
Member Function Documentation
final java_cup.runtime.Symbol CUP $parser Scheme.$actions.$do_action (int CUP $parser $ act_num, java_cup.runtime.lr_parser CUP $parser $ parser, java.util.Stack CUP $parser $ stack, int CUP $parser $ top) throws java.lang.Exception
Method with the actual generated action code.
Definition at line 219 of file parser.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, Scheme.RunEnv.checkbucket(), Scheme.RunEnv.hash(), Scheme.RunEnv.hashtab, Scheme.RunEnv.interns(), Scheme.RunEnv.nilval, Scheme.ISchemeObject.print(), Scheme.RunEnv.root, and java_cup.runtime.Symbol.Symbol().
Member Data Documentation
final parser Scheme.$actions.parser [private]
Definition at line 211 of file parser.java.
The documentation for this class was generated from the following file:
src/Scheme/parser.java