Jamus Scheme: java_cup.terminal_set Class Reference
java_cup.terminal_set Class Reference
Public Member Functions
terminal_set ()
terminal_set (terminal_set other) throws internal_error
boolean empty ()
boolean contains (terminal sym) throws internal_error
boolean contains (int indx)
boolean is_subset_of (terminal_set other) throws internal_error
boolean is_superset_of (terminal_set other) throws internal_error
boolean add (terminal sym) throws internal_error
void remove (terminal sym) throws internal_error
boolean add (terminal_set other) throws internal_error
boolean intersects (terminal_set other) throws internal_error
boolean equals (terminal_set other)
boolean equals (Object other)
String toString ()
Static Public Attributes
static final terminal_set EMPTY = new terminal_set()
Protected Member Functions
void not_null (Object obj) throws internal_error
Protected Attributes
BitSet _elements
Detailed Description
A set of terminals implemented as a bitset.
Version:
last updated: 11/25/95
Author:
Scott Hudson
Definition at line 10 of file terminal_set.java.
Constructor & Destructor Documentation
java_cup.terminal_set.terminal_set ()
Constructor for an empty set.
Definition at line 17 of file terminal_set.java.
References java_cup.terminal_set._elements, and java_cup.terminal.number().
java_cup.terminal_set.terminal_set (terminal_set other) throws internal_error
Constructor for cloning from another set.
Parameters:
other the set we are cloning from.
Definition at line 28 of file terminal_set.java.
References java_cup.terminal_set._elements, and java_cup.terminal_set.not_null().
Member Function Documentation
boolean java_cup.terminal_set.add (terminal sym) throws internal_error
Add a single terminal to the set.
Parameters:
sym the terminal being added.
Returns:
true if this changes the set.
Definition at line 131 of file terminal_set.java.
References java_cup.terminal_set._elements, and java_cup.terminal_set.not_null().
Referenced by java_cup.lalr_item_set.add(), java_cup.lalr_state.build_machine(), java_cup.lalr_state.build_table_entries(), java_cup.lalr_item.calc_lookahead(), java_cup.production.check_first_set(), java_cup.non_terminal.compute_first_sets(), and java_cup.lalr_item.propagate_lookaheads().
boolean java_cup.terminal_set.add (terminal_set other) throws internal_error
Add (union) in a complete set.
Parameters:
other the set being added.
Returns:
true if this changes the set.
Definition at line 166 of file terminal_set.java.
References java_cup.terminal_set._elements, and java_cup.terminal_set.not_null().
boolean java_cup.terminal_set.contains (terminal sym) throws internal_error
Determine if the set contains a particular terminal.
Parameters:
sym the terminal symbol we are looking for.
Definition at line 76 of file terminal_set.java.
References java_cup.terminal_set._elements, and java_cup.terminal_set.not_null().
Referenced by java_cup.lalr_state.build_table_entries(), and java_cup.lalr_item.toString().
boolean java_cup.terminal_set.contains (int indx)
Given its index determine if the set contains a particular terminal.
Parameters:
indx the index of the terminal in question.
Definition at line 88 of file terminal_set.java.
References java_cup.terminal_set._elements.
boolean java_cup.terminal_set.empty ()
Determine if the set is empty.
Definition at line 66 of file terminal_set.java.
References java_cup.terminal_set.EMPTY, and java_cup.terminal_set.equals().
Referenced by java_cup.lalr_state.build_table_entries().
boolean java_cup.terminal_set.equals (terminal_set other)
Equality comparison.
Definition at line 204 of file terminal_set.java.
References java_cup.terminal_set._elements.
Referenced by java_cup.terminal_set.empty(), and java_cup.terminal_set.equals().
boolean java_cup.terminal_set.equals (Object other)
Generic equality comparison.
Definition at line 215 of file terminal_set.java.
References java_cup.terminal_set.equals().
boolean java_cup.terminal_set.intersects (terminal_set other) throws internal_error
Determine if this set intersects another.
Parameters:
other the other set in question.
Definition at line 186 of file terminal_set.java.
References java_cup.terminal_set._elements, and java_cup.terminal_set.not_null().
Referenced by java_cup.lalr_state.report_conflicts().
boolean java_cup.terminal_set.is_subset_of (terminal_set other) throws internal_error
Determine if this set is an (improper) subset of another.
Parameters:
other the set we are testing against.
Definition at line 98 of file terminal_set.java.
References java_cup.terminal_set._elements, and java_cup.terminal_set.not_null().
Referenced by java_cup.non_terminal.compute_first_sets().
boolean java_cup.terminal_set.is_superset_of (terminal_set other) throws internal_error
Determine if this set is an (improper) superset of another.
Parameters:
other the set we are testing against.
Definition at line 118 of file terminal_set.java.
References java_cup.terminal_set.not_null().
void java_cup.terminal_set.not_null (Object obj) throws internal_error [protected]
Helper function to test for a null object and throw an exception if one is found.
Parameters:
obj the object we are testing.
Definition at line 57 of file terminal_set.java.
Referenced by java_cup.terminal_set.add(), java_cup.terminal_set.contains(), java_cup.terminal_set.intersects(), java_cup.terminal_set.is_subset_of(), java_cup.terminal_set.is_superset_of(), java_cup.terminal_set.remove(), and java_cup.terminal_set.terminal_set().
void java_cup.terminal_set.remove (terminal sym) throws internal_error
Remove a terminal if it is in the set.
Parameters:
sym the terminal being removed.
Definition at line 153 of file terminal_set.java.
References java_cup.terminal_set._elements, and java_cup.terminal_set.not_null().
String java_cup.terminal_set.toString ()
Convert to string.
Definition at line 226 of file terminal_set.java.
References java_cup.terminal_set._elements, java_cup.terminal.find(), java_cup.symbol.name(), and java_cup.terminal.number().
Member Data Documentation
BitSet java_cup.terminal_set._elements [protected]
Bitset to implement the actual set.
Definition at line 47 of file terminal_set.java.
Referenced by java_cup.terminal_set.add(), java_cup.terminal_set.contains(), java_cup.terminal_set.equals(), java_cup.terminal_set.intersects(), java_cup.terminal_set.is_subset_of(), java_cup.terminal_set.remove(), java_cup.terminal_set.terminal_set(), and java_cup.terminal_set.toString().
final terminal_set java_cup.terminal_set.EMPTY = new terminal_set() [static]
Constant for the empty set.
Definition at line 40 of file terminal_set.java.
Referenced by java_cup.terminal_set.empty().
The documentation for this class was generated from the following file:
src/java_cup/terminal_set.java