Jamus Scheme: Scheme.Pair Class Reference
Scheme.Pair Class Reference
Public Member Functions
Pair ()
Pair (SchemeObject carp, SchemeObject cdrp)
Pair cons (SchemeObject e)
SchemeBoolean eqp (SchemeObject o)
SchemeBoolean equalp (SchemeObject o)
Pair append (Pair l)
Pair member (SchemeObject e)
Pair remove (SchemeObject e)
Pair reverse ()
Pair assoc (SchemeObject e)
Pair remdup (Pair l)
SchemeObject car ()
SchemeObject cdr ()
SchemeObject caar ()
SchemeObject cadr ()
SchemeObject cddr ()
SchemeObject cdar ()
Pair rplaca (SchemeObject x)
Pair rplacd (SchemeObject x)
Pair list ()
boolean nullp ()
SchemeBoolean pairp ()
SchemeBoolean symbolp ()
SchemeBoolean zerop ()
SchemeBoolean not ()
SchemeNumber iplus ()
SchemeNumber itimes ()
SchemeBoolean eq ()
SchemeBoolean lt ()
SchemeBoolean gt ()
SchemeNumber iminus ()
SchemeNumber idivision ()
SchemeNumber iexpt ()
Pair closure ()
Pair ubvcdr ()
Pair remlocallambdas (Pair frees)
SchemeObject apply (SchemeObject op)
Pair expandlist ()
SchemeObject expand ()
Pair expand2 (String part1, String part2)
SchemeObject andexp ()
SchemeObject orexp ()
Pair condexp ()
Pair vn ()
Pair vl ()
Pair lettwo ()
Pair settwo ()
Pair vundef ()
Pair initlist ()
SchemeObject evlis (Pair l)
SchemeObject eval ()
void treeeval (boolean trace)
SchemeObject write ()
void print ()
void printlist ()
Pair ()
Pair (ISchemeObject carp, ISchemeObject cdrp)
SchemeBoolean equalp (ISchemeObject o)
Pair append (Pair l)
Pair member (ISchemeObject e)
Pair remove (ISchemeObject e)
Pair reverse ()
ISchemeObject assoc (ISchemeObject e)
Pair remdup (Pair l)
Pair remdup2 (Symbol l)
ISchemeObject car ()
ISchemeObject cdr ()
ISchemeObject caar ()
ISchemeObject cadr ()
ISchemeObject cddr ()
ISchemeObject cdar ()
Pair rplaca (ISchemeObject x)
Pair setcar (ISchemeObject x)
Pair rplacd (ISchemeObject x)
Pair setcdr (ISchemeObject x)
Pair list ()
boolean nullp ()
SchemeBoolean nullpp ()
SchemeBoolean pairp ()
SchemeBoolean listp ()
SchemeBoolean not ()
SchemeNumber iplus ()
SchemeNumber itimes ()
SchemeBoolean eq ()
SchemeBoolean lt ()
SchemeBoolean gt ()
SchemeString stringappend (SchemeString s)
SchemeBoolean stringle ()
SchemeNumber iminus ()
SchemeNumber idivision ()
SchemeNumber iexpt ()
SchemeNumber quotient ()
SchemeNumber remainder ()
SchemeNumber min ()
SchemeNumber max ()
SchemeNumber length ()
SchemeNumber abs ()
SchemeNumber exactinexact ()
SchemeNumber inexactexact ()
Pair closure ()
Pair ubvcdr ()
Pair remlocallambdas (Pair frees)
Pair removel (Pair li)
ISchemeObject apply (ISchemeObject op)
ISchemeObject expandall ()
Pair expandlist ()
ISchemeObject expand ()
Pair expand2 (String part1, String part2)
ISchemeObject orexp ()
Pair condexp ()
Pair vn ()
Pair vl ()
Pair lettwo ()
Pair settwo ()
Pair vundef ()
Pair initlist ()
Pair varlist ()
Pair steplist ()
ISchemeObject evlis (Pair l)
ISchemeObject eval ()
void treeeval (boolean trace)
ISchemeObject write ()
ISchemeObject printp (BufferedWriter open_buffer_writer)
void printplist (BufferedWriter open_buffer_writer)
void print ()
void printlist ()
ISchemeObject newline ()
Static Public Member Functions
static ISchemeObject quasiquote (ISchemeObject e)
Package Attributes
SchemeObject car
SchemeObject cdr
ISchemeObject car
ISchemeObject cdr
Static Package Attributes
static boolean closurestatus = false
static Symbol definesym
Private Member Functions
Pair fc2 (Pair fvars, Pair befarg)
void fc3 (Pair fvars, Pair l)
Pair fv (Pair vars, Pair body)
SchemeObject searchv (SchemeObject l)
Pair searchgb ()
Pair searchb (Stack s)
Pair fc2 (Pair fvars, Pair befarg)
void fc3 (Pair fvars, Pair l)
Pair fv (Pair vars, Pair body)
Pair fv2 (Symbol var, Pair body)
Pair remfunctions (Pair vars)
ISchemeObject searchv (ISchemeObject l)
Pair searchgb ()
Pair searchb (Stack s)
Detailed Description
Class Pair in Scheme.
Definition at line 5 of file Pair1.java.
Constructor & Destructor Documentation
Scheme.Pair.Pair ()
Definition at line 11 of file Pair1.java.
Referenced by Scheme.Pair.assoc(), Scheme.Pair.closure(), Scheme.Pair.cons(), Scheme.Pair.eq(), Scheme.Pair.equalp(), Scheme.Pair.gt(), Scheme.Pair.idivision(), Scheme.Pair.iexpt(), Scheme.Pair.iminus(), Scheme.Pair.iplus(), Scheme.Pair.itimes(), Scheme.Pair.length(), Scheme.Pair.lt(), Scheme.Pair.max(), Scheme.Pair.min(), Scheme.Pair.quotient(), Scheme.Pair.remainder(), and Scheme.Pair.stringle().
Scheme.Pair.Pair (SchemeObject carp, SchemeObject cdrp)
Definition at line 14 of file Pair1.java.
References Scheme.Pair.car(), and Scheme.Pair.cdr().
Scheme.Pair.Pair ()
Definition at line 15 of file Pair.java.
References Scheme.Pair.car(), and Scheme.Pair.cdr().
Scheme.Pair.Pair (ISchemeObject carp, ISchemeObject cdrp)
Definition at line 20 of file Pair.java.
References Scheme.Pair.car(), and Scheme.Pair.cdr().
Member Function Documentation
SchemeNumber Scheme.Pair.abs ()
Definition at line 820 of file Pair.java.
References Scheme.Pair.car(), and Scheme.Pair.nullp().
SchemeObject Scheme.Pair.andexp ()
Definition at line 766 of file Pair1.java.
References Scheme.Pair.andexp(), Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, and Scheme.Pair.cdr.
Referenced by Scheme.Pair.andexp(), and Scheme.Pair.expand().
Pair Scheme.Pair.append (Pair l)
Definition at line 46 of file Pair1.java.
References Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.cons(), and Scheme.Pair.nullp().
Referenced by Scheme.Pair.append(), Scheme.Pair.closure(), and Scheme.Pair.reverse().
Pair Scheme.Pair.append (Pair l)
Definition at line 50 of file Pair.java.
References Scheme.Pair.append(), Scheme.Pair.car(), Scheme.Pair.cdr(), and Scheme.Pair.nullp().
SchemeObject Scheme.Pair.apply (SchemeObject op)
Definition at line 500 of file Pair1.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bind(), Scheme.RunEnv.bTrue, Scheme.Pair.car, Scheme.Pair.cdr, Scheme.Pair.closurestatus, Scheme.SchemeObject.eval(), Scheme.RunEnv.nilval, Scheme.Pair.nullp(), and Scheme.RunEnv.unbind().
Referenced by Scheme.Pair.eval().
ISchemeObject Scheme.Pair.apply (ISchemeObject op)
Definition at line 1109 of file Pair.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bind(), Scheme.RunEnv.bind1(), Scheme.RunEnv.bTrue, Scheme.Pair.closurestatus, Scheme.ISchemeObject.eval(), Scheme.RunEnv.nilval, Scheme.RunEnv.unbind(), and Scheme.RunEnv.unbind1().
Pair Scheme.Pair.assoc (SchemeObject e)
Definition at line 81 of file Pair1.java.
References Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.RunEnv.nilval, and Scheme.Pair.nullp().
ISchemeObject Scheme.Pair.assoc (ISchemeObject e)
Definition at line 113 of file Pair.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.SchemeObject.equalp(), Scheme.Pair.nullp(), and Scheme.Pair.Pair().
SchemeObject Scheme.Pair.caar ()
Definition at line 112 of file Pair1.java.
References Scheme.Pair.car().
ISchemeObject Scheme.Pair.caar ()
Definition at line 155 of file Pair.java.
References Scheme.Pair.car().
SchemeObject Scheme.Pair.cadr ()
Definition at line 116 of file Pair1.java.
References Scheme.Pair.cdr().
ISchemeObject Scheme.Pair.cadr ()
Definition at line 159 of file Pair.java.
References Scheme.Pair.cdr().
SchemeObject Scheme.Pair.car ()
Definition at line 104 of file Pair1.java.
Referenced by Scheme.Pair.abs(), Scheme.Pair.append(), Scheme.Pair.assoc(), Scheme.Pair.caar(), Scheme.Pair.car(), Scheme.Pair.cdar(), Scheme.Pair.closure(), Scheme.Pair.eq(), Scheme.Pair.equalp(), Scheme.Pair.exactinexact(), Scheme.Pair.gt(), Scheme.Pair.idivision(), Scheme.Pair.iexpt(), Scheme.Pair.iminus(), Scheme.Pair.inexactexact(), Scheme.Pair.length(), Scheme.Pair.listp(), Scheme.Pair.lt(), Scheme.Pair.max(), Scheme.Pair.member(), Scheme.Pair.min(), Scheme.Pair.not(), Scheme.Pair.nullp(), Scheme.Pair.nullpp(), Scheme.Pair.Pair(), Scheme.Pair.pairp(), Scheme.Pair.quotient(), Scheme.Pair.remainder(), Scheme.Pair.remdup(), Scheme.Pair.remdup2(), Scheme.Pair.remove(), Scheme.Pair.rplaca(), Scheme.Pair.setcar(), and Scheme.Pair.stringle().
ISchemeObject Scheme.Pair.car ()
Definition at line 147 of file Pair.java.
References Scheme.Pair.car().
SchemeObject Scheme.Pair.cdar ()
Definition at line 124 of file Pair1.java.
References Scheme.Pair.car().
ISchemeObject Scheme.Pair.cdar ()
Definition at line 167 of file Pair.java.
References Scheme.Pair.car().
SchemeObject Scheme.Pair.cddr ()
Definition at line 120 of file Pair1.java.
References Scheme.Pair.cdr().
ISchemeObject Scheme.Pair.cddr ()
Definition at line 163 of file Pair.java.
References Scheme.Pair.cdr().
SchemeObject Scheme.Pair.cdr ()
Definition at line 108 of file Pair1.java.
Referenced by Scheme.Pair.append(), Scheme.Pair.assoc(), Scheme.Pair.cadr(), Scheme.Pair.cddr(), Scheme.Pair.cdr(), Scheme.Pair.closure(), Scheme.Pair.eq(), Scheme.Pair.equalp(), Scheme.Pair.gt(), Scheme.Pair.idivision(), Scheme.Pair.iexpt(), Scheme.Pair.iminus(), Scheme.Pair.iplus(), Scheme.Pair.itimes(), Scheme.Pair.listp(), Scheme.Pair.lt(), Scheme.Pair.member(), Scheme.Pair.Pair(), Scheme.Pair.quotient(), Scheme.Pair.remainder(), Scheme.Pair.remdup(), Scheme.Pair.remdup2(), Scheme.Pair.remove(), Scheme.Pair.reverse(), Scheme.Pair.rplacd(), Scheme.Pair.setcdr(), and Scheme.Pair.stringle().
ISchemeObject Scheme.Pair.cdr ()
Definition at line 151 of file Pair.java.
References Scheme.Pair.cdr().
Pair Scheme.Pair.closure ()
Definition at line 352 of file Pair1.java.
References Scheme.Pair.append(), Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.cons(), Scheme.Pair.definesym, Scheme.Pair.fc2(), Scheme.Pair.fc3(), Scheme.Pair.fv(), Scheme.RunEnv.interns(), Scheme.Pair.member(), Scheme.RunEnv.nilval, Scheme.Pair.nullp(), Scheme.Pair.Pair(), Scheme.Pair.remove(), and Scheme.Pair.searchgb().
Pair Scheme.Pair.closure ()
Definition at line 878 of file Pair.java.
References Scheme.Pair.append(), Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.cons(), Scheme.Pair.definesym, Scheme.Pair.fc2(), Scheme.Pair.fc3(), Scheme.Pair.fv(), Scheme.Pair.fv2(), Scheme.RunEnv.interns(), Scheme.RunEnv.nilval, and Scheme.Pair.Pair().
Pair Scheme.Pair.condexp ()
Definition at line 810 of file Pair1.java.
References Scheme.RunEnv.bTrue, Scheme.Pair.cons(), Scheme.RunEnv.interns(), Scheme.RunEnv.nilval, and Scheme.Pair.print().
Referenced by Scheme.Pair.expand().
Pair Scheme.Pair.condexp ()
Definition at line 1587 of file Pair.java.
References Scheme.RunEnv.bTrue, Scheme.Pair.cons(), Scheme.RunEnv.interns(), and Scheme.RunEnv.nilval.
Pair Scheme.Pair.cons (SchemeObject e)
Definition at line 19 of file Pair1.java.
References Scheme.Pair.Pair().
Referenced by Scheme.Pair.append(), Scheme.Pair.closure(), Scheme.Pair.condexp(), Scheme.Pair.eval(), Scheme.Pair.expand(), Scheme.Pair.expand2(), Scheme.Pair.expandlist(), Scheme.Pair.fc2(), Scheme.Pair.initlist(), Scheme.RunEnv.intern(), Scheme.Pair.lettwo(), Scheme.Pair.remdup(), Scheme.Pair.remdup2(), Scheme.Pair.remove(), Scheme.Pair.reverse(), Scheme.Pair.searchgb(), Scheme.Pair.searchv(), Scheme.Pair.settwo(), Scheme.Pair.steplist(), Scheme.Pair.ubvcdr(), Scheme.Pair.varlist(), and Scheme.Pair.vundef().
SchemeBoolean Scheme.Pair.eq ()
Definition at line 184 of file Pair1.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, Scheme.Pair.car(), Scheme.Pair.cdr(), and Scheme.SchemeObject.value.
SchemeBoolean Scheme.Pair.eq ()
Definition at line 293 of file Pair.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, Scheme.Pair.car(), and Scheme.Pair.Pair().
SchemeBoolean Scheme.Pair.eqp (SchemeObject o)
Definition at line 23 of file Pair1.java.
References Scheme.RunEnv.bFalse, and Scheme.RunEnv.bTrue.
SchemeBoolean Scheme.Pair.equalp (ISchemeObject compared_object)
Checks if this scheme object is equal (by value) to the given scheme object #compared_object.
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Returns:
a SchemeBoolean object with value 'true' if they are equal (have the same value), else false.
Reimplemented from Scheme.SchemeObject.
Definition at line 26 of file Pair.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.equalp(), Scheme.SchemeObject.equalp(), Scheme.Pair.nullp(), and Scheme.Pair.Pair().
SchemeBoolean Scheme.Pair.equalp (SchemeObject o)
Definition at line 30 of file Pair1.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, Scheme.Pair.car(), Scheme.Pair.cdr(), and Scheme.Pair.nullp().
Referenced by Scheme.Pair.equalp(), and Scheme.Pair.member().
SchemeObject Scheme.Pair.eval ()
Evaluates a scheme expression and returns a new scheme object. Which object is returned, depends on the scheme expression.
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Returns:
a scheme object. Which type of scheme object can be found out with castings.
Reimplemented from Scheme.SchemeObject.
Definition at line 928 of file Pair1.java.
References Scheme.Pair.apply(), Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, Scheme.Pair.cdr, Scheme.SchemeObject.eval(), Scheme.SchemeObject.nullp(), Scheme.Pair.nullp(), and Scheme.SchemeFunction.setBody().
ISchemeObject Scheme.Pair.eval ()
Evaluates a scheme expression and returns a new scheme object. Which object is returned, depends on the scheme expression.
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Returns:
a scheme object. Which type of scheme object can be found out with castings.
Reimplemented from Scheme.SchemeObject.
Definition at line 1729 of file Pair.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, Scheme.Pair.cons(), Scheme.Stack.empty(), Scheme.ISchemeObject.eval(), Scheme.ISchemeObject.expand(), Scheme.RunEnv.interns(), Scheme.RunEnv.nilval, Scheme.ISchemeObject.nullp(), Scheme.RunEnv.number_read_call_temp, Scheme.RunEnv.number_read_data_temp, Scheme.RunEnv.read_object, Scheme.RunEnv.read_status, Scheme.RunEnv.root, Scheme.SchemeFunction.setBody(), Scheme.RunEnv.stack, and Scheme.RunEnv.unbound.
SchemeObject Scheme.Pair.evlis (Pair l)
Definition at line 911 of file Pair1.java.
References Scheme.SchemeObject.cons().
ISchemeObject Scheme.Pair.evlis (Pair l)
Definition at line 1711 of file Pair.java.
References Scheme.ISchemeObject.cons().
SchemeNumber Scheme.Pair.exactinexact ()
Definition at line 839 of file Pair.java.
References Scheme.Pair.car(), and Scheme.Pair.nullp().
SchemeObject Scheme.Pair.expand ()
Expands a scheme expression once. Which object is returned, depends on the scheme expression.
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Returns:
a scheme object. Which type of scheme object can be found out with castings.
See also:
e.g. symbolp(), numberp(), integerp(), realp(), pairp(), listp(), nullp()
Reimplemented from Scheme.SchemeObject.
Definition at line 658 of file Pair1.java.
References Scheme.Pair.andexp(), Scheme.Pair.condexp(), Scheme.Pair.cons(), Scheme.Pair.expand(), Scheme.Pair.expandlist(), Scheme.RunEnv.interns(), Scheme.RunEnv.nilval, Scheme.Pair.orexp(), and Scheme.Pair.print().
Referenced by Scheme.Pair.expand().
ISchemeObject Scheme.Pair.expand ()
Expands a scheme expression once. Which object is returned, depends on the scheme expression.
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Returns:
a scheme object. Which type of scheme object can be found out with castings.
See also:
e.g. symbolp(), numberp(), integerp(), realp(), pairp(), listp(), nullp()
Reimplemented from Scheme.SchemeObject.
Definition at line 1331 of file Pair.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, Scheme.Pair.cons(), Scheme.RunEnv.interns(), and Scheme.RunEnv.nilval.
Pair Scheme.Pair.expand2 (String part1, String part2)
Definition at line 758 of file Pair1.java.
References Scheme.Pair.cons(), Scheme.RunEnv.interns(), and Scheme.RunEnv.nilval.
Pair Scheme.Pair.expand2 (String part1, String part2)
Definition at line 1562 of file Pair.java.
References Scheme.Pair.cons(), Scheme.RunEnv.interns(), and Scheme.RunEnv.nilval.
ISchemeObject Scheme.Pair.expandall ()
Expands a scheme expression until it cannot be expanded anymore. Which object is returned, depends on the scheme expression.
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Returns:
a scheme object. Which type of scheme object can be found out with castings.
See also:
e.g. symbolp(), numberp(), integerp(), realp(), pairp(), listp(), nullp()
Reimplemented from Scheme.SchemeObject.
Definition at line 1308 of file Pair.java.
References Scheme.RunEnv.nilval.
Pair Scheme.Pair.expandlist ()
Definition at line 651 of file Pair1.java.
References Scheme.Pair.cons(), Scheme.Pair.expandlist(), and Scheme.RunEnv.nilval.
Referenced by Scheme.Pair.expand(), and Scheme.Pair.expandlist().
Pair Scheme.Pair.expandlist ()
Definition at line 1323 of file Pair.java.
References Scheme.Pair.cons(), Scheme.Pair.expandlist(), and Scheme.RunEnv.nilval.
Pair Scheme.Pair.fc2 (Pair fvars, Pair befarg) [private]
Definition at line 397 of file Pair1.java.
References Scheme.Pair.car, Scheme.Pair.cdr, Scheme.Pair.cons(), Scheme.RunEnv.interns(), Scheme.RunEnv.nilval, and Scheme.Pair.nullp().
Referenced by Scheme.Pair.closure(), and Scheme.Pair.fc2().
Pair Scheme.Pair.fc2 (Pair fvars, Pair befarg) [private]
Definition at line 948 of file Pair.java.
References Scheme.Pair.cons(), Scheme.Pair.fc2(), Scheme.RunEnv.interns(), and Scheme.RunEnv.nilval.
void Scheme.Pair.fc3 (Pair fvars, Pair l) [private]
Definition at line 411 of file Pair1.java.
References Scheme.Pair.cdr, and Scheme.Pair.nullp().
Referenced by Scheme.Pair.closure().
void Scheme.Pair.fc3 (Pair fvars, Pair l) [private]
Definition at line 964 of file Pair.java.
Pair Scheme.Pair.fv (Pair vars, Pair body) [private]
Definition at line 419 of file Pair1.java.
References Scheme.Pair.remdup().
Referenced by Scheme.Pair.closure().
Pair Scheme.Pair.fv (Pair vars, Pair body) [private]
Definition at line 972 of file Pair.java.
Pair Scheme.Pair.fv2 (Symbol var, Pair body) [private]
Definition at line 983 of file Pair.java.
Referenced by Scheme.Pair.closure().
SchemeBoolean Scheme.Pair.gt ()
Definition at line 204 of file Pair1.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, Scheme.Pair.car(), Scheme.Pair.cdr(), and Scheme.SchemeObject.value.
SchemeBoolean Scheme.Pair.gt ()
Definition at line 343 of file Pair.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, Scheme.Pair.car(), and Scheme.Pair.Pair().
SchemeNumber Scheme.Pair.idivision ()
Definition at line 248 of file Pair1.java.
References Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.nullp(), Scheme.Pair.Pair(), and Scheme.SchemeObject.value.
SchemeNumber Scheme.Pair.idivision ()
Definition at line 446 of file Pair.java.
References Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.nullp(), and Scheme.Pair.Pair().
SchemeNumber Scheme.Pair.iexpt ()
Definition at line 298 of file Pair1.java.
References Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.nullp(), Scheme.Pair.Pair(), and Scheme.SchemeObject.value.
SchemeNumber Scheme.Pair.iexpt ()
Definition at line 556 of file Pair.java.
References Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.nullp(), and Scheme.Pair.Pair().
SchemeNumber Scheme.Pair.iminus ()
Definition at line 215 of file Pair1.java.
References Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.nullp(), Scheme.Pair.Pair(), and Scheme.SchemeObject.value.
SchemeNumber Scheme.Pair.iminus ()
Subtraction function.
Returns:
no param: 0; one param: -param; two or more params: param1 - param2 - ...
Definition at line 389 of file Pair.java.
References Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.nullp(), and Scheme.Pair.Pair().
SchemeNumber Scheme.Pair.inexactexact ()
Definition at line 857 of file Pair.java.
References Scheme.Pair.car(), and Scheme.Pair.nullp().
Pair Scheme.Pair.initlist ()
Definition at line 902 of file Pair1.java.
References Scheme.Pair.cons(), and Scheme.RunEnv.nilval.
Referenced by Scheme.Pair.initlist().
Pair Scheme.Pair.initlist ()
Definition at line 1686 of file Pair.java.
References Scheme.Pair.cons(), Scheme.Pair.initlist(), and Scheme.RunEnv.nilval.
SchemeNumber Scheme.Pair.iplus ()
Definition at line 162 of file Pair1.java.
References Scheme.Pair.cdr(), Scheme.Pair.nullp(), Scheme.Pair.Pair(), Scheme.SchemeNumber.value, and Scheme.SchemeObject.value.
SchemeNumber Scheme.Pair.iplus ()
Definition at line 243 of file Pair.java.
References Scheme.Pair.Pair().
SchemeNumber Scheme.Pair.itimes ()
Definition at line 173 of file Pair1.java.
References Scheme.Pair.cdr(), Scheme.Pair.nullp(), Scheme.Pair.Pair(), Scheme.SchemeNumber.value, and Scheme.SchemeObject.value.
SchemeNumber Scheme.Pair.itimes ()
Definition at line 268 of file Pair.java.
References Scheme.Pair.Pair().
SchemeNumber Scheme.Pair.length ()
Definition at line 799 of file Pair.java.
References Scheme.Pair.car(), Scheme.Pair.nullp(), and Scheme.Pair.Pair().
Pair Scheme.Pair.lettwo ()
Definition at line 863 of file Pair1.java.
References Scheme.Pair.cons(), Scheme.RunEnv.interns(), Scheme.RunEnv.nilval, Scheme.SchemeObject.print(), and Scheme.Pair.print().
Pair Scheme.Pair.lettwo ()
Definition at line 1638 of file Pair.java.
References Scheme.Pair.cons(), Scheme.RunEnv.interns(), and Scheme.RunEnv.nilval.
Pair Scheme.Pair.list ()
Definition at line 138 of file Pair1.java.
Pair Scheme.Pair.list ()
Definition at line 194 of file Pair.java.
SchemeBoolean Scheme.Pair.listp ()
Checks if this scheme object is a list of pairs and returns a SchemeBoolean. All classes exept the Pair class should return always false! The pair class should check if all tail elements are Pair objects. If it is so, the method should return true.
Returns:
a SchemeBoolean with value 'true', if this scheme object is a list of pairs, else 'false'.
Implements Scheme.ISchemePair.
Definition at line 220 of file Pair.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, Scheme.Pair.car(), and Scheme.Pair.cdr().
SchemeBoolean Scheme.Pair.lt ()
Definition at line 194 of file Pair1.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, Scheme.Pair.car(), Scheme.Pair.cdr(), and Scheme.SchemeObject.value.
SchemeBoolean Scheme.Pair.lt ()
Definition at line 318 of file Pair.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, Scheme.Pair.car(), and Scheme.Pair.Pair().
SchemeNumber Scheme.Pair.max ()
Definition at line 770 of file Pair.java.
References Scheme.Pair.car(), and Scheme.Pair.Pair().
Pair Scheme.Pair.member (SchemeObject e)
Definition at line 53 of file Pair1.java.
References Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.member(), Scheme.RunEnv.nilval, and Scheme.Pair.nullp().
Referenced by Scheme.Pair.closure(), Scheme.Pair.member(), Scheme.Pair.remdup(), and Scheme.Pair.remdup2().
Pair Scheme.Pair.member (ISchemeObject e)
Definition at line 57 of file Pair.java.
References Scheme.RunEnv.bTrue, Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.equalp(), Scheme.RunEnv.nilval, and Scheme.Pair.nullp().
SchemeNumber Scheme.Pair.min ()
Definition at line 741 of file Pair.java.
References Scheme.Pair.car(), and Scheme.Pair.Pair().
ISchemeObject Scheme.Pair.newline ()
Definition at line 2002 of file Pair.java.
References Scheme.RunEnv.nilval.
Referenced by Scheme.RunEnv.newline().
SchemeBoolean Scheme.Pair.not ()
Returns a negated object of type SchemeBoolean. E.g., all objects which implements the SchemeBoolean class should also implement this method.
Returns:
a negated SchemeBoolean object.
Implements Scheme.ISchemeBoolean.
Definition at line 158 of file Pair1.java.
References Scheme.RunEnv.bFalse.
SchemeBoolean Scheme.Pair.not ()
Returns a negated object of type SchemeBoolean. E.g., all objects which implements the SchemeBoolean class should also implement this method.
Returns:
a negated SchemeBoolean object.
Implements Scheme.ISchemeBoolean.
Definition at line 236 of file Pair.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, and Scheme.Pair.car().
boolean Scheme.Pair.nullp ()
Checks if the scheme object is an empty object.
Returns:
true, if the scheme object is an empty object, else false.
See also:
class Pair.
Reimplemented from Scheme.SchemeObject.
Definition at line 142 of file Pair1.java.
References Scheme.Pair.car().
Referenced by Scheme.Pair.abs(), Scheme.Pair.append(), Scheme.Pair.apply(), Scheme.Pair.assoc(), Scheme.RunEnv.bind(), Scheme.Pair.closure(), Scheme.Pair.equalp(), Scheme.Pair.eval(), Scheme.Pair.exactinexact(), Scheme.Pair.fc2(), Scheme.Pair.fc3(), Scheme.Pair.idivision(), Scheme.Pair.iexpt(), Scheme.Pair.iminus(), Scheme.Pair.inexactexact(), Scheme.Pair.iplus(), Scheme.Pair.itimes(), Scheme.Pair.length(), Scheme.Pair.member(), Scheme.Pair.quotient(), Scheme.Pair.remainder(), Scheme.Pair.remdup(), Scheme.Pair.remdup2(), Scheme.Pair.remove(), Scheme.Pair.reverse(), and Scheme.RunEnv.unbind().
boolean Scheme.Pair.nullp ()
Checks if the scheme object is an empty object.
Returns:
true, if the scheme object is an empty object, else false.
See also:
class Pair.
Reimplemented from Scheme.SchemeObject.
Definition at line 199 of file Pair.java.
References Scheme.Pair.car().
SchemeBoolean Scheme.Pair.nullpp ()
??????????????? Checks if this scheme object is a number object and returns a SchemeBoolean. Only the SchemeNumber class should return true, all other classes should return false!
Returns:
a SchemeBoolean with value 'true', if this scheme object is from type SchemeNumber, else 'false'.
Implements Scheme.ISchemePair.
Definition at line 204 of file Pair.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, and Scheme.Pair.car().
SchemeObject Scheme.Pair.orexp ()
Definition at line 788 of file Pair1.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, Scheme.Pair.cdr, and Scheme.Pair.orexp().
Referenced by Scheme.Pair.expand(), and Scheme.Pair.orexp().
ISchemeObject Scheme.Pair.orexp ()
Definition at line 1568 of file Pair.java.
References Scheme.RunEnv.bFalse, and Scheme.RunEnv.bTrue.
SchemeBoolean Scheme.Pair.pairp ()
Checks if this scheme object is a Pair object and returns a SchemeBoolean. Only the Pair class should return true, all other classes should return false!
Returns:
a SchemeBoolean with value 'true', if this scheme object is from type Pair, else 'false'.
Implements Scheme.ISchemePair.
Definition at line 146 of file Pair1.java.
References Scheme.RunEnv.bTrue.
SchemeBoolean Scheme.Pair.pairp ()
Checks if this scheme object is a Pair object and returns a SchemeBoolean. Only the Pair class should return true, all other classes should return false!
Returns:
a SchemeBoolean with value 'true', if this scheme object is from type Pair, else 'false'.
Implements Scheme.ISchemePair.
Definition at line 212 of file Pair.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, and Scheme.Pair.car().
void Scheme.Pair.print ()
Prints the scheme object to 'stdout' (mostly a console).
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Reimplemented from Scheme.SchemeObject.
Definition at line 1079 of file Pair1.java.
Referenced by Scheme.Pair.condexp(), Scheme.Pair.expand(), Scheme.Pair.lettwo(), and Scheme.Pair.vundef().
void Scheme.Pair.print ()
Prints the scheme object to 'stdout' (mostly a console).
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Reimplemented from Scheme.SchemeObject.
Definition at line 1980 of file Pair.java.
void Scheme.Pair.printlist ()
Definition at line 1089 of file Pair1.java.
void Scheme.Pair.printlist ()
Definition at line 1990 of file Pair.java.
ISchemeObject Scheme.Pair.printp (BufferedWriter open_buffer_writer)
Prints the scheme object to the BufferedWriter.
Note:
This is an important function for the scheme interpreter and must be implemented by all scheme objects.
Implements Scheme.ISchemeObject.
Definition at line 1941 of file Pair.java.
References Scheme.RunEnv.nilval.
void Scheme.Pair.printplist (BufferedWriter open_buffer_writer)
Definition at line 1960 of file Pair.java.
static ISchemeObject Scheme.Pair.quasiquote (ISchemeObject e) [static]
Definition at line 1900 of file Pair.java.
SchemeNumber Scheme.Pair.quotient ()
Definition at line 615 of file Pair.java.
References Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.SchemeInteger.ivalue, Scheme.Pair.nullp(), and Scheme.Pair.Pair().
Referenced by Scheme.Pair.remainder().
SchemeNumber Scheme.Pair.remainder ()
Definition at line 676 of file Pair.java.
References Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.nullp(), Scheme.Pair.Pair(), and Scheme.Pair.quotient().
Pair Scheme.Pair.remdup (Pair l)
Definition at line 91 of file Pair1.java.
References Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.cons(), Scheme.Pair.member(), Scheme.RunEnv.nilval, and Scheme.Pair.nullp().
Referenced by Scheme.Pair.fv(), and Scheme.Pair.remdup().
Pair Scheme.Pair.remdup (Pair l)
Definition at line 123 of file Pair.java.
References Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.cons(), Scheme.Pair.member(), Scheme.RunEnv.nilval, Scheme.Pair.nullp(), and Scheme.Pair.remdup().
Pair Scheme.Pair.remdup2 (Symbol l)
Definition at line 135 of file Pair.java.
References Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.cons(), Scheme.Pair.member(), Scheme.RunEnv.nilval, Scheme.Pair.nullp(), and Scheme.Pair.remdup2().
Referenced by Scheme.Pair.remdup2().
Pair Scheme.Pair.remfunctions (Pair vars) [private]
Definition at line 994 of file Pair.java.
Pair Scheme.Pair.remlocallambdas (Pair frees)
Definition at line 482 of file Pair1.java.
References Scheme.Pair.car, and Scheme.Pair.remove().
Pair Scheme.Pair.remlocallambdas (Pair frees)
Definition at line 1065 of file Pair.java.
Pair Scheme.Pair.remove (SchemeObject e)
Definition at line 63 of file Pair1.java.
References Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.cons(), Scheme.RunEnv.nilval, and Scheme.Pair.nullp().
Referenced by Scheme.Pair.closure(), and Scheme.Pair.remlocallambdas().
Pair Scheme.Pair.remove (ISchemeObject e)
Definition at line 96 of file Pair.java.
References Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.cons(), Scheme.RunEnv.nilval, and Scheme.Pair.nullp().
Pair Scheme.Pair.removel (Pair li)
Definition at line 1096 of file Pair.java.
Pair Scheme.Pair.reverse ()
Definition at line 73 of file Pair1.java.
References Scheme.Pair.append(), Scheme.Pair.cdr(), Scheme.Pair.cons(), Scheme.RunEnv.nilval, Scheme.Pair.nullp(), and Scheme.Pair.reverse().
Referenced by Scheme.Pair.reverse().
Pair Scheme.Pair.reverse ()
Definition at line 105 of file Pair.java.
References Scheme.Pair.append(), Scheme.Pair.cdr(), Scheme.Pair.cons(), Scheme.RunEnv.nilval, Scheme.Pair.nullp(), and Scheme.Pair.reverse().
Pair Scheme.Pair.rplaca (SchemeObject x)
Definition at line 128 of file Pair1.java.
References Scheme.Pair.car().
Pair Scheme.Pair.rplaca (ISchemeObject x)
Definition at line 171 of file Pair.java.
References Scheme.Pair.car().
Pair Scheme.Pair.rplacd (SchemeObject x)
Definition at line 133 of file Pair1.java.
References Scheme.Pair.cdr().
Pair Scheme.Pair.rplacd (ISchemeObject x)
Definition at line 184 of file Pair.java.
References Scheme.Pair.cdr().
Pair Scheme.Pair.searchb (Stack s) [private]
Definition at line 462 of file Pair1.java.
References Scheme.Stack.empty(), Scheme.RunEnv.nilval, Scheme.Stack.pop(), and Scheme.Stack.top().
Pair Scheme.Pair.searchb (Stack s) [private]
Definition at line 1044 of file Pair.java.
References Scheme.Stack.empty(), Scheme.RunEnv.nilval, Scheme.Stack.pop(), and Scheme.Stack.top().
Pair Scheme.Pair.searchgb () [private]
Definition at line 448 of file Pair1.java.
References Scheme.RunEnv.nilval.
Referenced by Scheme.Pair.closure().
Pair Scheme.Pair.searchgb () [private]
Definition at line 1027 of file Pair.java.
References Scheme.Pair.cons(), Scheme.RunEnv.interns(), Scheme.RunEnv.nilval, and Scheme.RunEnv.unbound.
SchemeObject Scheme.Pair.searchv (SchemeObject l) [private]
Definition at line 428 of file Pair1.java.
References Scheme.Pair.cons(), Scheme.RunEnv.nilval, and Scheme.SchemeObject.nullp().
ISchemeObject Scheme.Pair.searchv (ISchemeObject l) [private]
Definition at line 1008 of file Pair.java.
References Scheme.Pair.cons(), Scheme.RunEnv.nilval, and Scheme.ISchemeObject.nullp().
Pair Scheme.Pair.setcar (ISchemeObject x)
Definition at line 178 of file Pair.java.
References Scheme.Pair.car().
Pair Scheme.Pair.setcdr (ISchemeObject x)
Definition at line 189 of file Pair.java.
References Scheme.Pair.cdr().
Pair Scheme.Pair.settwo ()
Definition at line 878 of file Pair1.java.
References Scheme.RunEnv.interns(), and Scheme.RunEnv.nilval.
Pair Scheme.Pair.settwo ()
Definition at line 1660 of file Pair.java.
References Scheme.Pair.cons(), Scheme.RunEnv.interns(), and Scheme.RunEnv.nilval.
Pair Scheme.Pair.steplist ()
Definition at line 1701 of file Pair.java.
References Scheme.Pair.cons(), Scheme.RunEnv.nilval, and Scheme.Pair.steplist().
Referenced by Scheme.Pair.steplist().
SchemeString Scheme.Pair.stringappend (SchemeString s)
Definition at line 368 of file Pair.java.
SchemeBoolean Scheme.Pair.stringle ()
Definition at line 372 of file Pair.java.
References Scheme.RunEnv.bFalse, Scheme.RunEnv.bTrue, Scheme.Pair.car(), Scheme.Pair.cdr(), Scheme.Pair.Pair(), and Scheme.SchemeObject.value.
SchemeBoolean Scheme.Pair.symbolp ()
Definition at line 150 of file Pair1.java.
References Scheme.RunEnv.bFalse.
void Scheme.Pair.treeeval (boolean trace)
Definition at line 1056 of file Pair1.java.
References Scheme.ISchemeObject.eval(), Scheme.SchemeObject.expand(), and Scheme.SchemeObject.print().
void Scheme.Pair.treeeval (boolean trace)
Definition at line 1918 of file Pair.java.
References Scheme.ISchemeObject.eval(), Scheme.ISchemeObject.expand(), and Scheme.ISchemeObject.print().
Pair Scheme.Pair.ubvcdr ()
Definition at line 476 of file Pair1.java.
References Scheme.Pair.cons(), Scheme.RunEnv.nilval, and Scheme.Pair.ubvcdr().
Referenced by Scheme.Pair.ubvcdr().
Pair Scheme.Pair.ubvcdr ()
Definition at line 1058 of file Pair.java.
References Scheme.Pair.cons(), Scheme.RunEnv.nilval, and Scheme.Pair.ubvcdr().
Pair Scheme.Pair.varlist ()
Definition at line 1694 of file Pair.java.
References Scheme.Pair.cons(), Scheme.RunEnv.nilval, and Scheme.Pair.varlist().
Referenced by Scheme.Pair.varlist().
Pair Scheme.Pair.vl ()
Definition at line 848 of file Pair1.java.
References Scheme.RunEnv.nilval.
Pair Scheme.Pair.vl ()
Definition at line 1623 of file Pair.java.
References Scheme.ISchemeObject.cons(), and Scheme.RunEnv.nilval.
Pair Scheme.Pair.vn ()
Definition at line 834 of file Pair1.java.
References Scheme.RunEnv.nilval.
Pair Scheme.Pair.vn ()
Definition at line 1609 of file Pair.java.
References Scheme.RunEnv.nilval.
Pair Scheme.Pair.vundef ()
Definition at line 889 of file Pair1.java.
References Scheme.RunEnv.bTrue, Scheme.Pair.cons(), Scheme.RunEnv.nilval, and Scheme.Pair.print().
Referenced by Scheme.Pair.vundef().
Pair Scheme.Pair.vundef ()
Definition at line 1674 of file Pair.java.
References Scheme.RunEnv.bTrue, Scheme.Pair.cons(), Scheme.RunEnv.nilval, and Scheme.Pair.vundef().
SchemeObject Scheme.Pair.write ()
Definition at line 1073 of file Pair1.java.
References Scheme.RunEnv.nilval.
ISchemeObject Scheme.Pair.write ()
Definition at line 1936 of file Pair.java.
References Scheme.RunEnv.write().
SchemeBoolean Scheme.Pair.zerop ()
Definition at line 154 of file Pair1.java.
References Scheme.RunEnv.bFalse.
Member Data Documentation
SchemeObject Scheme.Pair.car [package]
Definition at line 8 of file Pair1.java.
Referenced by Scheme.Pair.apply(), Scheme.RunEnv.bind(), Scheme.Pair.closure(), Scheme.Pair.fc2(), and Scheme.Pair.remlocallambdas().
ISchemeObject Scheme.Pair.car [package]
Definition at line 12 of file Pair.java.
SchemeObject Scheme.Pair.cdr [package]
Definition at line 9 of file Pair1.java.
Referenced by Scheme.Pair.andexp(), Scheme.Pair.apply(), Scheme.RunEnv.bind(), Scheme.Pair.eval(), Scheme.Pair.fc2(), Scheme.Pair.fc3(), Scheme.Pair.orexp(), and Scheme.RunEnv.unbind().
ISchemeObject Scheme.Pair.cdr [package]
Definition at line 13 of file Pair.java.
static boolean Scheme.Pair::closurestatus = false [static, package]
Definition at line 6 of file Pair1.java.
Referenced by Scheme.Pair.apply().
static Symbol Scheme.Pair::definesym [static, package]
Definition at line 7 of file Pair1.java.
Referenced by Scheme.Pair.closure().
The documentation for this class was generated from the following files:
backup/Pair1.java
src/Scheme/Pair.java