Jamus Scheme: java_cup.parse_action_table Class Reference
java_cup.parse_action_table Class Reference
Public Member Functions
parse_action_table ()
int num_states ()
void check_reductions () throws internal_error
String toString ()
Public Attributes
parse_action_row[] under_state
Protected Attributes
int _num_states
Detailed Description
This class represents the complete "action" table of the parser. It has one row for each state in the parse machine, and a column for each terminal symbol. Each entry in the table represents a shift, reduce, or an error.
See also:
java_cup.parse_action
java_cup.parse_action_row
Version:
last updated: 11/25/95
Author:
Scott Hudson
Definition at line 16 of file parse_action_table.java.
Constructor & Destructor Documentation
java_cup.parse_action_table.parse_action_table ()
Simple constructor. All terminals, non-terminals, and productions must already have been entered, and the viable prefix recognizer should have been constructed before this is called.
Definition at line 26 of file parse_action_table.java.
References java_cup.parse_action_table._num_states, java_cup.lalr_state.number(), and java_cup.parse_action_table.under_state.
Member Function Documentation
void java_cup.parse_action_table.check_reductions () throws internal_error
Check the table to ensure that all productions have been reduced. Issue a warning message (to System.err) for each production that is never reduced.
Definition at line 60 of file parse_action_table.java.
References java_cup.production.all(), java_cup.parse_action.kind(), java_cup.emit.nowarn, java_cup.production.num_reductions(), java_cup.parse_action_table.num_states(), java_cup.parse_action.REDUCE, java_cup.parse_action_row.size(), java_cup.production.to_simple_string(), java_cup.parse_action_table.under_state, java_cup.parse_action_row.under_term, and java_cup.lexer.warning_count.
Referenced by java_cup.Main.build_parser().
int java_cup.parse_action_table.num_states ()
How many rows/states are in the machine/table.
Definition at line 45 of file parse_action_table.java.
References java_cup.parse_action_table._num_states.
Referenced by java_cup.parse_action_table.check_reductions().
String java_cup.parse_action_table.toString ()
Definition at line 106 of file parse_action_table.java.
References java_cup.parse_action_table.under_state, and java_cup.parse_action_row.under_term.
Member Data Documentation
int java_cup.parse_action_table._num_states [protected]
How many rows/states are in the machine/table.
Definition at line 42 of file parse_action_table.java.
Referenced by java_cup.parse_action_table.num_states(), and java_cup.parse_action_table.parse_action_table().
parse_action_row [] java_cup.parse_action_table.under_state
Actual array of rows, one per state.
Definition at line 50 of file parse_action_table.java.
Referenced by java_cup.parse_action_table.check_reductions(), java_cup.parse_action_table.parse_action_table(), and java_cup.parse_action_table.toString().
The documentation for this class was generated from the following file:
src/java_cup/parse_action_table.java