Jamus Scheme: java_cup.lalr_item_set Class Reference
java_cup.lalr_item_set Class Reference
Public Member Functions
lalr_item_set ()
lalr_item_set (lalr_item_set other) throws internal_error
Enumeration all ()
int size ()
boolean contains (lalr_item itm)
lalr_item find (lalr_item itm)
boolean is_subset_of (lalr_item_set other) throws internal_error
boolean is_superset_of (lalr_item_set other) throws internal_error
lalr_item add (lalr_item itm) throws internal_error
void remove (lalr_item itm) throws internal_error
void add (lalr_item_set other) throws internal_error
void remove (lalr_item_set other) throws internal_error
lalr_item get_one () throws internal_error
void compute_closure () throws internal_error
boolean equals (lalr_item_set other)
boolean equals (Object other)
int hashCode ()
String toString ()
Protected Member Functions
void not_null (Object obj) throws internal_error
Protected Attributes
Hashtable _all = new Hashtable(11)
Integer hashcode_cache = null
Detailed Description
This class represents a set of LALR items. For purposes of building these sets, items are considered unique only if they have unique cores (i.e., ignoring differences in their lookahead sets).
This class provides fairly conventional set oriented operations (union, sub/super-set tests, etc.), as well as an LALR "closure" operation (see compute_closure()).
See also:
java_cup.lalr_item
java_cup.lalr_state
Version:
last updated: 3/6/96
Author:
Scott Hudson
Definition at line 21 of file lalr_item_set.java.
Constructor & Destructor Documentation
java_cup.lalr_item_set.lalr_item_set ()
Constructor for an empty set.
Definition at line 28 of file lalr_item_set.java.
Referenced by java_cup.lalr_item_set.compute_closure().
java_cup.lalr_item_set.lalr_item_set (lalr_item_set other) throws internal_error
Constructor for cloning from another set.
Parameters:
other indicates set we should copy from.
Definition at line 35 of file lalr_item_set.java.
References java_cup.lalr_item_set._all, and java_cup.lalr_item_set.not_null().
Member Function Documentation
lalr_item java_cup.lalr_item_set.add (lalr_item itm) throws internal_error
Add a singleton item, merging lookahead sets if the item is already part of the set. returns the element of the set that was added or merged into.
Parameters:
itm the item being added.
Definition at line 117 of file lalr_item_set.java.
References java_cup.lalr_item_set._all, java_cup.terminal_set.add(), java_cup.lalr_item_set.hashcode_cache, java_cup.lalr_item.lookahead(), and java_cup.lalr_item_set.not_null().
Referenced by java_cup.lalr_item_set.add(), java_cup.lalr_state.build_machine(), and java_cup.lalr_item_set.compute_closure().
void java_cup.lalr_item_set.add (lalr_item_set other) throws internal_error
Add a complete set, merging lookaheads where items are already in the set
Parameters:
other the set to be added.
Definition at line 165 of file lalr_item_set.java.
References java_cup.lalr_item_set.add(), and java_cup.lalr_item_set.not_null().
Enumeration java_cup.lalr_item_set.all ()
Access to all elements of the set.
Definition at line 52 of file lalr_item_set.java.
References java_cup.lalr_item_set._all.
Referenced by java_cup.lalr_state.build_machine(), java_cup.lalr_state.dump_state(), java_cup.lalr_item_set.get_one(), java_cup.lalr_item_set.hashCode(), java_cup.lalr_item_set.is_subset_of(), java_cup.lalr_state.report_conflicts(), java_cup.lalr_state.report_shift_reduce(), and java_cup.lalr_item_set.toString().
void java_cup.lalr_item_set.compute_closure () throws internal_error
Compute the closure of the set using the LALR closure rules. Basically for every item of the form:
    [L ::= a *N alpha, l]
(where N is a a non terminal and alpha is a string of symbols) make sure there are also items of the form:
    [N ::= *beta, first(alpha l)]
corresponding to each production of N. Items with identical cores but differing lookahead sets are merged by creating a new item with the same core and the union of the lookahead sets (the LA in LALR stands for "lookahead merged" and this is where the merger is). This routine assumes that nullability and first sets have been computed for all productions before it is called.
Definition at line 238 of file lalr_item_set.java.
References java_cup.lalr_item_set.add(), java_cup.lalr_item.add_propagate(), java_cup.lalr_item.calc_lookahead(), java_cup.lr_item_core.dot_before_nt(), java_cup.lalr_item_set.get_one(), java_cup.lalr_item_set.hashcode_cache, java_cup.lalr_item_set.lalr_item_set(), java_cup.lalr_item.lookahead(), java_cup.lalr_item.lookahead_visible(), java_cup.non_terminal.productions(), and java_cup.lalr_item_set.size().
Referenced by java_cup.lalr_state.build_machine().
boolean java_cup.lalr_item_set.contains (lalr_item itm)
Does the set contain a particular item?
Parameters:
itm the item in question.
Definition at line 71 of file lalr_item_set.java.
References java_cup.lalr_item_set._all.
boolean java_cup.lalr_item_set.equals (lalr_item_set other)
Equality comparison.
Definition at line 302 of file lalr_item_set.java.
References java_cup.internal_error.crash(), java_cup.lalr_item_set.is_subset_of(), and java_cup.lalr_item_set.size().
Referenced by java_cup.lalr_item_set.equals(), and java_cup.lalr_state.equals().
boolean java_cup.lalr_item_set.equals (Object other)
Generic equality comparison.
Definition at line 320 of file lalr_item_set.java.
References java_cup.lalr_item_set.equals().
lalr_item java_cup.lalr_item_set.find (lalr_item itm)
Return the item in the set matching a particular item (or null if not found)
Parameters:
itm the item we are looking for.
Definition at line 79 of file lalr_item_set.java.
References java_cup.lalr_item_set._all.
Referenced by java_cup.lalr_state.build_machine().
lalr_item java_cup.lalr_item_set.get_one () throws internal_error
Remove and return one item from the set (done in hash order).
Definition at line 191 of file lalr_item_set.java.
References java_cup.lalr_item_set.all().
Referenced by java_cup.lalr_item_set.compute_closure().
int java_cup.lalr_item_set.hashCode ()
Return hash code.
Definition at line 331 of file lalr_item_set.java.
References java_cup.lalr_item_set.all(), and java_cup.lalr_item_set.hashcode_cache.
Referenced by java_cup.lalr_state.hashCode().
boolean java_cup.lalr_item_set.is_subset_of (lalr_item_set other) throws internal_error
Is this set an (improper) subset of another?
Parameters:
other the other set in question.
Definition at line 86 of file lalr_item_set.java.
References java_cup.lalr_item_set.all(), and java_cup.lalr_item_set.not_null().
Referenced by java_cup.lalr_item_set.equals().
boolean java_cup.lalr_item_set.is_superset_of (lalr_item_set other) throws internal_error
Is this set an (improper) superset of another?
Parameters:
other the other set in question.
Definition at line 104 of file lalr_item_set.java.
References java_cup.lalr_item_set.not_null().
void java_cup.lalr_item_set.not_null (Object obj) throws internal_error [protected]
Helper function for null test. Throws an interal_error exception if its parameter is null.
Parameters:
obj the object we are testing.
Definition at line 215 of file lalr_item_set.java.
Referenced by java_cup.lalr_item_set.add(), java_cup.lalr_item_set.is_subset_of(), java_cup.lalr_item_set.is_superset_of(), java_cup.lalr_item_set.lalr_item_set(), and java_cup.lalr_item_set.remove().
void java_cup.lalr_item_set.remove (lalr_item itm) throws internal_error
Remove a single item if it is in the set.
Parameters:
itm the item to remove.
Definition at line 148 of file lalr_item_set.java.
References java_cup.lalr_item_set._all, java_cup.lalr_item_set.hashcode_cache, and java_cup.lalr_item_set.not_null().
void java_cup.lalr_item_set.remove (lalr_item_set other) throws internal_error
Remove (set subtract) a complete set.
Parameters:
other the set to remove.
Definition at line 179 of file lalr_item_set.java.
References java_cup.lalr_item_set.not_null().
int java_cup.lalr_item_set.size ()
Size of the set
Definition at line 62 of file lalr_item_set.java.
References java_cup.lalr_item_set._all.
Referenced by java_cup.lalr_item_set.compute_closure(), and java_cup.lalr_item_set.equals().
String java_cup.lalr_item_set.toString ()
Convert to string.
Definition at line 356 of file lalr_item_set.java.
References java_cup.lalr_item_set.all().
Member Data Documentation
Hashtable java_cup.lalr_item_set._all = new Hashtable(11) [protected]
A hash table to implement the set. We store the items using themselves as keys.
Definition at line 49 of file lalr_item_set.java.
Referenced by java_cup.lalr_item_set.add(), java_cup.lalr_item_set.all(), java_cup.lalr_item_set.contains(), java_cup.lalr_item_set.find(), java_cup.lalr_item_set.lalr_item_set(), java_cup.lalr_item_set.remove(), and java_cup.lalr_item_set.size().
Integer java_cup.lalr_item_set.hashcode_cache = null [protected]
Cached hashcode for this set.
Definition at line 57 of file lalr_item_set.java.
Referenced by java_cup.lalr_item_set.add(), java_cup.lalr_item_set.compute_closure(), java_cup.lalr_item_set.hashCode(), and java_cup.lalr_item_set.remove().
The documentation for this class was generated from the following file:
src/java_cup/lalr_item_set.java