Jamus Scheme: java_cup.lalr_transition Class Reference
java_cup.lalr_transition Class Reference
Public Member Functions
lalr_transition (symbol on_sym, lalr_state to_st, lalr_transition nxt) throws internal_error
lalr_transition (symbol on_sym, lalr_state to_st) throws internal_error
symbol on_symbol ()
lalr_state to_state ()
lalr_transition next ()
String toString ()
Protected Attributes
symbol _on_symbol
lalr_state _to_state
lalr_transition _next
Detailed Description
This class represents a transition in an LALR viable prefix recognition machine. Transitions can be under terminals for non-terminals. They are internally linked together into singly linked lists containing all the transitions out of a single state via the _next field.
See also:
java_cup.lalr_state
Version:
last updated: 11/25/95
Author:
Scott Hudson
Definition at line 13 of file lalr_transition.java.
Constructor & Destructor Documentation
java_cup.lalr_transition.lalr_transition (symbol on_sym, lalr_state to_st, lalr_transition nxt) throws internal_error
Full constructor.
Parameters:
on_sym symbol we are transitioning on.
to_st state we transition to.
nxt next transition in linked list.
Definition at line 24 of file lalr_transition.java.
References java_cup.lalr_transition._next, java_cup.lalr_transition._on_symbol, and java_cup.lalr_transition._to_state.
java_cup.lalr_transition.lalr_transition (symbol on_sym, lalr_state to_st) throws internal_error
Constructor with null next.
Parameters:
on_sym symbol we are transitioning on.
to_st state we transition to.
Definition at line 45 of file lalr_transition.java.
Member Function Documentation
lalr_transition java_cup.lalr_transition.next ()
Next transition in linked list of transitions out of a state
Definition at line 74 of file lalr_transition.java.
References java_cup.lalr_transition._next.
Referenced by java_cup.lalr_state.build_table_entries(), and java_cup.lalr_state.toString().
symbol java_cup.lalr_transition.on_symbol ()
The symbol we make the transition on.
Definition at line 58 of file lalr_transition.java.
References java_cup.lalr_transition._on_symbol.
Referenced by java_cup.lalr_transition.toString().
lalr_state java_cup.lalr_transition.to_state ()
The state we transition to.
Definition at line 66 of file lalr_transition.java.
References java_cup.lalr_transition._to_state.
String java_cup.lalr_transition.toString ()
Convert to a string.
Definition at line 81 of file lalr_transition.java.
References java_cup.lalr_transition._to_state, java_cup.lalr_state.index(), java_cup.symbol.name(), and java_cup.lalr_transition.on_symbol().
Member Data Documentation
lalr_transition java_cup.lalr_transition._next [protected]
Next transition in linked list of transitions out of a state
Definition at line 71 of file lalr_transition.java.
Referenced by java_cup.lalr_transition.lalr_transition(), and java_cup.lalr_transition.next().
symbol java_cup.lalr_transition._on_symbol [protected]
The symbol we make the transition on.
Definition at line 55 of file lalr_transition.java.
Referenced by java_cup.lalr_transition.lalr_transition(), and java_cup.lalr_transition.on_symbol().
lalr_state java_cup.lalr_transition._to_state [protected]
The state we transition to.
Definition at line 63 of file lalr_transition.java.
Referenced by java_cup.lalr_transition.lalr_transition(), java_cup.lalr_transition.to_state(), and java_cup.lalr_transition.toString().
The documentation for this class was generated from the following file:
src/java_cup/lalr_transition.java