Jamus Scheme: java_cup.lexer Class Reference
java_cup.lexer Class Reference
Static Public Member Functions
static void init (BufferedInputStream b) throws java.io.IOException
static void emit_error (String message)
static void emit_warn (String message)
static Symbol next_token () throws java.io.IOException
static Symbol debug_next_token () throws java.io.IOException
Static Public Attributes
static int error_count = 0
static int warning_count = 0
static BufferedInputStream bis
Static Protected Member Functions
static void advance () throws java.io.IOException
static boolean id_start_char (int ch)
static boolean id_char (int ch)
static int find_single_char (int ch)
static void swallow_comment () throws java.io.IOException
static Symbol do_code_string () throws java.io.IOException
static Symbol do_id () throws java.io.IOException
static Symbol real_next_token () throws java.io.IOException
Static Protected Attributes
static int next_char
static int next_char2
static int next_char3
static int next_char4
static final int EOF_CHAR = -1
static Hashtable keywords = new Hashtable(23)
static Hashtable char_symbols = new Hashtable(11)
static int current_line = 1
static int current_position = 1
static int absolute_position = 1
Private Member Functions
lexer ()
Detailed Description
This class implements a small scanner (aka lexical analyzer or lexer) for the JavaCup specification. This scanner reads characters from standard input (System.in) and returns integers corresponding to the terminal number of the next Symbol. Once end of input is reached the EOF Symbol is returned on every subsequent call.
Symbols currently returned include:
    Symbol        Constant Returned     Symbol        Constant Returned
    ------        -----------------     ------        -----------------
    "package"     PACKAGE               "import"      IMPORT
    "code"        CODE                  "action"      ACTION
    "parser"      PARSER                "terminal"    TERMINAL
    "non"         NON                   "init"        INIT
    "scan"        SCAN                  "with"        WITH
    "start"       START                 "precedence"  PRECEDENCE
    "left"        LEFT          "right"       RIGHT
    "nonassoc"    NONASSOC          "prec        PRECENT_PREC
      [           LBRACK                  ]           RBRACK
      ;           SEMI
      ,           COMMA                   *           STAR
      .           DOT                     :           COLON
      ::=         COLON_COLON_EQUALS      |           BAR
    identifier    ID                    {:...:}       CODE_STRING
    "nonterminal" NONTERMINAL
All symbol constants are defined in sym.java which is generated by JavaCup from parser.cup.
In addition to the scanner proper (called first via init() then with next_token() to get each Symbol) this class provides simple error and warning routines and keeps a count of errors and warnings that is publicly accessible.
This class is "static" (i.e., it has only static members and methods).
Version:
last updated: 7/3/96
Author:
Frank Flannery
Definition at line 44 of file lexer.java.
Constructor & Destructor Documentation
java_cup.lexer.lexer () [private]
The only constructor is private, so no instances can be created.
Definition at line 51 of file lexer.java.
Member Function Documentation
static void java_cup.lexer.advance () throws java.io.IOException [static, protected]
Advance the scanner one character in the input stream. This moves next_char2 to next_char and then reads a new next_char2.
Definition at line 190 of file lexer.java.
References java_cup.lexer.absolute_position, java_cup.lexer.bis, java_cup.lexer.current_line, java_cup.lexer.current_position, java_cup.lexer.EOF_CHAR, java_cup.lexer.next_char, java_cup.lexer.next_char2, java_cup.lexer.next_char3, and java_cup.lexer.next_char4.
Referenced by java_cup.lexer.do_code_string(), java_cup.lexer.do_id(), java_cup.lexer.real_next_token(), and java_cup.lexer.swallow_comment().
static Symbol java_cup.lexer.debug_next_token () throws java.io.IOException [static]
Debugging version of next_token(). This routine calls the real scanning routine, prints a message on System.out indicating what the Symbol is, then returns it.
Definition at line 446 of file lexer.java.
References java_cup.lexer.real_next_token(), and java_cup.runtime.Symbol.sym.
static Symbol java_cup.lexer.do_code_string () throws java.io.IOException [static, protected]
Swallow up a code string. Code strings begin with "{:" and include all characters up to the first occurrence of ":}" (there is no way to include ":}" inside a code string). The routine returns a String object suitable for return by the scanner.
Definition at line 360 of file lexer.java.
References java_cup.lexer.advance(), java_cup.sym.CODE_STRING, java_cup.lexer.emit_error(), java_cup.lexer.EOF_CHAR, java_cup.lexer.next_char, and java_cup.lexer.next_char2.
Referenced by java_cup.lexer.real_next_token().
static Symbol java_cup.lexer.do_id () throws java.io.IOException [static, protected]
Process an identifier. Identifiers begin with a letter, underscore, or dollar sign, which is followed by zero or more letters, numbers, underscores or dollar signs. This routine returns a String suitable for return by the scanner.
Definition at line 394 of file lexer.java.
References java_cup.lexer.advance(), java_cup.sym.ID, java_cup.lexer.id_char(), java_cup.lexer.keywords, and java_cup.lexer.next_char.
Referenced by java_cup.lexer.real_next_token().
static void java_cup.lexer.emit_error (String message) [static]
Emit an error message. The message will be marked with both the current line number and the position in the line. Error messages are printed on standard error (System.err).
Parameters:
message the message to print.
Definition at line 233 of file lexer.java.
References java_cup.lexer.current_line, java_cup.lexer.current_position, and java_cup.lexer.error_count.
Referenced by java_cup.$actions.$do_action(), java_cup.lexer.do_code_string(), java_cup.Main.parse_grammar_spec(), java_cup.lexer.real_next_token(), java_cup.parser.report_error(), java_cup.parser.report_fatal_error(), and java_cup.lexer.swallow_comment().
static void java_cup.lexer.emit_warn (String message) [static]
Emit a warning message. The message will be marked with both the current line number and the position in the line. Messages are printed on standard error (System.err).
Parameters:
message the message to print.
Definition at line 247 of file lexer.java.
References java_cup.lexer.current_line, java_cup.lexer.current_position, and java_cup.lexer.warning_count.
Referenced by java_cup.lexer.real_next_token().
static int java_cup.lexer.find_single_char (int ch) [static, protected]
Try to look up a single character symbol, returns -1 for not found.
Parameters:
ch the character in question.
Definition at line 285 of file lexer.java.
References java_cup.lexer.char_symbols.
Referenced by java_cup.lexer.real_next_token().
static boolean java_cup.lexer.id_char (int ch) [static, protected]
Determine if a character is ok for the middle of an id.
Parameters:
ch the character in question.
Definition at line 275 of file lexer.java.
References java_cup.lexer.id_start_char().
Referenced by java_cup.lexer.do_id().
static boolean java_cup.lexer.id_start_char (int ch) [static, protected]
Determine if a character is ok to start an id.
Parameters:
ch the character in question.
Definition at line 259 of file lexer.java.
Referenced by java_cup.lexer.id_char(), and java_cup.lexer.real_next_token().
static void java_cup.lexer.init (BufferedInputStream b) throws java.io.IOException [static]
Initialize the scanner. This sets up the keywords and char_symbols tables and reads the first two characters of lookahead.
Definition at line 128 of file lexer.java.
References java_cup.sym.ACTION, java_cup.sym.BAR, java_cup.lexer.bis, java_cup.lexer.char_symbols, java_cup.sym.CODE, java_cup.sym.COMMA, java_cup.sym.DOT, java_cup.lexer.EOF_CHAR, java_cup.sym.IMPORT, java_cup.sym.INIT, java_cup.lexer.keywords, java_cup.sym.LBRACK, java_cup.sym.LEFT, java_cup.lexer.next_char, java_cup.lexer.next_char2, java_cup.lexer.next_char3, java_cup.lexer.next_char4, java_cup.sym.NON, java_cup.sym.NONASSOC, java_cup.sym.NONTERMINAL, java_cup.sym.PACKAGE, java_cup.sym.PARSER, java_cup.sym.PRECEDENCE, java_cup.sym.RBRACK, java_cup.sym.RIGHT, java_cup.sym.SCAN, java_cup.sym.SEMI, java_cup.sym.STAR, java_cup.sym.START, java_cup.sym.TERMINAL, and java_cup.sym.WITH.
Referenced by java_cup.parser.user_init().
static Symbol java_cup.lexer.next_token () throws java.io.IOException [static]
Return one Symbol. This is the main external interface to the scanner. It consumes sufficient characters to determine the next input Symbol and returns it. To help with debugging, this routine actually calls real_next_token() which does the work. If you need to debug the parser, this can be changed to call debug_next_token() which prints a debugging message before returning the Symbol.
Definition at line 435 of file lexer.java.
References java_cup.lexer.real_next_token().
Referenced by java_cup.parser.scan().
static Symbol java_cup.lexer.real_next_token () throws java.io.IOException [static, protected]
The actual routine to return one Symbol. This is normally called from next_token(), but for debugging purposes can be called indirectly from debug_next_token().
Definition at line 459 of file lexer.java.
References java_cup.lexer.advance(), java_cup.sym.COLON, java_cup.sym.COLON_COLON_EQUALS, java_cup.lexer.do_code_string(), java_cup.lexer.do_id(), java_cup.lexer.emit_error(), java_cup.lexer.emit_warn(), java_cup.sym.EOF, java_cup.lexer.EOF_CHAR, java_cup.lexer.find_single_char(), java_cup.lexer.id_start_char(), java_cup.lexer.next_char, java_cup.lexer.next_char2, java_cup.lexer.next_char3, java_cup.lexer.next_char4, java_cup.sym.PERCENT_PREC, and java_cup.lexer.swallow_comment().
Referenced by java_cup.lexer.debug_next_token(), and java_cup.lexer.next_token().
static void java_cup.lexer.swallow_comment () throws java.io.IOException [static, protected]
Handle swallowing up a comment. Both old style C and new style C++ comments are handled.
Definition at line 301 of file lexer.java.
References java_cup.lexer.advance(), java_cup.lexer.emit_error(), java_cup.lexer.EOF_CHAR, java_cup.lexer.next_char, and java_cup.lexer.next_char2.
Referenced by java_cup.lexer.real_next_token().
Member Data Documentation
int java_cup.lexer.absolute_position = 1 [static, protected]
Character position in current line.
Definition at line 106 of file lexer.java.
Referenced by java_cup.lexer.advance().
BufferedInputStream java_cup.lexer.bis [static]
Definition at line 118 of file lexer.java.
Referenced by java_cup.lexer.advance(), and java_cup.lexer.init().
Hashtable java_cup.lexer.char_symbols = new Hashtable(11) [static, protected]
Table of single character symbols. For ease of implementation, we store all unambiguous single character Symbols in this table of Integer objects keyed by Integer objects with the numerical value of the appropriate char (currently Character objects have a bug which precludes their use in tables).
Definition at line 91 of file lexer.java.
Referenced by java_cup.lexer.find_single_char(), and java_cup.lexer.init().
int java_cup.lexer.current_line = 1 [static, protected]
Current line number for use in error messages.
Definition at line 96 of file lexer.java.
Referenced by java_cup.lexer.advance(), java_cup.lexer.emit_error(), and java_cup.lexer.emit_warn().
int java_cup.lexer.current_position = 1 [static, protected]
Character position in current line.
Definition at line 101 of file lexer.java.
Referenced by java_cup.lexer.advance(), java_cup.lexer.emit_error(), and java_cup.lexer.emit_warn().
final int java_cup.lexer.EOF_CHAR = -1 [static, protected]
EOF constant.
Definition at line 72 of file lexer.java.
Referenced by java_cup.lexer.advance(), java_cup.lexer.do_code_string(), java_cup.lexer.init(), java_cup.lexer.real_next_token(), and java_cup.lexer.swallow_comment().
int java_cup.lexer.error_count = 0 [static]
Count of total errors detected so far.
Definition at line 111 of file lexer.java.
Referenced by java_cup.$actions.$do_action(), java_cup.Main.build_parser(), java_cup.lexer.emit_error(), java_cup.Main.emit_summary(), and java_cup.Main.main().
Hashtable java_cup.lexer.keywords = new Hashtable(23) [static, protected]
Table of keywords. Keywords are initially treated as identifiers. Just before they are returned we look them up in this table to see if they match one of the keywords. The string of the name is the key here, which indexes Integer objects holding the symbol number.
Definition at line 81 of file lexer.java.
Referenced by java_cup.lexer.do_id(), and java_cup.lexer.init().
int java_cup.lexer.next_char [static, protected]
First character of lookahead.
Definition at line 58 of file lexer.java.
Referenced by java_cup.lexer.advance(), java_cup.lexer.do_code_string(), java_cup.lexer.do_id(), java_cup.lexer.init(), java_cup.lexer.real_next_token(), and java_cup.lexer.swallow_comment().
int java_cup.lexer.next_char2 [static, protected]
Second character of lookahead.
Definition at line 61 of file lexer.java.
Referenced by java_cup.lexer.advance(), java_cup.lexer.do_code_string(), java_cup.lexer.init(), java_cup.lexer.real_next_token(), and java_cup.lexer.swallow_comment().
int java_cup.lexer.next_char3 [static, protected]
Second character of lookahead.
Definition at line 64 of file lexer.java.
Referenced by java_cup.lexer.advance(), java_cup.lexer.init(), and java_cup.lexer.real_next_token().
int java_cup.lexer.next_char4 [static, protected]
Second character of lookahead.
Definition at line 67 of file lexer.java.
Referenced by java_cup.lexer.advance(), java_cup.lexer.init(), and java_cup.lexer.real_next_token().
int java_cup.lexer.warning_count = 0 [static]
Count of warnings issued so far
Definition at line 116 of file lexer.java.
Referenced by java_cup.parse_action_table.check_reductions(), java_cup.Main.check_unused(), java_cup.Main.emit_summary(), java_cup.lexer.emit_warn(), java_cup.lalr_state.report_reduce_reduce(), and java_cup.lalr_state.report_shift_reduce().
The documentation for this class was generated from the following file:
src/java_cup/lexer.java