Jamus Scheme: java_cup.symbol_set Class Reference
java_cup.symbol_set Class Reference
Public Member Functions
symbol_set ()
symbol_set (symbol_set other) throws internal_error
Enumeration all ()
int size ()
boolean contains (symbol sym)
boolean is_subset_of (symbol_set other) throws internal_error
boolean is_superset_of (symbol_set other) throws internal_error
boolean add (symbol sym) throws internal_error
void remove (symbol sym) throws internal_error
boolean add (symbol_set other) throws internal_error
void remove (symbol_set other) throws internal_error
boolean equals (symbol_set other)
boolean equals (Object other)
int hashCode ()
String toString ()
Protected Member Functions
void not_null (Object obj) throws internal_error
Protected Attributes
Hashtable _all = new Hashtable(11)
Detailed Description
This class represents a set of symbols and provides a series of set operations to manipulate them.
See also:
java_cup.symbol
Version:
last updated: 11/25/95
Author:
Scott Hudson
Definition at line 14 of file symbol_set.java.
Constructor & Destructor Documentation
java_cup.symbol_set.symbol_set ()
Constructor for an empty set.
Definition at line 21 of file symbol_set.java.
java_cup.symbol_set.symbol_set (symbol_set other) throws internal_error
Constructor for cloning from another set.
Parameters:
other the set we are cloning from.
Definition at line 26 of file symbol_set.java.
References java_cup.symbol_set._all, and java_cup.symbol_set.not_null().
Member Function Documentation
boolean java_cup.symbol_set.add (symbol sym) throws internal_error
Add a single symbol to the set.
Parameters:
sym the symbol we are adding.
Returns:
true if this changes the set.
Definition at line 102 of file symbol_set.java.
References java_cup.symbol_set._all, and java_cup.symbol_set.not_null().
Referenced by java_cup.symbol_set.add(), and java_cup.lalr_state.build_machine().
boolean java_cup.symbol_set.add (symbol_set other) throws internal_error
Add (union) in a complete set.
Parameters:
other the set we are adding in.
Returns:
true if this changes the set.
Definition at line 132 of file symbol_set.java.
References java_cup.symbol_set.add(), and java_cup.symbol_set.not_null().
Enumeration java_cup.symbol_set.all ()
Access to all elements of the set.
Definition at line 41 of file symbol_set.java.
References java_cup.symbol_set._all.
Referenced by java_cup.lalr_state.build_machine(), java_cup.symbol_set.hashCode(), java_cup.symbol_set.is_subset_of(), and java_cup.symbol_set.toString().
boolean java_cup.symbol_set.contains (symbol sym)
Determine if the set contains a particular symbol.
Parameters:
sym the symbol we are looking for.
Definition at line 65 of file symbol_set.java.
References java_cup.symbol_set._all, and java_cup.symbol.name().
boolean java_cup.symbol_set.equals (symbol_set other)
Equality comparison.
Definition at line 162 of file symbol_set.java.
References java_cup.internal_error.crash(), java_cup.symbol_set.is_subset_of(), and java_cup.symbol_set.size().
Referenced by java_cup.symbol_set.equals().
boolean java_cup.symbol_set.equals (Object other)
Generic equality comparison.
Definition at line 179 of file symbol_set.java.
References java_cup.symbol_set.equals().
int java_cup.symbol_set.hashCode ()
Compute a hash code.
Definition at line 190 of file symbol_set.java.
References java_cup.symbol_set.all().
boolean java_cup.symbol_set.is_subset_of (symbol_set other) throws internal_error
Determine if this set is an (improper) subset of another.
Parameters:
other the set we are testing against.
Definition at line 72 of file symbol_set.java.
References java_cup.symbol_set.all(), and java_cup.symbol_set.not_null().
Referenced by java_cup.symbol_set.equals().
boolean java_cup.symbol_set.is_superset_of (symbol_set other) throws internal_error
Determine if this set is an (improper) superset of another.
Parameters:
other the set we are are testing against.
Definition at line 90 of file symbol_set.java.
References java_cup.symbol_set.not_null().
void java_cup.symbol_set.not_null (Object obj) throws internal_error [protected]
Helper function to test for a null object and throw an exception if one is found.
Parameters:
obj the object we are testing.
Definition at line 54 of file symbol_set.java.
Referenced by java_cup.symbol_set.add(), java_cup.symbol_set.is_subset_of(), java_cup.symbol_set.is_superset_of(), java_cup.symbol_set.remove(), and java_cup.symbol_set.symbol_set().
void java_cup.symbol_set.remove (symbol sym) throws internal_error
Remove a single symbol if it is in the set.
Parameters:
sym the symbol we are removing.
Definition at line 120 of file symbol_set.java.
References java_cup.symbol_set._all, and java_cup.symbol_set.not_null().
void java_cup.symbol_set.remove (symbol_set other) throws internal_error
Remove (set subtract) a complete set.
Parameters:
other the set we are removing.
Definition at line 150 of file symbol_set.java.
References java_cup.symbol_set.not_null().
int java_cup.symbol_set.size ()
size of the set
Definition at line 44 of file symbol_set.java.
References java_cup.symbol_set._all.
Referenced by java_cup.symbol_set.equals().
String java_cup.symbol_set.toString ()
Convert to a string.
Definition at line 206 of file symbol_set.java.
References java_cup.symbol_set.all().
Member Data Documentation
Hashtable java_cup.symbol_set._all = new Hashtable(11) [protected]
A hash table to hold the set. Symbols are keyed using their name string.
Definition at line 38 of file symbol_set.java.
Referenced by java_cup.symbol_set.add(), java_cup.symbol_set.all(), java_cup.symbol_set.contains(), java_cup.symbol_set.remove(), java_cup.symbol_set.size(), and java_cup.symbol_set.symbol_set().
The documentation for this class was generated from the following file:
src/java_cup/symbol_set.java