Jamus Scheme: Scheme.SchemeObject Interface Reference
Scheme.SchemeObject Interface Reference
Public Member Functions
SchemeObject expand ()
SchemeObject eval ()
boolean nullp ()
SchemeBoolean not ()
Pair cons (SchemeObject x)
void print ()
SchemeObject printp (BufferedWriter open_buffer_writer)
SchemeBoolean pairp ()
SchemeBoolean symbolp ()
SchemeString symbolstring ()
SchemeString numberstring ()
SchemeBoolean numberp ()
SchemeBoolean listp ()
SchemeBoolean integerp ()
SchemeBoolean realp ()
SchemeBoolean zerop ()
SchemeBoolean negativep ()
SchemeBoolean nullpp ()
SchemeBoolean eqp (SchemeObject o)
Symbol stringsymbol ()
SchemeBoolean equalp (SchemeObject o)
SchemeObject expandall ()
Detailed Description
Author:
mkain
Definition at line 10 of file SchemeObject.java.
Member Function Documentation
Pair Scheme.SchemeObject.cons (SchemeObject x)
Implemented in Scheme.SchemePort, Scheme.SchemeFunction, Scheme.SchemeDouble, Scheme.SchemeNumber, Scheme.SchemeInteger, Scheme.SchemeString, Scheme.Symbol, Scheme.SchemeBoolean, Scheme.Pair, Scheme.Pair, and Scheme.Function.
Referenced by Scheme.RunEnv.bind(), Scheme.RunEnv.bind1(), Scheme.Pair.evlis(), Scheme.RunEnv.intern(), and Scheme.Pair.vl().
SchemeBoolean Scheme.SchemeObject.eqp (SchemeObject o)
Implemented in Scheme.SchemePort, Scheme.SchemeString, Scheme.SchemeFunction, Scheme.Symbol, Scheme.Function, Scheme.SchemeBoolean, Scheme.Pair, Scheme.SchemeDouble, Scheme.SchemeNumber, Scheme.SchemeInteger, and Scheme.Pair.
SchemeBoolean Scheme.SchemeObject.equalp (SchemeObject o)
Implemented in Scheme.SchemePort, Scheme.SchemeString, Scheme.SchemeFunction, Scheme.Symbol, Scheme.Function, Scheme.SchemeBoolean, Scheme.Pair, Scheme.SchemeDouble, Scheme.SchemeNumber, Scheme.SchemeInteger, and Scheme.Pair.
Referenced by Scheme.Pair.assoc().
SchemeObject Scheme.SchemeObject.eval ()
Implemented in Scheme.Pair, Scheme.Pair, Scheme.SchemeFunction, Scheme.SchemePort, Scheme.SchemeDouble, Scheme.SchemeNumber, Scheme.SchemeInteger, Scheme.Function, Scheme.SchemeString, and Scheme.SchemeBoolean.
Referenced by Scheme.Pair.apply(), Scheme.Pair.eval(), and Scheme.Pair.treeeval().
SchemeObject Scheme.SchemeObject.expand ()
Implemented in Scheme.Pair, Scheme.Pair, Scheme.SchemeFunction, Scheme.SchemePort, Scheme.SchemeDouble, Scheme.SchemeBoolean, Scheme.SchemeNumber, Scheme.SchemeInteger, and Scheme.SchemeString.
Referenced by Scheme.Pair.eval(), and Scheme.Pair.treeeval().
SchemeObject Scheme.SchemeObject.expandall ()
Implemented in Scheme.Pair, Scheme.SchemeFunction, Scheme.SchemeBoolean, Scheme.SchemeDouble, Scheme.SchemeNumber, Scheme.SchemeInteger, and Scheme.SchemeString.
SchemeBoolean Scheme.SchemeObject.integerp ()
Implemented in Scheme.Pair, Scheme.SchemePort, Scheme.SchemeDouble, Scheme.SchemeNumber, Scheme.SchemeInteger, Scheme.Symbol, and Scheme.SchemeString.
SchemeBoolean Scheme.SchemeObject.listp ()
Implemented in Scheme.Pair, Scheme.SchemeFunction, Scheme.SchemePort, Scheme.SchemeDouble, Scheme.SchemeNumber, Scheme.SchemeInteger, Scheme.SchemeBoolean, Scheme.Symbol, and Scheme.SchemeString.
SchemeBoolean Scheme.SchemeObject.negativep ()
Implemented in Scheme.Pair, Scheme.SchemeDouble, Scheme.SchemeNumber, Scheme.SchemeInteger, and Scheme.SchemeString.
SchemeBoolean Scheme.SchemeObject.not ()
Implemented in Scheme.Pair, Scheme.Pair, Scheme.SchemePort, Scheme.SchemeFunction, Scheme.SchemeBoolean, Scheme.SchemeDouble, Scheme.SchemeNumber, Scheme.Symbol, Scheme.SchemeInteger, Scheme.SchemeString, and Scheme.Function.
boolean Scheme.SchemeObject.nullp ()
Implemented in Scheme.Pair, Scheme.Pair, Scheme.SchemePort, Scheme.SchemeFunction, Scheme.SchemeBoolean, Scheme.SchemeDouble, Scheme.SchemeNumber, Scheme.SchemeInteger, Scheme.Symbol, Scheme.SchemeString, and Scheme.Function.
Referenced by Scheme.RunEnv.checkbucket(), Scheme.Pair.equalp(), Scheme.Pair.eval(), Scheme.RunEnv.intern(), and Scheme.Pair.searchv().
SchemeBoolean Scheme.SchemeObject.nullpp ()
Implemented in Scheme.Pair, Scheme.SchemeString, Scheme.SchemePort, Scheme.SchemeFunction, Scheme.SchemeDouble, Scheme.SchemeNumber, Scheme.SchemeInteger, Scheme.SchemeBoolean, and Scheme.Symbol.
SchemeBoolean Scheme.SchemeObject.numberp ()
Implemented in Scheme.Pair, Scheme.SchemeDouble, Scheme.SchemeFunction, Scheme.SchemeNumber, Scheme.SchemeInteger, Scheme.SchemeString, and Scheme.SchemeBoolean.
SchemeString Scheme.SchemeObject.numberstring ()
Implemented in Scheme.Pair, Scheme.SchemePort, Scheme.SchemeFunction, Scheme.SchemeDouble, Scheme.SchemeInteger, Scheme.SchemeNumber, Scheme.SchemeString, Scheme.Symbol, Scheme.SchemeBoolean, and Scheme.Function.
SchemeBoolean Scheme.SchemeObject.pairp ()
Implemented in Scheme.Pair, Scheme.Pair, Scheme.SchemePort, Scheme.SchemeFunction, Scheme.SchemeDouble, Scheme.SchemeNumber, Scheme.SchemeInteger, Scheme.SchemeString, Scheme.SchemeBoolean, Scheme.Symbol, and Scheme.Function.
void Scheme.SchemeObject.print ()
Implemented in Scheme.Pair, Scheme.Pair, Scheme.SchemeFunction, Scheme.SchemePort, Scheme.SchemeBoolean, Scheme.SchemeDouble, Scheme.SchemeNumber, Scheme.SchemeInteger, Scheme.Symbol, Scheme.SchemeString, and Scheme.Function.
Referenced by Scheme.$actions.$do_action(), Scheme.RunEnv.display(), Scheme.Pair.lettwo(), Scheme.Pair.treeeval(), and Scheme.RunEnv.write().
SchemeObject Scheme.SchemeObject.printp (BufferedWriter open_buffer_writer)
Implemented in Scheme.Pair, Scheme.SchemePort, Scheme.SchemeFunction, Scheme.SchemeString, Scheme.SchemeDouble, Scheme.SchemeNumber, Scheme.SchemeInteger, and Scheme.Symbol.
Referenced by Scheme.RunEnv.display(), and Scheme.RunEnv.write().
SchemeBoolean Scheme.SchemeObject.realp ()
Implemented in Scheme.Pair, Scheme.SchemePort, Scheme.SchemeFunction, Scheme.Symbol, Scheme.SchemeDouble, Scheme.SchemeNumber, Scheme.SchemeInteger, Scheme.SchemeBoolean, Scheme.Function, and Scheme.SchemeString.
Symbol Scheme.SchemeObject.stringsymbol ()
Implemented in Scheme.Pair, Scheme.SchemeFunction, Scheme.SchemePort, Scheme.SchemeNumber, Scheme.Symbol, Scheme.SchemeString, Scheme.SchemeBoolean, and Scheme.Function.
SchemeBoolean Scheme.SchemeObject.symbolp ()
Implemented in Scheme.Pair, Scheme.Pair, Scheme.SchemePort, Scheme.SchemeFunction, Scheme.SchemeDouble, Scheme.SchemeNumber, Scheme.SchemeInteger, Scheme.SchemeString, Scheme.SchemeBoolean, Scheme.Symbol, and Scheme.Function.
SchemeString Scheme.SchemeObject.symbolstring ()
Implemented in Scheme.Pair, Scheme.SchemeDouble, Scheme.SchemeNumber, and Scheme.SchemeInteger.
SchemeBoolean Scheme.SchemeObject.zerop ()
Implemented in Scheme.Pair, Scheme.Pair, Scheme.SchemePort, Scheme.SchemeFunction, Scheme.SchemeDouble, Scheme.SchemeNumber, Scheme.SchemeInteger, Scheme.SchemeString, and Scheme.SchemeBoolean.
The documentation for this interface was generated from the following file:
src/Scheme/SchemeObject.java