Jamus Scheme: java_cup.runtime.virtual_parse_stack Class Reference
java_cup.runtime.virtual_parse_stack Class Reference
Public Member Functions
virtual_parse_stack (Stack shadowing_stack) throws java.lang.Exception
boolean empty ()
int top () throws java.lang.Exception
void pop () throws java.lang.Exception
void push (int state_num)
Protected Member Functions
void get_from_real ()
Protected Attributes
Stack real_stack
int real_next
Stack vstack
Detailed Description
This class implements a temporary or "virtual" parse stack that replaces the top portion of the actual parse stack (the part that has been changed by some set of operations) while maintaining its original contents. This data structure is used when the parse needs to "parse ahead" to determine if a given error recovery attempt will allow the parse to continue far enough to consider it successful. Once success or failure of parse ahead is determined the system then reverts to the original parse stack (which has not actually been modified). Since parse ahead does not execute actions, only parse state is maintained on the virtual stack, not full Symbol objects.
See also:
java_cup.runtime.lr_parser
Version:
last updated: 7/3/96
Author:
Frank Flannery
Definition at line 22 of file virtual_parse_stack.java.
Constructor & Destructor Documentation
java_cup.runtime.virtual_parse_stack.virtual_parse_stack (Stack shadowing_stack) throws java.lang.Exception
Constructor to build a virtual stack out of a real stack.
Definition at line 28 of file virtual_parse_stack.java.
References java_cup.runtime.virtual_parse_stack.get_from_real(), java_cup.runtime.virtual_parse_stack.real_next, java_cup.runtime.virtual_parse_stack.real_stack, and java_cup.runtime.virtual_parse_stack.vstack.
Member Function Documentation
boolean java_cup.runtime.virtual_parse_stack.empty ()
Indicate whether the stack is empty.
Definition at line 99 of file virtual_parse_stack.java.
References java_cup.runtime.virtual_parse_stack.vstack.
void java_cup.runtime.virtual_parse_stack.get_from_real () [protected]
Transfer an element from the real to the virtual stack. This assumes that the virtual stack is currently empty.
Definition at line 79 of file virtual_parse_stack.java.
References java_cup.runtime.Symbol.parse_state, java_cup.runtime.virtual_parse_stack.real_next, java_cup.runtime.virtual_parse_stack.real_stack, and java_cup.runtime.virtual_parse_stack.vstack.
Referenced by java_cup.runtime.virtual_parse_stack.pop(), and java_cup.runtime.virtual_parse_stack.virtual_parse_stack().
void java_cup.runtime.virtual_parse_stack.pop () throws java.lang.Exception
Pop the stack.
Definition at line 121 of file virtual_parse_stack.java.
References java_cup.runtime.virtual_parse_stack.get_from_real(), and java_cup.runtime.virtual_parse_stack.vstack.
Referenced by java_cup.runtime.lr_parser.try_parse_ahead().
void java_cup.runtime.virtual_parse_stack.push (int state_num)
Push a state number onto the stack.
Definition at line 138 of file virtual_parse_stack.java.
References java_cup.runtime.virtual_parse_stack.vstack.
Referenced by java_cup.runtime.lr_parser.try_parse_ahead().
int java_cup.runtime.virtual_parse_stack.top () throws java.lang.Exception
Return value on the top of the stack (without popping it).
Definition at line 109 of file virtual_parse_stack.java.
References java_cup.runtime.virtual_parse_stack.vstack.
Referenced by java_cup.runtime.lr_parser.try_parse_ahead().
Member Data Documentation
int java_cup.runtime.virtual_parse_stack.real_next [protected]
Top of stack indicator for where we leave off in the real stack. This is measured from top of stack, so 0 would indicate that no elements have been "moved" from the real to virtual stack.
Definition at line 60 of file virtual_parse_stack.java.
Referenced by java_cup.runtime.virtual_parse_stack.get_from_real(), and java_cup.runtime.virtual_parse_stack.virtual_parse_stack().
Stack java_cup.runtime.virtual_parse_stack.real_stack [protected]
The real stack that we shadow. This is accessed when we move off the bottom of the virtual portion of the stack, but is always left unmodified.
Definition at line 52 of file virtual_parse_stack.java.
Referenced by java_cup.runtime.virtual_parse_stack.get_from_real(), and java_cup.runtime.virtual_parse_stack.virtual_parse_stack().
Stack java_cup.runtime.virtual_parse_stack.vstack [protected]
The virtual top portion of the stack. This stack contains Integer objects with state numbers. This stack shadows the top portion of the real stack within the area that has been modified (via operations on the virtual stack). When this portion of the stack becomes empty we transfer elements from the underlying stack onto this stack.
Definition at line 70 of file virtual_parse_stack.java.
Referenced by java_cup.runtime.virtual_parse_stack.empty(), java_cup.runtime.virtual_parse_stack.get_from_real(), java_cup.runtime.virtual_parse_stack.pop(), java_cup.runtime.virtual_parse_stack.push(), java_cup.runtime.virtual_parse_stack.top(), and java_cup.runtime.virtual_parse_stack.virtual_parse_stack().
The documentation for this class was generated from the following file:
src/java_cup/runtime/virtual_parse_stack.java