/**
 * generated by Xtext 2.11.0
 */
package de.htwdd.sf.beleg.scoping;

import de.htwdd.sf.beleg.scoping.AbstractCustomPrologScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class CustomPrologScopeProvider extends AbstractCustomPrologScopeProvider {
}
