/**
 * generated by Xtext 2.11.0
 */
package de.htwdd.sf.beleg.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.htwdd.sf.beleg.CustomPrologRuntimeModule;
import de.htwdd.sf.beleg.CustomPrologStandaloneSetup;
import de.htwdd.sf.beleg.ide.CustomPrologIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class CustomPrologIdeSetup extends CustomPrologStandaloneSetup {
  @Override
  public Injector createInjector() {
    CustomPrologRuntimeModule _customPrologRuntimeModule = new CustomPrologRuntimeModule();
    CustomPrologIdeModule _customPrologIdeModule = new CustomPrologIdeModule();
    return Guice.createInjector(Modules2.mixin(_customPrologRuntimeModule, _customPrologIdeModule));
  }
}
