/**
 * generated by Xtext 2.11.0
 */
package de.htwdd.sf.beleg.ide;

import de.htwdd.sf.beleg.ide.AbstractCustomPrologIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CustomPrologIdeModule extends AbstractCustomPrologIdeModule {
}
