Jamus Scheme: Scheme.Stack Class Reference
Scheme.Stack Class Reference
Public Member Functions
Stack (int max_elements)
void push (Object elem)
void pop ()
Object top ()
boolean empty ()
Private Attributes
int size = 0
int maxelem = 10
List stacklist = new List()
Detailed Description
The Scheme run environment needs a stack to organize the expressions.
Definition at line 7 of file Stack.java.
Constructor & Destructor Documentation
Scheme.Stack.Stack (int max_elements)
Construct a new stack with maximal elements.
Parameters:
max_elements the maximal elements on stack.
Definition at line 23 of file Stack.java.
References Scheme.Stack.maxelem.
Member Function Documentation
boolean Scheme.Stack.empty ()
Check if the stack is empty (there is no element on stack).
Returns:
true, if the stack is empty, else false.
Implements Scheme.IStack.
Definition at line 59 of file Stack.java.
References Scheme.Stack.size.
Referenced by Scheme.Pair.eval(), Scheme.Stack.pop(), Scheme.Pair.searchb(), and Scheme.Stack.top().
void Scheme.Stack.pop ()
Removes the element on top of the stack.
Implements Scheme.IStack.
Definition at line 39 of file Stack.java.
References Scheme.List.cdr, Scheme.Stack.empty(), Scheme.Stack.size, and Scheme.Stack.stacklist.
Referenced by Scheme.Pair.searchb(), Scheme.RunEnv.unbind(), and Scheme.RunEnv.unbind1().
void Scheme.Stack.push (Object elem)
Pushs a new element to the top of the stack.
Parameters:
elem the new element
Implements Scheme.IStack.
Definition at line 28 of file Stack.java.
References Scheme.List.cons(), Scheme.Stack.maxelem, Scheme.Stack.size, and Scheme.Stack.stacklist.
Referenced by Scheme.RunEnv.bind(), and Scheme.RunEnv.bind1().
Object Scheme.Stack.top ()
Get the element on top of the stack.
Returns:
the top element
Implements Scheme.IStack.
Definition at line 50 of file Stack.java.
References Scheme.List.car, Scheme.Stack.empty(), and Scheme.Stack.stacklist.
Referenced by Scheme.Pair.searchb(), Scheme.RunEnv.unbind(), and Scheme.RunEnv.unbind1().
Member Data Documentation
int Scheme.Stack.maxelem = 10 [private]
maximal elements on the stack
Definition at line 12 of file Stack.java.
Referenced by Scheme.Stack.push(), and Scheme.Stack.Stack().
int Scheme.Stack.size = 0 [private]
the number of elements on the stack
Definition at line 9 of file Stack.java.
Referenced by Scheme.Stack.empty(), Scheme.Stack.pop(), and Scheme.Stack.push().
List Scheme.Stack.stacklist = new List() [private]
The : Stack is organized as list.
Definition at line 15 of file Stack.java.
Referenced by Scheme.Stack.pop(), Scheme.Stack.push(), and Scheme.Stack.top().
The documentation for this class was generated from the following file:
src/Scheme/Stack.java