/*
 * generated by Xtext 2.12.0
 */
package de.htwdd.sf.beleg.ui.tests;

import com.google.inject.Injector;

import de.htwdd.sf.beleg.s81170.ui.internal.S81170Activator;

import org.eclipse.xtext.testing.IInjectorProvider;

public class CustomPrologUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return S81170Activator.getInstance().getInjector("de.htwdd.sf.beleg.CustomProlog");
	}

}
