//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Tue Oct 04 16:12:10 CEST 2005
//----------------------------------------------------

package de.jamus.scheme;

/** CUP generated class containing symbol constants. */
public class sym {
	/* terminals */
	public static final int CHARACTER = 4;
	public static final int QUOT = 10;
	public static final int QUASIQUOT = 11;
	public static final int SYMBOL = 2;
	public static final int NUMBER = 6;
	public static final int VBEGIN = 15;
	public static final int DOLLAR = 9;
	public static final int BOOLEAN = 5;
	public static final int EOF = 0;
	public static final int STRING = 3;
	public static final int UNQUOT = 12;
	public static final int DOUBLE = 7;
	public static final int DOT = 8;
	public static final int error = 1;
	public static final int RPAREN = 14;
	public static final int LPAREN = 13;
}
